filesender/filesender

templates/guests_page.php
templates/upload_page.php

This triggers a more useful keyboard on mobile devices.

Make 'to' input fields of type template.

---

.travis.yml
classes/utils/Utilities.class.php
composer.json
composer.lock
includes/init.php

move from mt_rand() to a stronger random number generator

move to using a stronger random number generator

---

classes/rest/RestServer.class.php

There are only a few functions called this way, an explicit white list will help keep bad intentioned folks from exploiting this feature to inject unintended code.

limit what functions can be called by cgi

---

docs/index.md

Nicole updates

---

classes/data/Guest.class.php
classes/data/Recipient.class.php
classes/exceptions/GuestExceptions.class.php
classes/exceptions/UserExceptions.class.php
classes/rest/endpoints/RestEndpointGuest.class.php
includes/ConfigDefaults.php

The limits are fairly high by default so that most users will not ever hit them. But if a bot or bad person gets at things then they will not be able to go on forever.

fis010 limit guest creation and reminder sending

---

classes/data/Guest.class.php
classes/data/Recipient.class.php

This should clean up https://github.com/filesender/filesender/issues/72

tweak the new db columns with proper metadata

---

classes/utils/Config.class.php

131k is bad, 262k and above work ok
having some checks in here will help folks know that something is wrong in the config instead of them thinking that perhaps other things might be wrong in such cases.

encryption fails when chunk size is set much to low.

---

templates/guests_page.php
www/js/guests_page.js

If the guest is forced to get a link then they will be able to send to everybody by default.

Can only send to me makes no sense with get a link

---

classes/storage/StorageFilesystem.class.php
classes/storage/StorageFilesystemChunked.class.php
classes/utils/Config.class.php
dev/doc/filesender-2.0-config-directives-markdown.txt
docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php

Instead of merging the chunks into a single file in the files/ directory, this code creates a subdir with the uid and stores each chunk it's own file in the uid directory. This might help over time with fragmentation on normal filesystems because chunks are created, used, and reclaimed of the same size each time. Obviously with final chunks that are smaller than the whole chunk size.
One big use for this is handing data off to other distributed systems using FUSE. For example using an EOS setup to store content https://twiki.cern.ch/twiki/bin/view/EOS/WebHome

Storage: New StorageFilesystemChunked to store the chunks as individual files

---

classes/utils/Utilities.class.php
templates/admin_statistics_section.php

More info on the admin stats page how it should have been on mysql only render.

SQL: a bit more on quoting across backends

---

docs/v2.0/install/index.md

https://github.com/filesender/filesender/issues/106

DOCS: mysql install update

---

classes/auth/AuthSPSaml.class.php
classes/utils/Utilities.class.php
templates/transfers_page.php
templates/transfers_table.php
www/lib/graph/uploadGraph.php

A bunch of this is on the chart and pager.
One part is a long standing source of chatter from the saml class.

logs: remove some of the clutter that hits them

---

classes/storage/StorageFilesystem.class.php

This may seem like a silly thing to do, but it's not.
FileSender will never attempt to write overlapping chunks, so there is no risk of conflict.
However, locking may cause tremendous overhead in terms of time, especially when using an NFS backend.

Stop locking files on write

---

docs/v2.0/install/index.md

This is basically the code from https://github.com/filesender/filesender/pull/167 in a branch so I can merge it.

imported from jornane:20171026-ssp

---

classes/storage/StorageFilesystem.class.php

This fixes a number of issues that seem to have crept into the
storage_filesystem_hashing use. Specifically, files were not stored
into the created subdirectories, NFS support was lacking (df output
would throw an exception), and it seems to have been expected that the
entire subdirectory tree existed in one code path when it is created
on an on demand basis.
There are likely more to come as I retest this functionality but this
is a good first handful of updates.

storage_filesystem_hashing fixes: use path, nfs volumes, missing directories

---

www/js/transfer.js

It doesn't make much sense to compare the number of chunks that one worker
has uploaded relative to the others. This number will rely heavily on the
computer doing completely fair scheduling which there is no guarantee of.
Instead we are probably better off comparing a worker only to itself.
If it varies too much from it's past performance then we might have a
problem. If we are only starting an upload then a worker will not have
much history and so comparing to average of past chunk times will be a
little more prone to error. So there is more scope in there to be late
if we only have 1,2,3 chunk history as the worker is not established
yet and we don't have a good estimate for the mean for a chunk upload
for the worker.
This should hopefully avoid false positives for stall detection.

Stall Detection: avoid false positives

---

classes/storage/StorageFilesystemExternal.class.php
classes/storage/StorageFilesystemExternalStream.class.php

Hi,
Some missing translations for fr_FR.

fr_FR translations

---

www/js/upload_page.js

If the user cancels that dialog (cancel the stop) then start uploading
again too.

Pause uploading if the stop button is pressed.

---

docs/index.md
docs/v2.0/development-upgrade-notes/index.md
docs/v2.0/install/index.md
docs/v2.0/release/index.md

A good time to update the release page instructions as I was just doing a release.

Docs: small updates, refresh the release page instructions

---

classes/storage/StorageCloudS3.class.php
classes/storage/StorageCloudS3Stream.class.php
docs/v2.0/cloud/index.md
includes/ConfigDefaults.php
optional-dependencies/s3/.gitignore
optional-dependencies/s3/composer.json
optional-dependencies/s3/composer.lock
scripts/cloud/s3/test-s3-simple.php

This has not been tested against a real S3 server. It works against Zenko CloudServer.
See http://docs.filesender.org/v2.0/cloud/ for information on setup.

cloud: amazon s3 storage backend

---

docs/_includes/menu.html
docs/v2.0/i38n/index.md
scripts/language/common.php
scripts/language/import-translation-for-language.php

Some new scripts to bring in language translation updates from poeditor with some new documentation on how to use the scripts to bring in updates. I'll be using these soon to test and update the files for various languages so they will get more testing and possible updates.

i18n: ability to import translations from poeditor exports

---

language/en_AU/about_text.html.php
language/en_AU/lang.php
language/en_AU/site_splash.html.php
scripts/language/common.php
scripts/language/import-translation-for-language.php
scripts/language/sort-lang-file-and-write.php

The new sort script makes it possible to sort a lang.php, save a copy of that sorted file, and then import a langauge from poeditor and compare the lang.php lines with diff to see the exact changes.

i18n: script update and language import for en_au

---

scripts/language/common.php
scripts/language/import-translation-for-language.php
scripts/language/sort-lang-file-and-write.php

just the script updates. the actual import of en_au will be next.

i18n: import script updates

---

classes/auth/AuthSPSaml.class.php

Should solve issue #262
Namespace has changed in newer SSP

support for SSP 1.15.3 + older

---

scripts/cloud/azure/azure-simpleblob-benchmark.php

on a local azurite server I get the following...
```
Connecting to Azure server took 0.01 seconds
performance testing...
70.0 mb/s to write   1.0 mb to server, total time needed was 0.0 seconds
88.9 mb/s to write   5.0 mb to server, total time needed was 0.1 seconds
111.6 mb/s to write  10.0 mb to server, total time needed was 0.1 seconds
89.1 mb/s to write  50.0 mb to server, total time needed was 0.6 seconds
100.5 mb/s to write 100.0 mb to server, total time needed was 1.0 seconds
103.6 mb/s to write 200.0 mb to server, total time needed was 1.9 seconds
```

cloud azure: new benchmark script to get base level performance

---

classes/utils/Logger.class.php
docs/v2.0/admin/configuration/index.md

Gives admins the option to log in json format

add json logs option

---

docs/v2.0/admin/configuration/index.md

Hopefully this is a bit easier of a read and presented better in the browser.

docs: clean up the logging section a bit

---

docs/index.md
docs/v2.0/development-upgrade-notes/index.md
docs/v2.0/install/index.md

Update from referencing beta4 to reference rc1 instead.

docs: release update for rc1

---

docs/v2.0/faq/index.md
docs/v2.0/install/index.md

spaces become - if that helps too.

docs: references to id tags are all lower case

---

classes/rest/endpoints/RestEndpointTransfer.class.php

If the default is not to allow this then there isn't much point in
asking the end user of they want what they will not get.
https://github.com/filesender/filesender/issues/323

download page: only offer download email if option is available.

---

config-templates/apache/filesender.conf
config-templates/cron/filesender
config-templates/nginx/nginx.conf
config/config_sample.php
docs/v2.0/faq/index.md
docs/v2.0/install/index.md

These are some updates after running through a simple install on a Fedora 28 VM.

docs: getting ready for 2.0

---

.travis.yml
config/config_sample.php
docs/v2.0/install/index.md

run through postgresql install again and then switched to mariadb to check that part of the docs.

docs: tested this out on a Debian 9 vm

---

www/js/transfer.js

When a worker finished before the others it had nothing to do and would sometimes be shown as doing nothing (which is true) but that that was an issue (which is not).

stall detection: handle early finishing workers

---

templates/upload_page.php

Removed CloudStor specific template lines that are not used by FileSender

removed CloudStor specific template lines

---

www/js/upload_page.js

Something our users have been using for a while now

Make drop area clickable

---

classes/data/Transfer.class.php

fixed bug in Transfer.class.php. Pressing stop during a transfer triggered an error

fixed bug in Transfer.class.php

---

classes/rest/endpoints/RestEndpointUtility.class.php
classes/utils/TestSuiteSupport.class.php
unittests/selenium_tests/SeleniumTest.php
unittests/selenium_tests/tests/UploadAutoResumeTest.php

Test suites can now clear the cache of which things have happened
using a REST endpoint.

ci: rest endpoint to clear function call cache

---

config/config_sample.php
docs/_includes/menu.html
docs/v2.0/dev/testing/index.md
docs/v2.0/index.md

This was a little tricky to get going. I never managed to get firefox to go in the docker or local attempts.

docs: running selenium locally

---

templates/admin_statistics_section.php

A few cases in the SQL wher a div by zero was possible.

admin page sql potential div by 0

---

language/en_AU/lang.php

somehow this one got in the js code but not into the lang tr structure

i38n: empty_file term

---

classes/data/Authentication.class.php

This part was slightly ahead of it's time and the password_hash was the wrong choice for that hashing.

move to just sha1 for that

---

language/en_AU/lang.php
templates/user_page.php

This is still not ideal as it looks a bit auto generated. Maybe we should design the page itself and have some ways to disable the generation of some of the blocks rather than trying to use the generic $infos array to contain the php code that can generate controls from a general id,mode,generator type array entry.

updates for user profile page

---

docs/v2.0/install/index.md

Some updates for the new view stuff and permissions.

docs install db mariadb: update to instructions for views

---

classes/storage/Storage.class.php
classes/utils/Benchmark.class.php
lib/ubench/.gitignore
lib/ubench/.travis.yml
lib/ubench/README.md
lib/ubench/composer.json
lib/ubench/phpunit.xml.dist
lib/ubench/src/Ubench.php
lib/ubench/tests/UbenchTest.php

this sort of thing might move to a more statistics oriented reporting. Where you are not so much interested in what any one chunk write speed is but would like to have an overview.

allow benchmkarking writechunk

---

includes/ConfigDefaults.php

This is related to issue https://github.com/filesender/filesender/issues/401

enable the my profile page by default

---

classes/auth/Auth.class.php
classes/data/User.class.php
classes/rest/endpoints/RestEndpointTransfer.class.php
includes/ConfigDefaults.php

This relates to the issue https://github.com/filesender/filesender/issues/403

quotas: handle zero as unlimited and force save when value changes

---

classes/data/File.class.php
classes/data/Guest.class.php
classes/data/Transfer.class.php
classes/utils/DatabasePgsql.class.php
scripts/upgrade/database.php

This is an update to some of the code from
https://github.com/filesender/filesender/pull/414

sql: bring back more advanced view, fk creation no longer uses if exists

---

.php_cs.dist
composer.json
docs/_includes/menu.html
docs/v2.0/dev/formatting/index.md
reformat-code.sh

This will allow the formatting shown in https://github.com/filesender/filesender/pull/307 to be generated on demand and thus make it easy to keep things up to date.

formatting: add script to format code

---

docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php
www/filesender-config.js.php
www/js/crypter/crypto_app.js
www/js/upload_page.js

This should address https://github.com/filesender/filesender/issues/472 see the issue for more information.

crypto: allow the key version to be set in config.php

---

templates/user_page.php

As per https://github.com/filesender/filesender/issues/478 I have moved the actions to the end of the page to make the (more used) preferences appear at the top.

myprofile: move actions to the end of the page

---

language/en_AU/lang.php
templates/user_page.php

This makes the top level menu privacy button just one way for the user to see this information.

my profile: add a link to the privacy page in there

---

docs/_includes/menu.html
docs/v2.0/i18n/index.md

this relates to the subject not being set correctly for some locales https://github.com/filesender/filesender/issues/417.

docs: make sure not to translate the subject keyword from english in the email headers

---

classes/utils/Lang.class.php

This will help for emails that are generated unattended such as in https://github.com/filesender/filesender/issues/301.

translation: do not halt when a typo causes a bad property access

---

scripts/upgrade/database.php

Warn sys admins that after a *major* database update they might like to confirm a rollback as completed.
This relates to https://github.com/filesender/filesender/issues/453

db update: a warning on major updates

---

language/en_AU/lang.php
scripts/language/oldterms.txt

The invalid_file_name term was not in any translation. All three terms are now already pushed to poeditor.

i18n add new terms

---

language/sl_SI/lang.php

Fix lost file_encryption_description translation from importing. Also fixed on POEditor.

fix file_encryption_description

---

www/js/translate_email_page.js

This follows the same pattern as other template.php files and allows easy future expansion.

add stub translate_email_page.js file to avoid 404

---

docs/v2.0/install/index.md

Some information about disabling modules, turning on some settings in config.php, and bringing out the recommended commands for salt and admin password setting into command lines. Setting the admin module to false didn't seem to disable serving the admin directory so I added removing that directory to the recommendations.

docs: some more thoughts on simplesamlphp configuration

---

classes/data/FileCollection.class.php

The database error is a little rough looking. We will not get data by trying it with an empty IN () anyway, so don't do that.

collections: if no ids then return empty

---

www/js/terasender/terasender_worker.js

Turns out for some IE11 using a timeout to see if things worked breaks things.

ie11 fix for timeouts

---

.travis.yml
unittests/selenium/SeleniumTest.php

This relates to https://github.com/filesender/filesender/issues/598
lets check the version of that file

Trying to resolve selenium ci issue

---

classes/utils/Archiver.class.php

This should fix the issue #594

fix to function getTarSize from Archiver.class.php, tar archive filename was null

---

classes/utils/Archiver.class.php

Correct code currently relies on firstly not sending headers during size calculation and then sending them before streaming the virtual archive. This method is only called from download.php right now and does not use the withHeaders parameter. If there is a need for sending the archive without any headers in the future then it will be better to readd this parameter and ensure that it works as expected in the future.

archive: streamArchive withHeaders parameter is a relic and should be removed.

---

classes/rest/endpoints/RestEndpointTransfer.class.php

This should fix https://github.com/filesender/filesender/issues/596

aup: allow transfer modification

---

CONTRIBUTE.md

This relates to https://github.com/filesender/filesender/issues/585

docs: update poeditor link

---

classes/data/Transfer.class.php
docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php
templates/guests_page.php

Using SQL directly here will be more efficient. Some more filtering is optionally added.

guests: use sql directly in fromGuestsOf and allow restriction

---

classes/data/constants/DBConstantBrowserType.class.php
classes/data/constants/DBConstantOperatingSystem.class.php

As mentioned at the end of #557, this should help avoid generating email from cronjobs that output something to STDOUT or STDERR.

Fix Undefined index: HTTP_USER_AGENT

---

classes/data/constants/DBConstantBrowserType.class.php
classes/data/constants/DBConstantOperatingSystem.class.php

Thanks for catching this @fkooman, all the constants in the two changed files' paths in #629 must have confused me. ;) Hopefully with this PR issue #557 can be closed for good.

Amend #629 w/ proper fix for #557, as per @fkooman

---

classes/auth/Auth.class.php

These lines shouldn't have been here after testing was complete.

debug: cleanup

---

unittests/selenium/tests/EncryptionTest.php

I am not sure if the older browser used in CI will do these GCM modes or not. Let's find out!

ci: lets see if the old browser in ci can handle these modes

---

www/js/terasender/terasender.js
www/js/transfer.js

This in particular allows non terasender upload/download to work with aead and fileiv.

refactor the aead and fileiv handling to simplify multiple code paths

---

docs/v2.0/release/index.md

The first point was already handled, the second slipped the list so I am adding to the main release notes to make it harder to miss it next time around.

docs: update the release notes, notes

---

classes/utils/DBI.class.php
classes/utils/DatabaseForeignKey.class.php
classes/utils/DatabaseMysql.class.php

mostly for passing an empty array() to the exists call so as not to trigger an attempt to add existing fks

cleanup for database update script

---

classes/data/AuditLog.class.php
classes/data/Transfer.class.php

A slight modification to use the Recipient::getDBTable() instead of the updated case directly but this is based on: https://github.com/fransward/filesender/commit/29beee5f5fdba63e6d4a28a612d32653b1256dbe

mysql: updates for table name case and delete from sql

---

www/js/crypter/crypto_app.js

This also involves some quite old code such as the file decrypt dialog. Since much of the code was prefixed I thought I would make it all prefixed.

use window.filesender everywhere

---

classes/utils/DatabaseUpsert.class.php
classes/utils/EpochType.class.php

These were using error() but are just normal low level debug logs

hush non error messages

---

language/nl_NL/accepttoc.html.php

This is from a run of the import-all-from-poeditor.sh wrapped inside git branch, commit and push. The branch name includes year, month, day, and epoch-seconds to ensure uniqueness even if run many times a day.

i18n: auto import from poedtor on 2019-11-19-1574142468

---

classes/data/AuditLog.class.php
classes/utils/DBView.class.php

This is an update of https://github.com/filesender/filesender/pull/696/files against development branch

db: update auditlogs query for pg and mariadb compat

---

www/js/crypter/crypto_app.js

fixes for ie11

---

language/en_AU/lang.php
templates/user_page.php
www/js/logger.js
www/js/user_page.js

New buttons to send and clear the client logs in the my profile page. This will help with issues like https://github.com/filesender/filesender/issues/700 where clientlogs are not being sent.

clientlogs: buttons to send and clear them

---

templates/admin_users_section.php

This fixes the display of border issue in the clientlogs table mentioned in https://github.com/filesender/filesender/issues/700

admin-users-page-clientlogs-table-border-fix

---

language/en_AU/lang.php
templates/transfers_table.php
templates/user_page.php
www/js/admin_users.js
www/js/crypter/crypto_app.js
www/js/crypter/crypto_blob_reader.js
www/js/crypter/crypto_common.js
www/js/filesender.js
www/js/logger.js
www/js/pbkdf2dialog.js
www/js/terasender/terasender.js
www/js/terasender/terasender_worker.js
www/js/transfer.js
www/js/upload_page.js
www/js/user_page.js

Reverts filesender/filesender#734

Revert "2020/jan/my transfers div"

---

classes/data/AuditLog.class.php

We noticed a significant performance increase with this new index while running stress tests on our next filesender infrastructure.

Add index on AuditLogs.created

---

includes/ConfigValidation.php

Pull request allows the client ip source header to have multiple candidates, configuration validator needs to reflect this.

Update validator to match pr #751

---

language/en_AU/bounce_report.mail.php
language/en_AU/daily_summary.mail.php
language/en_AU/download_complete.mail.php
language/en_AU/email_feedback.mail.php
language/en_AU/file_deleted.mail.php
language/en_AU/files_downloaded.mail.php
language/en_AU/guest_access_upload_page.mail.php
language/en_AU/guest_cancelled.mail.php
language/en_AU/guest_created.mail.php
language/en_AU/guest_created_receipt.mail.php
language/en_AU/guest_expired.mail.php
language/en_AU/guest_reminder.mail.php
language/en_AU/guest_upload_complete.mail.php
language/en_AU/guest_upload_complete_confirmation_to_guest.mail.php
language/en_AU/guest_upload_start.mail.php
language/en_AU/recipient_deleted.mail.php
language/en_AU/recipient_feedback.mail.php
language/en_AU/report_attached.mail.php
language/en_AU/report_inline.mail.php
language/en_AU/storage_usage_warning.mail.php
language/en_AU/transfer_autoreminder_receipt.mail.php
language/en_AU/transfer_available.mail.php
language/en_AU/transfer_deleted.mail.php
language/en_AU/transfer_deleted_receipt.mail.php
language/en_AU/transfer_expired.mail.php
language/en_AU/transfer_expired_receipt.mail.php
language/en_AU/transfer_reminder.mail.php
language/en_AU/upload_complete.mail.php

This is a general language import. It should help https://github.com/filesender/filesender/issues/737

i18n: auto import from poedtor on 2020-03-01-1583063700

---

www/js/upload_page.js

This is a slight addition to https://github.com/filesender/filesender/pull/755

recheck send is ok when generate password is clicked

---

docs/known-installs.md

* Remove a few dead URLs
* Fixed URLs that had changed paths
* Replace https://filesender.teiath.gr/ by https://filesender.uniwa.gr/ - as indicated by the cert
* Added explicit links

Cleanup of known-installs.md

---

classes/data/DBObject.class.php
language/en_AU/lang.php
templates/statistics_page.php

In order to avoid doing a 
```
SELECT count(*) from TABLE
```
a new countEstimate method was introduced in DBObject.class.php. The result might not be 100% accurate but should be fast to compute.
The first example of this new method relates to https://github.com/filesender/filesender/issues/582

stats: show user count estimate on statistics page

---

classes/rest/endpoints/RestEndpointTransfer.class.php
classes/utils/Utilities.class.php

Prevent guests from trying to change some settings

computest-413: test against attempts to modify settings

---

classes/rest/endpoints/RestEndpointUser.class.php

There was a bad interaction between the new User POST rest handler from https://github.com/filesender/filesender/pull/762 and https://github.com/filesender/filesender/pull/765.

bad interaction between new localdb auth and moved freq recip to POST code

---

classes/rest/endpoints/RestEndpointUser.class.php

This contains the resolution for issue https://github.com/filesender/filesender/issues/782
This was also reported on the mailing list and the solution confirmed to work
https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2020-04/msg00019.html

release 2.17 changes

---

language/en_AU/lang.php
templates/user_page.php
www/js/admin_users.js
www/js/crypter/crypto_app.js
www/js/crypter/crypto_blob_reader.js
www/js/crypter/crypto_common.js
www/js/filesender.js
www/js/logger.js
www/js/pbkdf2dialog.js
www/js/terasender/terasender.js
www/js/terasender/terasender_worker.js
www/js/transfer.js
www/js/upload_page.js
www/js/user_page.js

This is an update to https://github.com/filesender/filesender/pull/733 with use of saveAs() and coming from a branch rather than development in remote repository.

clientlogs: update to allow export

---

.travis.yml
scripts/dataset/dumps/filesendercron-touch.pg
scripts/dataset/dumps/filesendercron.pg
travis/scripts/postgresql-setup.sh
unittests/config_tests_filesender.xml
unittests/tests/cron/CronTest.php
unittests/tests/dataset/CronTest.php

This is a start. I might also be useful to move this to after the data is inserted into the database or create some stuff for the script to clean out.

run the cron job during CI to help detect issues with that

---

language/en_AU/lang.php
templates/admin_transfers_section.php
templates/transfers_table.php
www/css/default.css
www/js/admin_transfers.js

This relates to the request from the community for improved admin/transfers section https://github.com/filesender/filesender/issues/747.
This allows searching for an explicit transfer range.

admin: transfers allow search by id range

---

templates/admin_transfers_section.php

This may help if testing when changing the page_size in admin / transfers and getting unexpected outcomes.

ui: admin transfers pass page size

---

scripts/language/oldterms.txt

New terms added locally, exported through 
```
./export-terms-to-new-and-deleted-lists.sh
```

oldterms update

---

docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php

Add some docs for these config settings.

rate limits: add the needed docs

---

classes/rest/endpoints/RestEndpointClientlogs.class.php

This is the fix from https://github.com/filesender/filesender/issues/811

strange, seems that codeformatter was last to change this in git log

---

templates/transfers_table.php
unittests/selenium/SeleniumTest.php
unittests/selenium/tests/EncryptionTest.php

These complete in less time and have stronger assertions about the expected thing happening.

CI: starting to update tests

---

docs/v2.0/install/index.md

This is a slight update to https://github.com/filesender/filesender/pull/831 to be created against development and change the PASS to PASSWORD instead of the other way around.

docs: update the PASS to match declared PASSWORD

---

config-templates/cron/filesender

This relates to https://github.com/filesender/filesender/issues/842

cron job remove call to EOF command

---

scripts/language/README.md
scripts/language/common.php
scripts/language/convert-php-to-poeditor-json.php
scripts/language/send-json-translations-for-language-to-poeditor.sh

Terms to be exported can be selected using a regex or all terms are exported. See the new README.md file from the  scripts/language subdir for more information, it is a better place for that than here.

i18n: scripts to export selected terms from the local repository to poeditor

---

docs/v2.0/i18n/index.md
language/README.language

Update to point to the web site and to poeditor.com

i18n: update stale documentation

---

scripts/testing/test-database-transactions-mariadb.php
scripts/testing/test-database-transactions-postgresql.php
scripts/upgrade/database.php

MariaDB doesn't transact DDL statements.

db: warning for DDL and MariaDB

---

templates/header.php

During testing of https://github.com/filesender/filesender/pull/867 I noticed this code could cause problems when an exception is thrown from one of the calls. As it is just for presentation it shouldn't effect the loading of the rest of the header.

better support for early exceptions

---

www/js/terasender/terasender_worker.js

If the server sent back a integrity_check_failed during the uploading of a chunk then retry to send that chunk. I have left the failing on send_attempts here in case there is some issue server side and we don't want to have more and more clients trying to upload more and more chunks because there is no fail state.
This may be useful for https://github.com/filesender/filesender/pull/879.

core: allow auto retry if the server didnt like the chunk

---

docs/v2.0/admin/configuration/index.md

Document encryption_enabled setting

---

classes/data/Transfer.class.php
language/en_AU/lang.php
templates/admin_transfers_section.php
www/js/admin_transfers.js

This should allow you to find a transfer given the sender email address. This is to help administration as highlighted in https://github.com/filesender/filesender/issues/888.

admin: allow search for transfer by sender email

---

templates/upload_page.php

Most testing, this time with "can only send to me" set and a guest upload workflow.

bootstrap: these options do not make sense if you can only send to the user who invited you

---

classes/data/Transfer.class.php

Remove debug variable dump so that cronjob stdout doesn't get polluted.

Remove debug output

---

language/en_AU/lang.php
templates/upload_page.php
www/css/default.css
www/js/upload_page.js

This improves the workflow when you return to the upload page and have to readd the files again in the bootstrap UI.

bootstrap: improved readd transfer interaction

---

www/js/upload_page.js

remove the message, and once all is set just remove the "add files" part too, you can not add more files to the existing transfer.

bootstrap ui: make that readd a little cleaner

---

www/js/crypter/crypto_app.js

This was a squashed box looking item before.

bootstrap ui: fix the show password checkbox

---

www/js/upload_page.js

The best default I can see is to ask if the user wants to stop the whole thing. Editing of the transfer is not supported right now.

bootstrap ui: handle back button on active upload

---

www/js/upload_page.js

a bit cleaner to use accessors to get at those options.

bootstrap: cleanup the code a little more

---

templates/upload_page.php
www/js/transfer.js
www/js/upload_page.js

This moves the language selector on the upload page to the new flag choice.

bootstrap use the flag decorated selector for upload specific lang

---

classes/storage/StorageFilesystemChunked.class.php
www/js/transfer.js
www/js/upload_page.js

This may need some review, but this commit adds:
- Hashing of the incoming stream and compare to what ends up stored on disk
- Verification of the upload size
- Update javascript to handle FileIntegrityExceptions and add a waiting state while a file is hashed.
- Refactor StorageFileSystemChunked

Add file integrity validation to StorageFilesystemChunked class

---

www/js/transfer.js

I didn't notice the end of function was missing in https://github.com/filesender/filesender/pull/987.

missing end of function

---

templates/menu.php
templates/pagemenuitem.php
www/css/default.css

Hi Ben (I assume you're reading this)
I made the menu a tad more responsive and added favicons to all the menu items. When the width of the screen gets too narrow, the menu becomes a 'hamburger'. 
Cheers
- Renato

responsive menu and favicons for all the menu items added

---

docker/Dockerfile

Introduce 4 new arguments to the dockerfile:
REF: Release reference / release version
REF_SUM: Release checksum
SSP_REF: Simplesamlphp release reference
SSP_REF_SUM: Simplesamlphp release checksum
Needed by #956

feat: Introduce 4 new build arguments for docker

---

README.md
ci/setup-machine.sh
unittests/selenium/SeleniumTest.php
unittests/selenium/tests/LanguageSelectTest.php
unittests/selenium/tests/UploadAutoResumeTest.php

Now that selenium is able to run in the cloud again I am bringing in some of the updates from that fork.

selenium: some updates from filesenderuici fork

---

www/js/zip64handler.js

This is a comment only update.

comments: zip64 handler call the sig a magic number instead

---

docs/v2.0/admin/configuration/index.md

Documentation for options
* tmp_path
* report_bounces
* report_bounces_asap_then_daily_range
* user_page
* terasender_disableable
* guest_limit_per_user
* guest_reminder_limit config options
Related to #939

Add documentation for 7 config options

---

includes/init/init_web.php

This API call version requires php 7.3 or above.

cookies: make a selection on samesite default setting

---

scripts/dev/www-lib-update/update-library-versions-from-node_modules.php
www/lib/streamsaver/StreamSaver.js

The script to update streamsaver is also updated to remove the default URL in the future.

This vacates the default URL for mitm in StreamSaver

---

www/js/crypter/crypto_app.js
www/js/crypter/streamsaver_sink.js
www/js/download_page.js

This should make things more explicit by adding the test at a higher level in the code as well as lower down.

StreamSaver: bring forward test

---

language/locale.php

Thanks for the display name from https://github.com/filesender/filesender/issues/1078

i18n: update Brazilian Portuguese display name

---

classes/avprograms/AVProgram.class.php
classes/avprograms/AVProgramEncrypted.class.php
classes/data/constants/DBConstantAVProgram.class.php
scripts/task/execute-av-program-on-files.php

This adds https://github.com/filesender/filesender/pull/1085 to avoid having files returned more than once if they are encrypted.

release 226 addition to avprograms for encrypted

---

templates/transfers_table.php

This is based on the PR https://github.com/filesender/filesender/pull/1099 but uses fa-lock instead of emoji.

add a lock near transfer id for encrypted transfers 

---

www/js/upload_page.js

This relates to the tail end of https://github.com/filesender/filesender/issues/1088

hide password validation details if encryption is turned off

---

www/js/graph/uploadGraph.php

This brings back the y axis label and trims the dates back to remove the 00:00:00 which provides only clutter. Mostly an update to how the metadata is presented to make it effective again.

make the upload page graph nicer

---

classes/data/Transfer.class.php

This relates to https://github.com/filesender/filesender/issues/1052

add secondary index on transfers.expires to help cron execution times

---

classes/data/Recipient.class.php
docs/v2.0/admin/configuration/index.md

This adds some docs for some things from ConfigDefaults.php that did not have information before.
This is a partial resolution for https://github.com/filesender/filesender/issues/939. Best to make some sort of start rather than delaying to get everything done in one go.

docs: more info on some config directives

---

classes/data/DBObject.class.php
classes/data/User.class.php
classes/rest/endpoints/RestEndpointGuest.class.php
classes/rest/endpoints/RestEndpointTransfer.class.php
classes/rest/endpoints/RestEndpointUser.class.php
release-development.sh
scripts/language/oldterms.txt
scripts/task/export-user.php
templates/privacy_page.php
templates/transfers_table.php
templates/user_page.php
www/download.php
www/js/upload_page.js
www/js/user_page.js

At commit `d6c91cf0` a patch was added to the bootstrap branch which incorrectly reverted a few previous commits. 
This patch was made with similar commands to the following (hash 830ee970 is the then tip of development).
```
git checkout 2021/feb/bootstrap
git diff 830ee970 > 2021-feb-bootstrap-to-development-v2.patch
```
To find these the missing patches a new branch was taken from 2021/feb/bootstrap and then merging in 830ee970 (which at the time was the tip of the development branch) and conflicts were resolved giving a local branch called 2021/feb/bootstrap-merge-with-830ee970. A diff from 2021/feb/bootstrap-merge-with-830ee970 to 830ee970 was then taken. The critical part here is that this diff to 830ee970 would not try to remove code from 830ee970 which was already merged into …

A few older patches from around the ending of work on 2021/feb/bootstrap

---

docs/known-installs.md

This is the changes from https://github.com/filesender/filesender/pull/1142 updated to merge with development.

add Cyprus | Frederick University to known installs

---

scripts/client/filesender.py

This is the update from https://github.com/filesender/filesender/pull/1153 made against the `development` branch.

udpate to pr 1153 to target development

---

unittests/selenium/SeleniumTest.php

A quick direct look first should be more workable than the two css classes.

dev3 ci: a better check for a quick transition to stage4

---

www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1150

ui: check that msg does not contain password on password entry too

---

unittests/selenium/SeleniumTest.php
unittests/selenium/tests/LanguageSelectTest.php

dev3 update for lang sel in cloud2

dev3: selenium add support for language selection on small screen

---

classes/auth/AuthSPSaml.class.php
templates/menu.php
www/css/default.css
www/saml_logout.php

Moving to using a POST request and allow CSRF check if enabled with
```
$config['owasp_csrf_protector_enabled'] = true;
```

SAML logout update

---

language/en_AU/lang.php
www/js/service_aup_page.js

This relates to https://github.com/filesender/filesender/issues/1216

Update for service AUP translation string

---

scripts/generate-report-version-information.php

This should hopefully make it a little easier to gather browser, apache, php, database version information for people reporting issues.

issues: new script to gather system information

---

www/js/client.js

This relates to https://github.com/filesender/filesender/issues/1305.

just always return that token to allow the server to decide if the check should be done

---

classes/utils/DatabaseMysql.class.php

This relates to https://github.com/filesender/filesender/issues/1309

mariadb: update for index check in database.php

---

language/cs_CZ/guest_created.mail.php
language/da_DK/guest_created.mail.php
language/de_DE/guest_created.mail.php
language/en_AU/guest_created.mail.php
language/es_ES/guest_created.mail.php
language/et_EE/guest_created.mail.php
language/fa_IR/guest_created.mail.php
language/fi_FI/guest_created.mail.php
language/hr_HR/guest_created.mail.php
language/it_IT/guest_created.mail.php
language/ja_JP/guest_created.mail.php
language/nl_NL/guest_created.mail.php
language/pl_PL/guest_created.mail.php
language/pt_BR/guest_created.mail.php
language/ru_RU/guest_created.mail.php
language/sl_SI/guest_created.mail.php
language/sr_RS/guest_created.mail.php
language/tr_TR/guest_created.mail.php

Bug fix in email templates which would show today's date as expiry when "does not expire" is ticked.

do not show todays date in email when guest voucher does not expire

---

classes/exceptions/Exceptions.class.php

Clean potential template injections from user-provided data upon de-serializing storable exceptions

Fix storable exceptions template injection

---

classes/utils/DatabasePgsql.class.php

This relates to https://github.com/filesender/filesender/issues/1323 and should now allow the database.php script to execute properly again.

psql: handle numeric type better

---

scripts/upgrade/database.php

This relates to issue https://github.com/filesender/filesender/issues/1300

db: add a config sanity check in database.php

---

classes/data/AuditLog.class.php
templates/report_html.php
templates/report_pdf.php
templates/report_plain.php

This relates to https://github.com/filesender/filesender/issues/1329

if there was an error getting some author info do not except

---

ci/php-config.ini
config-templates/filesender-php.ini
docs/v2.0/development-upgrade-notes/index.md
docs/v2.0/install/index.md

This related to https://github.com/filesender/filesender/issues/1320

docs: remove some outdated information

---

scripts/client/filesender.py

This was created for easier testing to resolve https://github.com/filesender/filesender/issues/1324

rest python: ability to make new guest from command line

---

config-templates/cron/filesender
scripts/task/cron.php

This relates to https://github.com/filesender/filesender/issues/1351
The cron job should relinquish privileges.

run cron job as apache/www user

---

config/config_sample.php
docs/v2.0/install/index.md

More information for "Step 8 - Update your FileSender config.php"
People who have installed FileSender will know that site_url et al will need to be updated. It is helpful to hint to the reader the keys they should look to update here to make the process easier.

docs: update step 8 to hint which config keys a user might need to update.

---

docs/v2.0/install/index.md

More information and better reflect the current state of affairs.

docs: mention master and master3 in the git install section

---

docs/v2.0/install/index.md
scripts/install/simplesamlphp-extract-sha256-from-release-notes.php

Also, a new php script to help verify the sha256 of simplesamlphp download :)

docs: update simplesamlphp section a little bit.

---

language/locale.php
scripts/language/import-all-from-poeditor.sh
scripts/language/import-langs-directory.sh

I will do a batch import soon to test this :)

i18n add Sinhalese to automatic import from poeditor script

---

language/si_LK/lang.php

Seems that one new line at the end of the term made things not work. I can now switch to Sinhalese and things work as expected. I personally can't read things but the site functions! :)

i18n: auto import from poedtor on 2023-02-07-1675763886

---

templates/admin_transfers_section.php
www/js/admin_transfers.js

This is 4.1.7 of Computest Jan. 2, 2023 Version 1.0.

move this to POST

---

classes/rest/endpoints/RestEndpointTransfer.class.php
classes/utils/Utilities.class.php

A check that the aead data has the expected format.
This relates to 4.1.2. of Computest Jan. 2, 2023 Version 1.0.

sanity: check that the aead data is in the epected format

---

classes/utils/Lang.class.php

This relates to https://github.com/filesender/filesender/issues/1382

lang: do not log null if fallbackid is not set

---

scripts/language/convert-php-to-poeditor-json.php
scripts/language/oldterms.txt

The output from this script was updated on poeditor so it knows the new terms as well.

i18n: bring in new terms from password reuse PR

---

language/en_AU/lang.php
scripts/language/oldterms.txt

This adds three of the terms cited in https://github.com/filesender/filesender/issues/1235 and on poeditor too

i18n: three of the new terms cited in issue 1235

---

classes/utils/Config.class.php
docs/v2.0/admin/configuration/index.md

See https://github.com/filesender/filesender/issues/1381

Allow overrides based on attributes

---

classes/utils/Principal.class.php
docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php
templates/upload_page.php
www/filesender-config.js.php
www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1398

encryption: new option to make generated password mandatory

---

templates/admin_transfers_section.php

fix the search URL in admin_transfers

---

templates/upload_page.php

This relates to https://github.com/filesender/filesender/issues/1398#issuecomment-1446211448

Trim off the template update, the setting is done in the js file.

---

classes/rest/endpoints/RestEndpointGuest.class.php

Hello, I have created a fix for my issue #1411 and would like to ask for a review.

fix use custom S3 bucket for Guest Uploads

---

classes/utils/Config.class.php

This relates to https://github.com/filesender/filesender/issues/1417 and will help to make sure that the upload and download chunk sizes match for cloud setups.

checks: make this test case insensitive to help site admins

---

www/js/crypter/crypto_app.js
www/js/crypter/streamsaver_sink.js
www/js/download_page.js
www/js/filesender.js
www/js/terasender/terasender.js

This relates to https://github.com/filesender/filesender/issues/1410

possible include race: avoid scoping this variable

---

templates/admin_transfers_section.php

Display page navigation depending on the number of transfers on Admin_Transfers
* Cannot confirm all transfers on Admin_Transfers page if the transfers are over 8 page.

Display page navigation on Admin_Transfers page

---

classes/storage/StorageCloudS3.class.php
classes/utils/Archiver.class.php
optional-dependencies/s3/composer.lock

This should address the cloud issue reported in https://github.com/filesender/filesender/issues/1417

server side tar: allow tar files to be created for cloud backed storage

---

classes/constants/GuestOptions.class.php
classes/data/Guest.class.php
classes/data/Transfer.class.php
docs/v2.0/admin/configuration/index.md
language/en_AU/lang.php
templates/upload_page.php
www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1443

Some new guest options for expire time

---

www/js/notification.js

This relates to https://github.com/filesender/filesender/issues/1429.

update to notifications for safari

---

language/en_AU/lang.php
templates/user_page.php

This relates to https://github.com/filesender/filesender/issues/1438

i18n: move the heading to a translation string

---

templates/transfers_table.php

A small update to https://github.com/filesender/filesender/pull/1455 to bring back https://github.com/filesender/filesender/pull/1426.

This brings back PR 1426

---

classes/storage/StorageCloudS3.class.php

cron.php re-deletes all transfers when it's time to permanently purge them from the database. When StorageCloudS3 was configured to use per-file buckets or daily buckets, cron.php was eventually failing with `deleteFile() error exception 'Aws\S3\Exception\S3Exception'` because S3 backend returned a NoSuchBucket error when trying to list the contents of that (already deleted) bucket.
I believe NoSuchBucket can be safely ignored when deleting files so I've changed the exception handler in StorageCloudS3 / deleteFile to ignore this particular error.
This is related to #1455 but same error should also happen when using per-file buckets.

Ignore NoSuchBucket exception in deleteFile (StorageCloudS3 class)

---

templates/upload_page.php

This relates to https://github.com/filesender/filesender/issues/1470

bootstrap: move the upload graph below the continue button

---

docs/v2.0/admin/configuration/index.md

This takes the ConfigDefaults update from https://github.com/filesender/filesender/pull/1466 and puts it into the docs as an example for site admins to consider.

docs: docuemnt valid_filename_regex and add an example from makinog3

---

www/filesender-config.js.php

This was suggested in https://github.com/filesender/filesender/pull/1466. I have split out the code to allow the comment to stand inline so that the rationale behind the str_replace is known to future readers.

convert unicode surrogate pairs for use in javascript (from makinog3)

---

docs/v2.0/admin/configuration/index.md

Some information brought forward from the initial PR into the docs for av programs and some extra wording etc to help new users take advantage of this feature. This relates to https://github.com/filesender/filesender/issues/1481

docs: more avprogram info

---

includes/init/init_web.php

This relates to https://github.com/filesender/filesender/issues/1488

move that to only be called if no session exists already

---

classes/auth/AuthRemote.class.php
classes/data/Transfer.class.php
classes/data/User.class.php
classes/rest/endpoints/RestEndpointUser.class.php
www/js/transfer.js

These case here doesn't matter to PHP but it can make some analysis tools raise an eyebrow.

make these User::fromAuthId calls caseConsist

---

.gitignore

Tinkering with LSP git ignore those files

---

language/locale.php

language: allow Korean to be selected from the menu

---

www/js/ui.js

Update ui.js popup buttons text, strip out html tags from lang.tr() on button text

Update ui.js popup buttons text

---

docs/v2.0/admin/configuration/index.md

A few more config options that were not in the docs from a fair while back. This relates to https://github.com/filesender/filesender/issues/1519

docs for stats

---

docs/_includes/menu.html
docs/v2.0/install/index.md
docs/v2.0/upgrade/index.md

A starting point for an upgrade page to compliment the installation information.

docs upgrade info

---

templates/upload_page.php

This is an update to https://github.com/filesender/filesender/pull/1532/files against development3.

update to 1532 to be against developement3

---

classes/utils/Mail.class.php
docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php

This relates to https://github.com/filesender/filesender/issues/1533

Make the -r option to mail() be optional

---

docs/v2.0/install/index.md

This documentation update was kindly suggested by Meindert van den Berg.

docs: update install package names on Fedora

---

scripts/client/filesender.py

Here is my improvements to @PaulLocksley Python Client:
- removed -d
- able to just give it folder(s)/file(s) in args and python works it out
- sort file list
- include filesender max_transfer_files, so we don't spam filesender
should solve https://github.com/filesender/filesender/issues/1549

FileSender Python Client: recursive dir 

---

www/js/crypter/crypto_blob_reader.js
www/js/terasender/terasender_worker.js

This needs more testing before a release. It is being merged today to make it easier for an NREN to test it in their suite.

chrome encrypted upload memory hunger

---

scripts/client/filesender.py

Hi Filesender team, 
Now that the FileSender.py client can take directories I feel like its worth handling the edge cases of a large amount of small files. 
Currently the client can only action one file at a time, this wastes upload slots and makes uploads containing multiple files take longer than necessary. I changed it so that we can work on multiple files at once.
There are some costs with my approach, we use slightly more memory and single file transactions are slightly slower. 
I have included some test run details below with performance characteristic differences
| File              | Script | Run 1       |        | Run 2       |      | Run 3       |      | Average     |      | Dev to Prod average delta |       |
| ----------------- | ------ | ----------- | ------ | ----------- | …

FileSender.py performance changes. 

---

classes/rest/endpoints/RestEndpointTransfer.class.php

This relates to https://github.com/filesender/filesender/issues/1555.

rest allow the fileids to get obtained if you know the token and are authenticated

---

templates/upload_page.php

This should allow translations and functionality again on the upload landging page.

ui3: fix from https://github.com/filesender/filesender/pull/1530#issuecomment-1746270986

---

classes/utils/Version.class.php
docs/v2.0/admin/configuration/index.md
templates/footer.php

Bump to contained version, added note to release docs to update that string, added a very simple example to disclosed in the docs.
This relates to https://github.com/filesender/filesender/issues/1643

a fix for 2023/nov/issues/1643

---

templates/guests_table.php

removal of commented code. boom.
relates to https://github.com/filesender/filesender/issues/1639

fix for issues/1639

---

templates/invitation_detail_page.php

This is not an ideal fix but certainly much better than showing a malformed page.
Relates to https://github.com/filesender/filesender/issues/1634.

fix for issues/1634

---

www/js/download_page.js

Fix for https://github.com/filesender/filesender/issues/1630
So SELECT LINHA -> SELECT LINE
which could be left in there as something like "select file entry on change". Might be useful to be a bit more verbose if we are wanting it to stick around.

fix for issues/1630

---

templates/user_page.php

I have left the last one in there as it is conditional and $id is used twice.
This relates to https://github.com/filesender/filesender/issues/1628.

indirect property access

---

www/js/upload_page.js

This should fix https://github.com/filesender/filesender/issues/1594
It works ok with the exact path mentioned in the issue. May regress on other interaction paths.

dev3 ui3 fix for password in message issue 1594

---

templates/user_page.php

This is a fix for https://github.com/filesender/filesender/issues/1603

dev3 ui3 fix for clear api secret issues/1603

---

classes/rest/endpoints/RestEndpointTransfer.class.php

I got an error on direct options[key] access for this line.

The option method has the ability to fallback under failure

---

www/js/download_page.js

This relates to https://github.com/filesender/filesender/issues/1646

Update the dangling reference to that message

---

templates/download_page.php

This relates to https://github.com/filesender/filesender/issues/1645

That is an array not an object

---

docs/v2.0/admin/configuration/index.md

Some docs for transfer_automatic_reminder. This was lacking and sought with  https://github.com/filesender/filesender/issues/1679

docs for transfer_automatic_reminder

---

www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1618

d3ui3 if there is no download link then do not show that section

---

templates/upload_page.php

This relates to https://github.com/filesender/filesender/issues/1626

Remove unused files_actions_div_extra_class

---

classes/data/Transfer.class.php
templates/download_page.php

This makes the code easier to reuse and update. This relates to https://github.com/filesender/filesender/issues/1648

D3UI3 move days_to_expire into Transfers class

---

scripts/task/execute-av-program-on-files.php

A few other little cosmetic updates too

avprograms wrap that in a try/catch to avoid file not found terminal

---

templates/guests_page.php

This relates to https://github.com/filesender/filesender/issues/1641

Using fromUserAvailable here allows the database to do the filtering

---

templates/invitation_detail_page.php

no need to search for many guests as we have the potential id, primary key, right there in a validated parameter.
This relates to https://github.com/filesender/filesender/issues/1635

d3ui3 Simplify guest lookup by id

---

www/js/transfers_table.js

The blocks marked for deletion in https://github.com/filesender/filesender/issues/1631 are removed.

d3ui3 remove the remover

---

templates/menu.php

We can always remove it again if we want.
This relates to https://github.com/filesender/filesender/issues/1574

d3ui3 bring back top menu logoff button

---

templates/guests_table.php

This relates to https://github.com/filesender/filesender/issues/1636

d3ui3 move some titles to using the translation strings

---

templates/transfer_detail_page.php
www/js/transfer_detail_page.js
www/js/ui.js

Given that this feature was requested and is actively used by one or more NRENs and seems generally useful for some users to be able to perform I have brought the functionality back.
This relates to https://github.com/filesender/filesender/issues/1577

d3ui3 bring back ability to extend expire time of transfer.

---

templates/guests_table.php

There is a Guest::fromUserAvailable method to allow the database to filter guests. If the guest table page does not impose a policy on the guests passed to it then the surrounding page can use or extend the database filtering/query code to find what it is wishing to display.
This relates to https://github.com/filesender/filesender/issues/1640

d3ui3 Guest table filtering is in database Guest::fromUserAvailable

---

classes/data/Transfer.class.php

cron: handle the case where files are deleted already but upload duration is sought

Found during cron investigation. More robust.

---

.github/workflows/sq.yml

Add the stuff from https://github.com/filesender/filesender/pull/1728 to run against development3.

add SonarQube-CI against development3

---

unittests/tests/auditlog/AuditlogTest.php
unittests/tests/clientlog/ClientlogTest.php
unittests/tests/common/CommonDatabaseTestCase.php
unittests/tests/dataset/DatasetTest.php
unittests/tests/dbs/DBsTest.php
unittests/tests/file/FileTest.php
unittests/tests/mail/MailTest.php
unittests/tests/report/ReportTest.php
unittests/tests/transfer/TransferTest.php
unittests/tests/utilities/UtilitiesTest.php

This relates to https://github.com/filesender/filesender/issues/1717

php 8.x move get_class() to get_class($this) in member functions.

---

www/download.php

Fixes: https://github.com/filesender/filesender/issues/1733
Please double check!

seems this should be REQUEST not a GET

---

www/js/download_page.js

"Refactor this function to not always return the same value" It seems from the code example that doing an early return and then having the "else" case just at normal scope is not desired.

d3sq code smell single return for function

---

classes/exceptions/TransferExceptions.class.php

It seems that $wanted became $size and some of the code got left behind.

d3sq: Review the data-flow - use of uninitialized value.

---

templates/download_page.php
www/css/new-ui/pages/_download.css

This relates to https://github.com/filesender/filesender/issues/1766
This is a test to see what SQ makes of the update.

d3sq: this is an attempt at Add "<th>" headers to this "<table>"

---

templates/menu.php

This addresses https://github.com/filesender/filesender/issues/1777

Support for newer 2.1 versions of SimpleSAMLphp

---

composer.json
composer.lock
unittests/config_tests_filesender.xml
unittests/tests/auditlog/AuditlogTest.php
unittests/tests/clientlog/ClientlogTest.php
unittests/tests/cron/CronTest.php
unittests/tests/dataset/DatasetTest.php
unittests/tests/dbobject/DBObjectTest.php
unittests/tests/dbs/DBsTest.php
unittests/tests/file/FileTest.php
unittests/tests/mail/MailTest.php
unittests/tests/report/ReportTest.php
unittests/tests/transfer/TransferTest.php
unittests/tests/utilities/UtilitiesTest.php

The main thing here is to update phpunit / selenium to newer versions. This will likely introduce the need for some updates and fixes but moving away from the old version is overdue.

update some of the vendor deps to more modern ones

---

language/en_AU/lang.php
www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1774

guests: Warn the user if they do not provide an email address

---

docs/v2.0/admin/reference/index.md

This brings in some docs requested in https://github.com/filesender/filesender/issues/1781.

docs: saml attributes

---

docs/v2.0/rest/index.md

This relates to https://github.com/filesender/filesender/issues/1772

docs: update for guest creation (POST /guest)

---

www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1802

update to get the auth attribute from the document

---

classes/storage/StorageFilesystem.class.php
classes/utils/Config.class.php
docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php
scripts/task/cron.php

Clean up old empty directories from daily buckets.
This relates to https://github.com/filesender/filesender/issues/1807

daily buckets: cron job to delete old empty directories

---

classes/utils/Lang.class.php

This relates to https://github.com/filesender/filesender/issues/1818

i18n: if a translation is not found log the error and try to continue

---

language/en_AU/lang.php

This relates to https://github.com/filesender/filesender/issues/1818

i18n: add email hint into the tr system

---

classes/exceptions/Exceptions.class.php
classes/utils/Utilities.class.php
docs/v2.0/admin/configuration/index.md

Allow a list of exceptions to be specified that an administrator does not wish to capture detailed logging for.
This relates to https://github.com/filesender/filesender/issues/1840

Allow a specific array of exceptions to not be logged.

---

classes/data/ShredFile.class.php

This relates to https://github.com/filesender/filesender/issues/1838 and https://github.com/filesender/filesender/issues/1838#issuecomment-2019898778

d3 strlen with potential null becomes more verbose

---

templates/transfer_detail_page.php
www/js/transfer_detail_page.js

Allow the download link on the transfer_detail page to be clicked if this feature is enabled in config.php

d3ui3: respect make_download_links_clickable if enabled

---

templates/upload_page.php

Looks and reads better without the dash

remove redundant dashes as the UX puts the text in its own bubble

---

classes/data/File.class.php
classes/data/FileCollection.class.php

This should address the issue in https://github.com/filesender/filesender/issues/1860

handle deleting a file in a collection

---

classes/utils/Config.class.php
docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php

This relates to https://github.com/filesender/filesender/issues/1878

d3: Ensure that auditlog_lifetime is long enough to avoid strange surprises

---

www/js/graph/aggregate-statistics-data-for-chart.php

This was discovered when testing for https://github.com/filesender/filesender/issues/1801

aggregate stats: set div to 1 by default

---

www/js/transfer_detail_page.js

This relates to https://github.com/filesender/filesender/issues/1884

d3ui3 make the auditlog button work for files again

---

classes/data/AuditLog.class.php
classes/utils/Utilities.class.php

Somehow a user is getting null for IP when downloading files.
Hopefully this fixes it.

getClientIP() tweaks

---

docs/v2.0/admin/configuration/index.md
includes/ConfigDefaults.php
templates/upload_page.php
www/css/new-ui/pages/_upload.css
www/css/new-ui/pages/pages.css
www/filesender-config.js.php
www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1867

d3ui3: bring back date picker for file upload as option

---

www/js/upload_page.js

This relates to https://github.com/filesender/filesender/issues/1882

d3ui3: scroll upload page to top as you progress

---

scripts/client/filesender.py

This issue was originally reported in https://github.com/filesender/filesender/pull/1875
This is an update to https://github.com/filesender/filesender/pull/1875 which follows the discussion there.

improve argument checking for filesender.py

---

scripts/task/emailfeedback.php

This is an update for verp passing for the issue raised in https://github.com/filesender/filesender/pull/1776.

update for verp

---

docs/v2.0/admin/configuration/index.md
templates/new_invitation_page.php
www/css/new-ui/pages/_new-invitation.css
www/filesender-config.js.php
www/js/new_invitation_page.js

This relates to https://github.com/filesender/filesender/issues/1867.

d3ui3: option to allow new invitation expire time to be set by date picker

---

templates/user_page.php

Referring to https://github.com/filesender/filesender/pull/1783/commits/0bf3d1ab657828a87295ed7922c0c8056a748b30#diff-1cbe5813828ff8dbaba5d417dbb28d6ee62f0657e63f41303d4c3a596cc09efa
make SimpleSAMLphp 2.x logout support for filesender3
I don't speak PHP so review carefully

SimpleSAMLphp2xSupport

---

www/js/guests_table.js

This relates to https://github.com/filesender/filesender/issues/1925

ui3: make expire action icons match

---

templates/transfers_table.php

this relates to https://github.com/filesender/filesender/issues/1924

ui3: make the transfers table icons css match others

---

docs/v2.0/install/index.md

Add missing package php-intl to docs

---

templates/guests_table.php
templates/invitation_detail_page.php
www/js/guests_table.js

- add "i" icon to guests table
- align icon types with transfer page
- move delete to the start like transfer page

ui3: fix guests icons

---

templates/service_aup_page.php

update service_aup_page to follow new FS3 format

Ui3 service aup update

---

docs/v3.0/install/index.md

A modified cherry pick of
https://github.com/filesender/filesender/pull/1934/commits/c68d497bb7ec5e2bf98bbaeb88f2c4a48c68e1ba to be against the docs/v3.0 tree

Update docs v3.0 with pr 1934

---

docs/v2.0/install/index.md

Not a true cherry pick but a patch to a fork to be PR'ed back to mainstream

A cherry pick of pr 1934 back to d

---

www/download.php

Fix download range offset math, most likely was a typo

Fix range offset calculation

---

docs/_includes/menu.html
docs/v3.0/user/download/index.md

do loopy to do docs updates now.

d3: add some user docs, downloading

---

docs/v3.0/user/download/index.md

I have focused on the 3.x user interface where the web browser interface is mentioned.

docs: more user docs on downloading

---

classes/data/StatLog.class.php

Update to allow things to work against modern (9.4+) versions of postgresql.
This should address https://github.com/filesender/filesender/issues/2010.

cron db update for postgresql for statlogs

---

templates/transfers_table.php

This relates to https://github.com/filesender/filesender/issues/2012

ui3: hide some action buttons for expired transfer

---

www/js/upload_page.js

This is an update of https://github.com/filesender/filesender/pull/2023 for UI3
This was raised for UI3 at https://github.com/filesender/filesender/issues/2020.

ui3 duplicate file handling improvement

---

.github/dependabot.yml

Dependabot is an automated updates management tool integrated into GitHub.
More information on Dependabot can be found here:
https://docs.github.com/en/code-security/dependabot
This PR enables dependabot to do automated scanning to see if composer packages have security vulnerabilities, and opens a PR for updating them as needed.
Note that dependabot does not merge actual PR's into code. A human needs to approve the PR.

Introduce dependabot security scans for composer

---

templates/user_page.php

Minor typo causing missing translations

Fix typo in translate string

---

scripts/client/filesender.py

Hi Team, 
Just two small changes here to make the script more useful for some of our users. 
- Added the option to explicitly set transfer expiry days.
- Added additional logic to not retry when authentication fails.
The core logic for transfer timeout has been here for a while but the users never had an option to manually set it themselves. 
Setting the value to high will generate the relevant log message regardless of verbosity settings for the user. 
Please let me know if you have any questions.

Filesender.py enhancements

---

docs/v3.0/install/index.md

Copy the information about composer --no-dev over to the 3.x docs.

Update 3.x install docs

---

classes/auth/Auth.class.php

This relates to https://github.com/filesender/filesender/issues/2089

Check if additional_attributes needs to be saved

---

docs/v2.0/admin/configuration/index.md
docs/v3.0/admin/configuration/index.md

This is very close to the disclosed one used by the web services.
Perhaps these could be merged at some stage.
This relates to https://github.com/filesender/filesender/issues/2102

Docs on disclose parameter

---

classes/data/Guest.class.php
language/en_AU/lang.php
templates/statistics_page.php

I mentioned this on the PR
https://github.com/filesender/filesender/pull/2099 I thought it might be simpler to add these updates after the merge.
I likely have more familiarity with the database schema and view setup code that most people will want to have :)

Move Guest count to using views and joining into auth table.

---

classes/data/Recipient.class.php
templates/statistics_page.php

This is an update to
https://github.com/filesender/filesender/pull/2099 to use a view here

Move getRecipients/getRecipientCount to using a view

---

classes/data/Transfer.class.php

also move to the dbobject api to keep it simple.

Got through users and auth to get results here

---

templates/transfer_detail_page.php
www/js/transfer_detail_page.js

fixes https://github.com/filesender/filesender/issues/2160

u3d3 allow downloading encrypted files from tr details page

---

templates/download_page.php
templates/upload_page.php

We've conducted some end-user tests on rc7. This PR reflects the rather simple UI improvements they suggested.
I'll be opening some issues on a few more improvements suggested by actual end-users.

Small UI tweaks after user testing

---

templates/guests_table.php

This relates to https://github.com/filesender/filesender/issues/2183

remove this confusing exclaim point

---

classes/rest/endpoints/RestEndpointUser.class.php
docs/v3.0/admin/configuration/index.md
includes/ConfigDefaults.php
templates/user_page.php

Add option cli_client_from_github + allow config to also use local python script

UI3: Add option cli_client_from_github

---

templates/user_page.php

UI3: user_page: make cli tool download links into buttons

---

templates/user_page.php

- space things out nicer
- make buttons like other buttons

UI: improve user_page for new PGP items

---

docs/v2.0/faq/index.md
docs/v3.0/faq/index.md

I had a lot of trouble get the current version of SimpleSAMLphp working with a local hosted SP. So I updated the documentation for that, so that others will have faster a working solution.

Update the docu for SimpleSAMLphp example-sp

---

docs/v2.0/faq/index.md
docs/v3.0/faq/index.md

Not really worth putting as a review comment. Easiest to just update.
A tiny tiny update to https://github.com/filesender/filesender/pull/2205

Very minor update modul -> module

---

templates/exception.php

This relates to https://github.com/filesender/filesender/issues/2203

D3UI3 unless this is in a main it does not show.

---

www/css/new-ui/components/_table.css

relates to https://github.com/filesender/filesender/issues/2204
a thing.

d3ui3 spacing issue

---

www/css/new-ui/_general.css
www/js/theme.js

Fixes and improvements to the v3.0 theme, including correcting the authentication theme color and saving the user's selected theme when it's changed in the settings screen.

Fix: theme v3.0

---

docs/v3.0/install/index.md

Minor fixes to v3.0/install document. Fixed some URLs pointing to SimpleSAMLphp documentation, whitespaces removed, some styling changed.

[Docs] Update urls, fix whitespace, some styling

---

classes/auth/AuthSP.class.php
classes/auth/AuthSPSaml.class.php
classes/autoload.php
classes/data/Authentication.class.php
classes/data/Guest.class.php
classes/data/IdP.class.php
classes/data/Recipient.class.php
classes/data/Transfer.class.php
classes/data/User.class.php
docs/v3.0/admin/configuration/index.md
includes/ConfigDefaults.php
scripts/task/README.md
scripts/task/cron-update-idp-metadata.php
scripts/task/import-idp-metadata.php
scripts/upgrade/database.php
templates/statistics_page.php
www/lib/tables/statistics_page.php

This should help to dice up data for stats and work out which IdP the transfers and users are coming from.
This is a rough first draft. It needs a combing over and other testing before merge but I am sharing it early as others are interested in it ;)

Ability to store IdP metadata in a new table and link to transfer

---

classes/data/User.class.php

This was reported here https://github.com/filesender/filesender/issues/2254

do not try for any php key if the feature is off

---

classes/data/Authentication.class.php
classes/data/Transfer.class.php
classes/data/User.class.php
classes/storage/StorageFilesystem.class.php

I'm not 100% sure if this will break anything

attempt to remove saml_user_identification_idp and use idpid instead

---

classes/data/DBObject.class.php
classes/data/Transfer.class.php
classes/exceptions/DBObjectExceptions.class.php

Added a new dbobject method to help to do it

Picking a column from a view seems fairly common

---

classes/data/Authentication.class.php
classes/data/DBObject.class.php
classes/data/Guest.class.php
classes/data/PublicKey.class.php
classes/data/Recipient.class.php
classes/data/ShredFile.class.php
classes/data/Transfer.class.php
classes/data/User.class.php

This should make forward porting updates from dev to dev3 easier too

Back port db changes that are only in dev3 into dev

---

www/js/admin_config.js
www/js/admin_statistics.js
www/js/admin_testing.js
www/js/admin_transfers.js
www/js/admin_users.js
www/js/asmcrypto/asmcryptoshim.js
www/js/asmcrypto/asmcryptoshim.module.js
www/js/client.js
www/js/crypter/archive_sink.js
www/js/crypter/filesystemwritablefilestream_sink.js
www/js/download_page.js
www/js/dragdrop-dirtree.js
www/js/guests_page.js
www/js/guests_table.js
www/js/lang.js
www/js/logger.js
www/js/notification.js
www/js/pbkdf2dialog.js
www/js/service_aup_page.js
www/js/transfer.js
www/js/transfers_table.js
www/js/translate_email_page.js
www/js/ui.js
www/js/upload_page.js
www/js/user_page.js
www/js/zip64handler.js

Do the js files as well as php from https://github.com/filesender/filesender/pull/2269

change SURFnet to SURF js

---

docs/v2.0/install/index.md
docs/v3.0/install/index.md
scripts/task/cron.php

This was raised here https://github.com/filesender/filesender/issues/2274 and improving the docs and cron.php script should help everybody.

Add some docs around the config for SSP+Cron

---

classes/data/Guest.class.php
classes/data/Transfer.class.php
templates/statistics_page.php
www/js/graph/statistics_data_per_day_graph.php
www/js/graph/statistics_encryption_split_graph.php
www/js/graph/statistics_transfers_speeds_graph.php
www/js/graph/statistics_transfers_vouchers_graph.php

you may have to manually drop transfersfilesidpview from db

simplify table views and sqls + drop transfersfilesidpview

---

www/css/default.css
www/css/default.scss
www/js/ui.js

This relates to https://github.com/filesender/filesender/issues/2219

Update for left padding on dialogs with a radio choice.

---

templates/transfer_detail_page.php

fix: initialize isEncrypted with transfer value

---

docs/v2.0/install/index.md
docs/v3.0/install/index.md

This was mentioned here https://github.com/filesender/filesender/issues/2284#issuecomment-2965506354
Thanks alexis-millionbalard !

does: update nginx paths for filesender and ssp

---

templates/upload_page.php

This seems to help a bit, making it it's own column.
This relates to https://github.com/filesender/filesender/issues/2314

D3UI3: move the "or" in the encryption password out

---

www/js/service_aup_page.js

This was reported here https://github.com/filesender/filesender/issues/2315

d3ui3: reload the aup page only after the popup has faded

---

classes/utils/Config.class.php
classes/utils/Template.class.php
templates/statistics_page.php
www/js/graph/statistics_encryption_split_graph.php

IDP name is blank until our 6 hour cron happens, which results is blanks in the stats drop down box.
Also other little bugs.

Idp blank name fix

---

classes/data/File.class.php

There is normally some little rough bits to chip away.
A tiny update after https://github.com/filesender/filesender/pull/2345

Allow upload for non forwarding again

---

scripts/task/cron.php

Force the closing of transfers that do not exist and allow rest of the cron to continue.
We shouldn't need to rely on Forwarded Sever to always be healthy.
This should also help when "we" manually manipulate the db directly.
Before this change I get this when running cron:
```
php scripts/task/cron.php --verbose
cron.php starting up... --force: --testing-mode:
cron.php running as user: uid=0(root) gid=0(root)
cron.php closing expired transfers...
Transfer#1049 expired, closing it...
PHP Fatal error:  Uncaught Exception: Http error 500 : {"message":"transfer_not_found","uid":"68a65d969c08c","details":null} in /filesender/scripts/client/FilesenderRestClient.class.php:210
Stack trace:
#0 /filesender/scripts/client/FilesenderRestClient.class.php(320): FilesenderRestClient->call()
#1 …
```

cron: force the closing of transfers that do not exist

---

classes/utils/Args.class.php
scripts/task/S3bucketmaintenance.php
scripts/task/cron.php

This is a manual pick of https://github.com/filesender/filesender/pull/2367

Doing it twice for the 2.x branch.

---

templates/invitation_detail_page.php

This relates to https://github.com/filesender/filesender/issues/1608

ui3d3: this moves the control buttons over

---

classes/constants/GUIPages.class.php
classes/utils/GUI.class.php
docs/v3.0/admin/configuration/index.md
includes/ConfigDefaults.php
language/en_AU/lang.php
templates/menu.php
templates/pagemenuitem.php
templates/transfers_guest_page.php
templates/transfers_table.php

This is to address
https://github.com/filesender/filesender/issues/2046
note that we do not cater for guests who have already expired here. This is a good first step to allow a guest to check if their upload is in the system which seems like a very useful feature for a guest who is submitting files and wishes to double check that they were sent correctly (from FileSender's perspective).

ui3 option to allow guest to see their uploads

---

classes/utils/Template.class.php

If you have millions of files this can be a good performance boost.

perf: it can be expensive to process nulls
