templates/download_page.php, templates/transfers_table.php, templates/upload_page.php, www/js/crypter/crypto_app.js, www/js/crypter/crypto_test.js, www/js/filesender.js, www/js/transfer.js, www/js/transfers_table.js, www/js/ui.js
FileSender currently uses User Agent detection to find out whether TeraSender can be used in combination with crypto. This is not ideal, since webbrowsers get updated all the time and capabilities are improved each release.
This pull request removes User Agent detection, and instead detects capabilities by probing browser features. In addition, it fixes a bug that earlier was (incorrectly) attributed to webbrowsers not supporting crypto in WebWorkers, namely that WebWorkers do not have access to the DOM, making jQuery unavailable. Therefore, in this pull request, jQuery is removed from WebWorkers code, and moved to more appropriate locations.
If this pull request is accepted, #5 should not be relevant anymore.
=> Update compatibility checking for crypto and WebWorkers

classes/autoload.php, config/config-sample-meijer.php, scripts/install/install.php, scripts/upgrade/database.php, scripts/upgrade/upgrade.php, travis/config.travis.mysql.php, travis/config.travis.pgsql.php, unittests/selenium_tests/SeleniumTest.php, unittests/tests/common/CommonPHPUnitConfigs.php
During the merging of the changes from CodeBridge, I seem to have missed some changes related to unittesting on Travis. More specific, during unittesting, `FILESENDER_BASE` was defined twice and Selenium was strict about whitespacing while patching config files for different tests. Additionally, one config option was misspelled in meijer's config file, which was used by CodeBridge.
Instead of backporting the stopgaps, I've opted to solve the problems at their roots. Thus, `FILESENDER_BASE` is now only defined in init. The define statement in the autoloader is replaced with a fatal error because it shouldn't be called. Selenium will now be more lenient with whitespace, and the misspelled config option has now been renamed to the correct one.
=> Fix regressions after merge CodeBrige

classes/data/File.class.php
While upgrading our staging server, we found out that the migrations code doesn't handle the case where it has to add a NOT NULL column to a table which already contains data. This is no problem for MySQL because it will just fill `0` or `""` instead, but PostgreSQL will fail.
This pull request **does not** resolve the issue, but marks the new `encrypted_size` field to be nullable. I think that a nullable `encrypted_size` makes more sense in order to be able to mark files as not encrypted.
=> Allow encrypted_size to be null

classes/auth/Auth.class.php, classes/auth/AuthSPSaml.class.php, classes/rest/RestServer.class.php, classes/rest/endpoints/RestEndpointUser.class.php, classes/utils/LegacyUploadProgress.class.php, classes/utils/Utilities.class.php, includes/init/init_web.php
FileSender uses a third party authentication handler (often SimpleSamlPhp). It has its own session handler. When combining it with another session system, such as by calling `session_start()`, the sessions conflict.
In FileSender, `session_start()` is called, seeminly for legacy reasons. This has no direct negative effects, because it doesn't actually use this session. However, it does trigger a log message in SimpleSamlPhp. [SimpleSamlPhp 1.14.9 has a bug where this log message causes the application to crash](https://github.com/simplesamlphp/simplesamlphp/issues/517#issuecomment-261258092).
This pull request will remove `session_start()` everywhere it was used. I have tested this on my test instance for multiple weeks, it has so far not caused issues.
=> Prevent calling session_start() directly

.travis.yml, classes/data/DBObject.class.php, classes/storage/StorageFilesystem.class.php, classes/utils/GUI.class.php, classes/utils/Mail.class.php, composer.json, composer.lock, travis/config.travis.mysql.php, travis/config.travis.pgsql.php, unittests/selenium_tests/SeleniumTest.php, unittests/selenium_tests/tests/ConfigurationOptionsTest.php, unittests/selenium_tests/tests/EncryptionTest.php, unittests/selenium_tests/tests/MaxFilesTest.php, unittests/selenium_tests/tests/TransferExpiredTest.php, unittests/tests/common/CommonPHPUnitConfigs.php, unittests/tests/dbs/DBsTest.php
The [] notation is prettier, but Red Hat 6 still uses PHP 5.3 which doesn't support it.
Since FileSender supports all alive versions of Debian and Red Hat, we must limit ourselves to syntaxes supported by old PHP versions.
=> Make FileSender compatible with PHP 5.3, for backwards compatibility

classes/utils/Logger.class.php
The logger has a failsafe to be able to log when no logging is configured yet. However, this fails on [classes/utils/Logger.class.php#L306](https://github.com/filesender/filesender/blob/27b7026/classes/utils/Logger.class.php#L306), where it required a `method` to be defined. The method being missing causes a fatal error, which causes PHPUnit to fail while trying to show an error message about missing configuration.
=> Define method in failsafe logging facility

classes/rest/endpoints/RestEndpointTransfer.class.php, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/transfer.js
Using a whitelist is better than trying to work out all the exploits that might come along. For example, nasties like the following as the file extension.
```
\"install_keystroke_monitor();" 
```
Most extensions are just normal characters
=> improve file extension testing for bad cases

classes/data/Transfer.class.php, classes/exceptions/TransferExceptions.class.php, classes/utils/Utilities.class.php, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/transfers_table.php
File names have no need to include things like the following
```
\"alert(1);
```
Most folks do the right thing, but they are not the ones we are concerned with here. Instead of trying to work out what to do with a blacklist of "you can't do a \" here" it is more secure to declare what characters are valid for a file name and reject the rest. Output is also sanitized just in case something got through before that is nasty.
=> FIS-007 fix for XSS injection in file name on transfer page

docs/v2.0/install/index.md
We should be using the latest SimpleSAML to avoid security issues that have been fixed in that library.
=> fis-009 update documentation that points to old SimpleSAML version

classes/utils/Utilities.class.php, includes/ConfigDefaults.php
This lets some common chars back into filenames 
```
php > echo preg_match( '/^[\p{L}\p{N}_]*$/u', 'ÆØÅÜÉéafdsfdDFSDFDS543534' ) == 1 ? 'ok' : 'bad';
ok
```
=> loosen the security to allow more freedom again

classes/exceptions/GuestExceptions.class.php, classes/exceptions/MailExceptions.php, classes/exceptions/TransferExceptions.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/utils/Utilities.class.php, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/guests_page.php, templates/upload_page.php, www/css/default.css, www/filesender-config.js.php, www/js/guests_page.js, www/js/ui.js, www/js/upload_page.js
I have left the default setting to not filter links as I think using links is a _huge_ advantage to researchers. 
I guess since the default is now to get a link to the transfer then the 'message' in file sender will get less direct use. Offering the link to the transfer puts the security issue on the messaging systems that people are using to communicate these links to each other. But it doesn't mean that the 'message' option in FileSender should make users not want to use it by being a bunch more restrictive than email.
=> fis013 option to filter links in messages

classes/utils/Zipper.class.php
most extractors catch these out of tree write attempts, but we should do some filtering to help stop them from happening.
=> fis012 disallow out of tree file names

classes/rest/endpoints/RestEndpointFile.class.php
It PUT was already protected from this, but POST needed the additional check on session status.
A command like the following used to allow override if sizes matched.
```
curl -X POST -k -v 'https://127.0.0.1/filesender/rest.php/file/149/whole?key=e9001...e2bc8' -F "file=@/tmp/new1"
...
{"id":149,"transfer_id":158,"uid":"e9001...e2bc8","name":"df2","size":30,"sha1":null}
```
Now it results in an error ```"message":"cannot_add_data_to_complete_transfer"```
=> FIS-005: Stop unauthorized file overwrite after transfer is complete.

classes/rest/endpoints/RestEndpointTransfer.class.php
Deleting files is so final and quick that there is not much gain to allowing folks to do it after their saml session has expired. This also mitigates hack attempts from folks who might have found out a file uid and sweep through trying to clean out things 6 months after the session was setup.
=> fis011: you need to be authenticated in order to delete files

classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php
After a PUT some metadata is returned. If the put does nothing much then a nasty user could use that call to obtain other information about a transfer using the 'key'.
=> FIS-004: Avoid leaking information when the user directly attacks the REST API.

language/en_AU/lang.php, language/fr_FR/lang.php, templates/download_page.php
The archive message is only shown if there is >1 file. Some css was hiding it anyway in those cases.
A message about encryption is shown when that option is effective.
And the right click + copy link message is now shown at the top of page to give the user a hint that it should work.
=> Make the disclaimer message more meaningful to the page

templates/guests_page.php
You have to supply the email address of the guest which is used to
send the link for guests. Having the option to get a link presented in
the UI is confusing as it doesn't change the outcome (emailing the
guest) regardless of if get a link is selected.
=> Disable the "Get a link" checkbox as it is misleading

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/upload_page.php
There are only a few options that a guest can actually change on my fairly stock config. It might make for a simpler one time upload of the guest has less uninteractive clutter to have to scan over for a simple first time upload.
=> Add an option to hide checkboxes in the guest upload page

classes/data/Transfer.class.php
The "My Transfers" page is sorted with the newest activity at the top. This will sort the guest transfers in the same way so the newest is at the top.
=> sort guest transfer table newest first

templates/upload_page.php
Showing the option might give the user the feeling that it will have an impact. Not showing it at all for guests is less confusing.
=> For guests, get a link option does nothing

classes/data/Guest.class.php, classes/data/Transfer.class.php, language/en_AU/guest_upload_complete_confirmation_to_guest.mail.php, language/fr_FR/guest_upload_complete_confirmation_to_guest.mail.php, templates/upload_page.php
When the guest performs an upload, a dialog box is presented offering the download link. If the user does not record this link right at the time then there is no way they can get it again later. Emailing the link to the user allows them access to it at a later time if they want to resend it to somebody.
=> send a confirmation email to guest after upload

templates/guests_page.php, templates/upload_page.php, www/js/upload_page.js
With a little love this works either way the checkbox is selected. It is important to get it right as the guest may well be blocked from changing the get_a_link option so it needs to work by default either way to be useful.
=> Make the UI work for link/nolink guest setups

classes/data/Transfer.class.php
If the guest is created with can only 'send to me' then do not send them an email after they upload. The email after upload contains a link to download which allows the guest to 'send to others', going against the wishes when the guest was created.
=> if they can only send to me then do not email them a link to send anywhere

classes/data/User.class.php
If the user is on a mysql type database and has character encodings that take 4 bytes per character then using varchar(255) will fail to create an index. The simple fix is to only allow email addresses up to 190 bytes long.
=> avoid hitting index size limit on mysql

.travis.yml
not a bad test, the CI worked fine before, so if anything breaks now it will be due to the distro and php 5.3 to php 5.6 update. 
So the main thing for this PR to evolve to do is getting the CI going again. Hopefully without resorting to forcing the use of an outdated distro in order to use 5.3 again. Keeping the CI modernish is likely better for all. A followup might be useful after a survey to see if everybody is using a later php version. Best to test in the CI using the same version that most folks want to use.
=> see how well php 5.6 works

docs/_includes/menu.html, docs/acknowledgements.md, docs/mailinglist.md, docs/socialmedia.md, docs/v2.0/release/index.md
Use of Assembla is being decommissioned. These are a few pages from the old wiki which seems useful to have on the new github based site. There may be more to import, and the releases instructions need some more freshing up love for sure.
=> Import some of the docs from assembla

scripts/client/FilesenderRestClient.class.php
This was suggested in https://github.com/filesender/filesender/issues/27 to improve the usability of the REST Client class to developers. If somebody accidentally passes null instead of array() then things are converted over for the developer.
=> REST Client: allow null as empty array

classes/auth/AuthSPFake.class.php, classes/auth/AuthSPSaml.class.php, classes/auth/AuthSPShibboleth.class.php, classes/exceptions/AuthSPExceptions.class.php, classes/exceptions/Exceptions.class.php, language/en_AU/lang.php
When a key is mistyped or the sysadmin is expecting different keys in the auth session than are there then things can be hard to debug. For example, using a local user/password in simplesaml one might select the wrong uid attribute but have no idea what the right choice is. With this serverlogging then the sysadmin gets some more clues that can be found with the finding out details hex string from the browser.
=> sysadmin: Help the sysadmin with missing SAML attributes

classes/rest/endpoints/RestEndpointTransfer.class.php
This was taken out with https://github.com/filesender/filesender/pull/34/files
It turns out that options is an array() from the Rest Client and there is no exists() method on array. Until things are normalized to object or array throughout this check has to come back so that the rest clients can upload again.
=> REST Client: fix for array and object when checking properties

classes/auth/AuthSPSaml.class.php, classes/data/Recipient.class.php, classes/data/TranslatableEmail.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/download_page.php
This allows the separator for CGI parameters to be set to something other than "&". Note that you will have to ensure your php.ini allows your setting too. By setting the separator to ";" you can avoid conflicts with some email clients escaping the "&" too much for example. This issue was reported in https://github.com/filesender/filesender/issues/98.
This PR targets some specific locations and I have checked over some of the emails and links on the site to see the ";" appear if configured to do so.
=> Allow CGI parameter separator to be configured

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/report_html.php, templates/report_pdf.php, templates/report_plain.php
Some sites might not like to report the IP address in their reports and with this patch that can be turned off without having to alter the reports templates to do it.
=> Reports: allow IP address to be hidden

classes/exceptions/Exceptions.class.php, classes/exceptions/RestExceptions.class.php, classes/rest/endpoints/RestEndpointFile.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md
Option to turn on additional logging for some exception types. This can be turned on/off with an optional config option to avoid the possibility of breaking a deployed system by editing the code directly.
This is an update to a previous PR but I'm allowing things to be turned on/off easily (default off) so that things can be turned on in the wild by admins who want to contribute feedback.
=> exceptions: allow some extra optional logging

classes/exceptions/Exceptions.class.php, classes/exceptions/StorageFilesystemExceptions.class.php, classes/storage/StorageFilesystem.class.php, classes/storage/StorageFilesystemChunked.class.php
It is fine syscall wise for fwrite() to return less than the provided number of bytes. This lesser number was being sent back to the client but never checked. So I could have done
```
fwrite($fh, $data, $chunk_size-1);
```
and return 1 byte less than the user gave us. The client did doesn't catch these short writes and say anything. So if the server didn't write all the data the client (and user) doesn't get any error. 
No with the brute force method of throwing on short writes the client will see if each of their bytes is not saved. From there the client code might like to retry the request. Though if the server has failed to write the bytes given then it might not help to rerun from the client side. It might be more useful to have a new utilities::fwriteWithTries() that can maybe retry …
=> upload: if fwrite() returns short, tell user 

classes/autoload.php, classes/constants/DBStorageType.class.php, classes/data/DBObject.class.php, classes/data/File.class.php, classes/storage/Storage.class.php, classes/storage/StorageFilesystemChunked.class.php
The addition of the new chunked storage type creates some issues when folks might want to migrate to using it while still serving old files that have already been transferred.
This PR will require a database upgrade to work;
```
php /opt/filesender/scripts/upgrade/database.php
```
Note that I have set the default storage for existing transfers to 'Filesystem'. If you have been using the chunked storage type then you will need to update the database with the below command to override the default setting, note use files as the table in postgresql and Files in MySQL.
```
update files set storage_type = 2 ;
```
Since each file saves the int value for the storage_type that was active when it was created you can more easily change the storage_type in the future while still serving existing …
=> Storage: bind storage_type to each file that is saved

docs/known-installs.md
Copied known installs over from the old Assembla wiki page, removed those which were offline. All remaining URLs checked.
=> Add known installs list as markdown file to docs

classes/data/AuditLog.class.php, classes/data/DBObject.class.php, classes/data/Transfer.class.php, language/en_AU/lang.php, templates/admin_transfers_section.php, templates/transfers_page.php, templates/transfers_table.php, www/css/default.css
DBObject::all() had some support for offset and limit (count) data though it was evaluated client side. Moving that to the db side allows for efficient evaluation with the minor cost that the client doesn't get to know the total number of matches any more.
The admin transfers page is the only client of the old code which has been updated to work with the db side queries. The number of pages is currently only a guess, though the speed of loading should more than make up for that temporary inconvenience.
I used the old fetch one more trick to allow the my transfers page to know if there are more records (a next page) or not. This is why transfers_page selects limit+1. The +1 is not shown to the user and only used to know if there is a next tuple or not.
With the seondary indexes already in …
=> My Transfers page is now paginated

classes/exceptions/ConfigExceptions.class.php, classes/utils/Config.class.php, classes/utils/Logger.class.php
This relates to the filed issue https://github.com/filesender/filesender/issues/107
It is informative to see how this happens. Default values are loaded and then the user's config.php is loaded and merged. So if the user has the following in the config.php
```
$config['log_facilities'] = 
array(
'type' => 'file',
'path' => '/var/ram/logs/',
'rotate' => 'hourly'
); 
```
The loaded config becomes the invalid mess;
```
(
[0] => Array
(
[type] => file
[path] => /opt/filesender/log/
[rotate] => hourly
)
[type] => file
[path] => /var/ram/logs/
[rotate] => hourly
)
```
There is an attempt to work with these keys, casting them to an array before inspecting, which gets into trouble when the type=>file entry is encountered as it is itself cast to an array but doesn't include the path element into …
=> give a little help to the admin if they set log_facilities in a way we dont expect

classes/data/StatLog.class.php
The created index is being selected for use here, but the event type then target index should also be generally useful to other queries as well.
=> db: some secondary indexes to speed up that upload page graph

www/js/transfer.js
As part of the effort to remedy FIS-007 (PR#64), a filename check was introduced.
However, another filename check was already in place.  The new filename check is better,
because it uses the configuration setting to decide which filename is good and which isn't.
This commit removes the old filename check.
=> Remove redundant filename check

classes/rest/endpoints/RestEndpointFile.class.php
When a user uploads a large file and the security token expires during upload,
FileSender has code in place to allow the upload to continue.
However, when the whole file has been uploaded, the browser must signal upload complete.
Now, FileSender suddenly does check the session and aborts the upload, thus defeating the purpose of allowing the upload to continue.
This commit will allow for the signaling of upload complete without checking the security token, in addition to the already existing code to allow for uploading chunks without checking the security token.  Thus allowing a user to complete a upload when the security token expires.
=> Do not require session to signal upload complete

classes/utils/Zipper.class.php
offset shouldn't need to be equal to size. A 2 byte file has offsets 0 and 1, reading at offset=2 is invalid.
This silently worked before because StorageFilesystem::readChunk() ignores the return value of seek() and returns null when no data is read.
=> zip: fencepost error

classes/data/AuditLog.class.php, classes/data/StatLog.class.php, classes/utils/DatabaseMysql.class.php
This moves the id column of these two tables to be larger. It is a shame that the default meduim sized int in mysql is meduim which is 3 bytes (16million) instead of a 4 byte int which would be much harder to bump into the limits for.
It is overkill making these bigints which are 8 byte numbers on both db backends. If we store 9 million, million, million records in any auditlog then we are doing well.
I noticed that MariaDB doesn't like it if you alter column for an existing primary key and state primary key in the alter clause. I have removed that in the code so that migration can be done simply using the update.db script. In the future we should really ensure that we are not making the column a primary key in the db upgrade (ie, only remove the primary key clause in the alter column if …
=> db: auditlog and statlog can be quite large

classes/data/Guest.class.php, classes/exceptions/BadExceptions.class.php, classes/utils/Config.class.php, classes/utils/Enum.class.php
As has been reported in issue 197, if you have a configuration for
guest_options that uses an invalid key then you will have only
discovered this when a guest voucher sent out is attempted.
This PR moves the detection of an invalid option to a top level event.
You will not see a filesender website if there is an invalid setting
but will get a log message telling you about this, what key is
offending, and what the possible keys are in case you have mistyped
something.
=> Config validation: fail very fast for bad configuration settings in guest

www/lib/terasender/terasender.js
The patch is mostly comment, better to be informative there than here.
The basic version is that there was a race between calling
file.complete and transaction.complete. Logging can show that for the
final two chunks nothing was explicitly stopping transaction.complete
from landing before the last chunk of the last file. A test was
already stopping transaction.complete from being called more than
once. There are multiple timeout delays involved in eventually calling
transaction.complete so the chances of that happening on a LAN were
less. Normally on a LAN the workers would themselves complete and call
file.complete before the timeouts ran and the already scheduled
transaction.complete would actually call the server.
This patch makes it explicit that transaction.complete is only
scheduled …
=> Race condition of file.complete and transaction.complete

www/js/transfer.js
This one is quite subtle. transfer.js/uploadChunk increments the
file_index if it was the last chunk and then goes on to call
putChunk() to actually send that last blob. Since there are no workers
it doesn't seem to make for a race. But there are timeout callbacks so
similar things can happen if you are not careful.
In the done callback passed to putChunk() the
transfer.reportComplete() is called which will complete the
transaction. Digging into transfer.reportComplete we see a guard for
status done which ensures it will only be able to fire once. Then
filesender.client.transferComplete is called after a 300ms delay.
To stimulate a race, add two files to the upload and make the last
file very small. This way in the call to 'done' for the first file,
lets call it firstfile, by the time the …
=> Race condition: uploading without terasender

dev/doc/filesender-2.0-config-directives-markdown.txt, includes/ConfigDefaults.php, templates/upload_page.php, www/css/default.css, www/filesender-config.js.php, www/js/transfer.js, www/js/upload_page.js, www/lib/terasender/terasender.js
A new mode is available which shows the duration that a chunk has been
active in the upload page. This way a user can see a chunk that is
taking a long time and also get more information that a transfer is
not stalled even though it is a huge file and the progress meter will
move very slowly.
It is early days for the feature. Hopefully the insights gained will
help work out the final kinks in the stall detection and also offer
the user the ability to report a stall that they think is invalid.
=> stall: new mode to show more info to user

classes/auth/AuthSPSaml.class.php, classes/utils/Logger.class.php
This offers some more information in the log if the saml files are not found where FileSender is expecting them to be or for some reason they are not readable (permissions, selinux).
=> saml: better reporting for things going wrong in setup

classes/auth/Auth.class.php, classes/auth/AuthSPSaml.class.php, classes/autoload.php, classes/utils/Logger.class.php, classes/utils/Utilities.class.php
It was easy for code that is executed during auth setup to call back into the auth setup which would cause an infinite loop. This brings in some protection against that happening.
=> auth: some protection from recursive loops during setup

classes/storage/StorageFilesystemExternal.class.php, classes/storage/StorageFilesystemExternalStream.class.php
The stream class is updated to avoid a name clash with the Chunked stream.
=> externalStorage: share the run() and streams update

dev/doc/filesender-2.0-config-directives-markdown.txt, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/upload_page.js
This only effects when you break an upload and then enter the Upload
page again. Normally a dialog "Restart failed transfer" appears
offering to setup the transfer again and "Restart" instead of start
the transfer.
This could be problematic if the user enters a different password for
the resume, having part of the upload encoded with one password and
part with another. It was also reported on
https://github.com/filesender/filesender/issues/80 that resumed
crypted uploads were having issues, so until that is tested to a
greater extent it is better to offer the abilitiy to not allow resume
for crypted transfers.
=> crypto and resume: option to not remember transfer if if crypto is on

templates/download_page.php, www/css/default.css, www/js/download_page.js
This is a partial solution to
https://github.com/filesender/filesender/issues/191 where dialogs and
messages are presented on the download page when encryption is not
detected. The next step is to work out which is the minimal version of
IE that is needed for things to happily work and ensure that
filesender.supports.crypto is set to false for the failing versions of
IE.
=> crypto and download: some checks and better handling when not available

classes/rest/endpoints/RestEndpointFile.class.php, dev/doc/filesender-2.0-config-directives-markdown.txt, includes/ConfigDefaults.php, www/css/default.css, www/filesender-config.js.php, www/js/transfer.js, www/js/upload_page.js, www/lib/terasender/terasender.js
The existing stall detection monitors whole chunks. This code
compliments the existing stall detection by monitoring how many bytes
have been transferred and how long it was since the last "subchunk" of
bytes has been transferred over.
By looking at the xhr progress messages like this we can much more
quickly detect when the single (non ts) or ts upload is starting to
struggle. For example, if you force a stall of say, 10 seconds, on the
server and set the following the worker displays will turn red after 5
seconds elapsed with no new bytes sent over.
$config['upload_considered_too_slow_if_no_progress_for_seconds'] = 5;
$config['upload_display_per_file_stats'] = true;
It is useful to know the low level health of each subchunk so that
network issues that might cause the server to timeout …
=> stall detection: monitoring bytes within chunk transfers

classes/auth/AuthSPSaml.class.php
This can cause downloads to fail to complete due to excess RAM usage in some cases.
=> getting saml version can cause problems in some cases

language/en_AU/accepttoc.html.php, templates/upload_page.php
There seemed to be some partial renaming going on there. This should make the T&C checkmark work again when you have
```
$config['aup_enabled'] = true;
$config['aup_default'] = false;       // AuP value is NOT already ticked
```
=> AUP: bring back the checkmark to bind users to the site terms and conditions

classes/exceptions/TransferExceptions.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, dev/doc/filesender_wiki/Documentation_v2-0-alpha/filesender-2.0-config-directives-markdown.md, includes/ConfigDefaults.php, language/en_AU/lang.php, www/filesender-config.js.php, www/js/transfer.js, www/js/upload_page.js
This is checked client and server side. One little twist on the client
side is that enabling and disabling encryption will have a toggle
effect on if files are valid.
The code sort of assumes that if the client side transaction.addFile()
doesn't work then it will not magically start to work. The max file
size stuff toggles so that you can enable encryption and see an error
for file too large, but if you then disable encryption again you
should see that the file is ok again.
=> Limits: ability to set maximum file size for encrypted files

dev/doc/filesender_wiki/Documentation_v2-0-alpha/filesender-2.0-config-directives-markdown.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/upload_page.php, www/css/default.css, www/filesender-config.js.php, www/js/upload_page.js
New encryption_min_password_length setting to set the minimum password
length for encryption. This also changes the generate password to make
sure that is the correct length as per system policy.
=> encryption: ability to set minimum password length

www/js/upload_page.js
Nothing major is inserted into the log() but this might be handy for tracking down why server side.
=> upload: some client side hint in the log as to why resume is silently dropped

classes/storage/StorageCloudAzure.class.php, scripts/cloud/azure/test-azure-simpleblob.php
It seems that deleting a container marks the blobs it has for deletion too, so the one call might work on the real azure server too.
=> cloud-azure: support delete, remove stale container_name references

classes/auth/AuthSPSaml.class.php, classes/storage/StorageFilesystem.class.php, classes/storage/StorageFilesystemPreserveName.class.php, www/js/upload_page.js
Created StorageFilesystemPreserveName which extends StorageFilesystem by overloading the buildPath and adding a buildFilename method, which in StorageFilesystem just returns ->uid. To have methods in StorageFilesystem call the outer implementation, switched most self::buildPath to static::buildFile, used static::buildFilename exclusively
Updated StorageFilesystemPreserveName so files uploaded will go into a subdirectory path called "owner/uid=name" to avoid name collision and satisfy archiveval systems usually wanting sets of files in a directory
=> Storage filesystem preserve name

classes/autoload.php, classes/data/ShredFile.class.php, classes/storage/StorageFilesystem.class.php, classes/storage/StorageFilesystemChunked.class.php, classes/utils/Filesystem.class.php, docs/v2.0/admin/configuration/index.md, docs/v2.0/shredding/index.md, includes/ConfigDefaults.php, scripts/commands/file_deletion_command_testing_fast, scripts/commands/file_deletion_command_testing_slow, scripts/commands/file_deletion_command_testing_very_slow, scripts/commands/file_deletion_command_with_shred, scripts/task/cron-handle-shred-files.php
Running shred(1) directly in the
storage_filesystem_file_deletion_command can make the Web interface
appear to be broken at times. This is due to the execution of shred
being done synchronously.
This new code creates a clearing house for shredding. When a file is
deleted through the Web interface it is moved and marked for shredding.
See the new docs shredding page at docs/v2.0/shredding/index.md
for details.
There are many design options for this. Having a database table allows
failures to be tracked which might not otherwise be noticed. The
original file names are scrubbed so the files to be shredded does not
expose the user who used to own the files.
=> Shredding: new clearing house to shred deleted files

language/de_DE/lang.php, language/es_ES/lang.php, language/fr_FR/lang.php, language/hr_HR/lang.php, language/hu_HU/lang.php, language/it_IT/lang.php, language/nl_NL/lang.php, language/no_NO/lang.php, language/sl_SI/lang.php, language/sr_RS/lang.php
These are just run through sort-lang-file-and-write.php and should contain the same data as before but in a key sorted manner.
Doing this first allows for easier comparison on the data from poeditor to the existing data in github.
=> i38n: sort all the remaining lang.php files

docs/v2.0/install/index.md
This is based on a message to filesender-dev by Ilya Vasilyev from RUNNet. I have split this into two sections in the documentation to match the current Apache install and configuration information.
I might flip things around a bit and coalesce the install and configuration of the Web server into a single section in the future.
=> docs: bring in the contributed nginx install info

language/en_AU/lang.php, www/lib/graph/uploadGraph.php
This is a fix for https://github.com/filesender/filesender/issues/285. The new terms are 
```
$lang['upload_page_graph_title_upload_speed_of_files_over'] = 'Global Average Upload Speed of Files over {size}';
$lang['upload_page_graph_mb_per_second'] = 'MB/sec';
$lang['upload_page_graph_encryption_in_transit_and_rest'] = 'Encryption in transit & rest';
$lang['upload_page_graph_encryption_in_transit'] = 'Encryption in transit';
```
which are exported to poeditor already.
=> i18n: graphs can be internationalized

www/js/transfer.js
Setting file.uploaded to the end of the chunk before the actual putChunk() was complete could cause a bad upload if there was a forced stall (turn wifi off during upload). This is a non terasender path mitigation.
If file.uploaded is set before the putChunk() is complete then that value is stored into local storage by transfer.reportProgress(), when it calls this.updateFileInRestartTracker(). This is fine as long as file.uploaded is actually the data that *is* uploaded and not what would be uploaded if the currently being processed chunk of data was completed.
So now I have moved setting file.uploaded to when the putChunk() is actually done.
=> baddata: mitigation for issue 293

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/lib/terasender/terasender.js, www/lib/terasender/terasender_worker.js
This allows up to a configurable amount of attempts reuploading a chunk before it is considered to have failed. The default is 20 retries, which is per chunk, so should cover most network issues.
There is also a new testing option to simulate a chunk failure on the third chunk up to allowed_retries-1 in order to test the recovery path. This is off by default and enabled through the config so that Travis can possibly enable the code to ensure recovery is working on a CI run.
This should mitigate https://github.com/filesender/filesender/issues/305 and currently will turn the failure of the 20th time a chunk upload is attempted into a user viewable failure message. Better than silent failure as the user does not expect more data to have been transferred than will be shown.
=> terasender: automatically restart uploading a chunk if the previous upload failed 

.travis.yml, travis/scripts/mysql-setup.sh, travis/scripts/postgresql-setup.sh
It is confusing having two calls to these. I moved the database.php calls up from the mysql/postgresql scripts because the database php is designed to run on any database backend. I think it makes sense to limit the database specific scripts to database specific tasks.
=> ci: move the database migration generic code calls up

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/crypter/crypto_app.js, www/js/upload_page.js
Update for https://github.com/filesender/filesender/issues/334
This retains the old password length setting. There is a min length even for generated passwords because the password box is editable. If the user trims the generated password they might make it too small. On the other hand, the user might like most of a generated password but want to edit it a little bit so leaving it editable can be handy for that use case.
This includes a new setting allowing the encoding to be set for the generated password. ascii85 will give more entropy per byte of text password than base64. With ascii85 encoding a 20 byte password will have 16 bytes of entropy in it. On the other hand a base64 encoded password of length 20 will have 15 bytes of entropy. The encoding used shouldn't matter because it is a …
=> generated password use better rng

classes/rest/endpoints/RestEndpointFile.class.php, unittests/selenium_tests/assets/file50mb.md5, unittests/selenium_tests/tests/UploadAutoResumeTest.php, www/js/upload_page.js
The idea here is that the travis env will use the comment hooks
like PUT_PERFORM_TESTSUITE to inject code that will selectively fail
on some cases. For example, claiming to have an issue on the second
chunk for a file called testing.txt.
=> ci: working on a new selenium test for auto resume upload

docs/v2.0/install/index.md
See: https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
=> actually use UTF-8 for MySQL/MariaDB

classes/data/AuditLog.class.php, classes/data/ClientLog.class.php, classes/data/DBObject.class.php, classes/data/Guest.class.php, classes/data/StatLog.class.php, classes/data/TrackingEvent.class.php, classes/data/Transfer.class.php, classes/data/TranslatableEmail.class.php, classes/data/User.class.php, classes/utils/DBView.class.php, classes/utils/Database.class.php, classes/utils/DatabaseMysql.class.php, classes/utils/DatabasePgsql.class.php, scripts/upgrade/database.php
These views are designed to have some support for retiring data
that has gone past a given number of days of age. Hopefully in the
future they can be expanded and other views added to help make queries
simpler by offloading things like date handling which is different in
pgsql and mysql into the view definitions. Capturing database
differences in a single view definition is likely to give much better
maintenance.
As dropping and creating views doesn't do any actual data changes
other than updating view definitions the entire view is dropped and
recreated each time the upgrade/database.php script is executed.
Refinements to the views and removal of complexity from some of the
SQL will follow, for example, the query in www/lib/graph/uploadGraph.php
=> db: initial support for views

classes/constants/GUIPages.class.php, classes/data/AuditLog.class.php, classes/data/DBObject.class.php, classes/data/Guest.class.php, classes/data/StatLog.class.php, classes/data/TrackingEvent.class.php, classes/data/TranslatableEmail.class.php, classes/utils/DBView.class.php, classes/utils/GUI.class.php, classes/utils/Mail.class.php, includes/ConfigDefaults.php, language/en_AU/lang.php, language/en_AU/privacy_text.html.php, scripts/task/cron.php, templates/menu.php, templates/privacy_page.php
Some row types in auditlog were not reclaimed, for example, user
created entries. Now also old auditlog entries for guests who have
been deleted are also deleted rather than left orphaned.
A new privacy tab is added to the web interface allowing users to
see how long some of the information is retained by the system.
=> privacy: sunsets on how long data is held

classes/data/User.class.php, classes/rest/endpoints/RestEndpointUser.class.php, language/en_AU/lang.php, language/en_AU/user_profile_delete_about_description_text.html.php, templates/user_page.php, www/filesender-config.js.php, www/js/client.js, www/js/user_page.js
This update offers a button on the My profile page which
allows the user to leave the FileSender instance. Doing this will
delete the user files, invited guests, etc from the database and
the file contents from the filesystem.
This is a bit tricky as the user can still come back using the same
SAML auth in many cases. So the distunction between the data the
FileSender is storing (in database etc) and the login information is
described above the remove account button.
=> GDPR: Allow a user to leave the system

classes/data/User.class.php
It seems the creation time was not set unless it was forced in the from authid method.
=> db: set user creation time in new db schema

classes/storage/StorageCloudAzure.class.php, optional-dependencies/azure/.gitignore, optional-dependencies/azure/composer.json, optional-dependencies/azure/composer.lock, scripts/cloud/azure/azure-simpleblob-benchmark.php, scripts/cloud/azure/test-azure-simpleblob.php
Move from https://github.com/Azure/azure-sdk-for-php/
To        https://github.com/Azure/azure-storage-php
Only fairly small changes needed, tested against azurite.
For local azurite.
```
php azure-simpleblob-benchmark.php
Connecting to Azure server took 0.01 seconds
performance testing...
0.9 mb/s to write   1.0 mb to server, total time needed was 1.1 seconds
4.1 mb/s to write   5.0 mb to server, total time needed was 1.2 seconds
7.0 mb/s to write  10.0 mb to server, total time needed was 1.4 seconds
14.6 mb/s to write  50.0 mb to server, total time needed was 3.4 seconds
16.7 mb/s to write 100.0 mb to server, total time needed was 6.0 seconds
18.9 mb/s to write 200.0 mb to server, total time needed was 10.6 seconds
```
=> cloud azure: move to newer azure storage API

classes/exceptions/DBIExceptions.class.php, classes/utils/DBI.class.php, scripts/upgrade/database.php
Sometimes things interact in 'interesting' ways. For example adding a not null constraint to a column might not work if there is an FOREIGN KEY (fk) in use. This might be the case during a database migration from an older database where a column is created in a slightly different way (allowing null) so that data can be migrated into the database updating that new column before it is set to not null.
Keeping the fks at the end of the script allows this shuffle on those columns to happen before an attempt is made to lock down the fk constraint. I think this particular migration worked for later mariaab (nulls -> no nulls) but certainly causes an issue with mariadb 10.0 as seen in https://github.com/filesender/filesender/issues/394#issuecomment-416116520
Giving the fks a name allows the use …
=> db: delay creating fks to the end of script

.travis.yml
This should be implicit anyway because we only setup the database we are planning to use. But also we save some RAM for the test run by stopping one of them.
=> ci: catch attempts to use the database we are not planning to use

templates/menu.php
If `auth_sp_embedded` is set all rendered pages will be broken (`menupage` doesn't seem to exist anymore, whatever it did). This PR fixes an undef var leading to fatal error:
```
AH01071: Got error 'PHP message: PHP Notice:
Undefined variable: menupage in /opt/filesender/templates/menu.php on line 56
PHP message: PHP Fatal error:  Uncaught Error: Function name must be a string in /opt/filesender/templates/menu.php:56
Stack trace:
thrown in /opt/filesender/templates/menu.php on line 56
```
=> Fix Undefined variable: menupage

classes/utils/DatabaseForeignKey.class.php, scripts/upgrade/database.php
This abstracts out the FK creation into it's own class. Doing this helps make the code easier to read, avoids having raw arrays of arrays floating around, and allows reuse of this in other parts of the code.
This is based on the code from https://github.com/filesender/filesender/pull/414.
The SQL to check if an fkey exists in mariadb is updated to avoid looking at index names which might be an implementation detail and directly at the fk constraint itself in the schema.
=> fk creation abstracted out to new class, exists check updated

scripts/upgrade/database.php
Var classes created line 88 is overrided during database migration version 22 line 420 , which prevents the creation of 3 views including auditlogsview which is essential for the cron.
=> Fix var classes overrided during migration

classes/data/AuditLog.class.php
Until mariaDb 10.3.1 (or on Mysql) you can't reference the table being deleted or updated. Because of that the function called by the cron AuditLog::cleanup is crashing. We can workaround that by using a join.
=> Fix crash during cron on mariadb < 10.3.1

scripts/language/common.php
After editing the french translation on poeditor, i tried to use the import-translation-for-language command, but the function squote is deleting the letter before escaping a single quote.
Example :
- Export Poeditor : `M\'ajouter aux destinataires`
- After the actual squote function : `\'ajouter aux destinataires` 
The commit fixes this issue.
=> Fix escaping quoting

optional-dependencies/s3/composer.json, optional-dependencies/s3/composer.lock
guzzle/guzzle deprecated and replaced with guzzlehttp/guzzle this is fixed in aws sdk 3.0
=> Fix s3 dep

classes/auth/AuthSPFake.class.php, classes/auth/AuthSPSaml.class.php, classes/auth/AuthSPShibboleth.class.php, classes/data/Guest.class.php, classes/data/Transfer.class.php
when building self-referential URLs with query strings, as used by other [Templates](https://github.com/filesender/filesender/blob/filesender-2.4/templates/download_page.php#L25-L34) or Classes, e.g. [Recipient.class.php](https://github.com/filesender/filesender/blob/filesender-2.4/classes/data/Recipient.class.php#L292) or [TranslatableEmail.class.php](https://github.com/filesender/filesender/blob/filesender-2.4/classes/data/TranslatableEmail.class.php#L382).
Actually I'm interested in replacing calls to `Utilities::http_build_query()` with another function that makes the generated URLs site-configurable beyond the `site_url` (e.g. in order to support "clean URLs"), but let's make the existing code more consistent first.
=> Consistently use Utilities::http_build_query

classes/data/Transfer.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/upload_page.php, www/css/default.css, www/js/upload_page.js
This is an alternate way to handle what https://github.com/filesender/filesender/pull/441 is doing.
The idea of this PR is to put the available=false options into hidden form elements. The code can then get those options just as it gets the shown options. The goal is to avoid having javascript code that does form.optionx is set or config.transfer_options_optionx is set because the later is communicated to the client in the hidden field which creates form.optionx. 
Yes, the client can then reverse this or mangle the javascript to show these hidden options but the server should recheck them to make sure nothing funny is going on. This issue is present no matter how these available=false options are sent. For get_a_link they must be sent to the browser as the javascript code has to operate …
=> create some hidden options to set not available options in the client javascript.

www/js/transfers_table.js, www/js/ui.js
As reported in https://github.com/filesender/filesender/issues/446 it can be confusing to see this additional scrollbar that will not do anything.
=> hide the scrollbar in the auditlog dialog as the page itself allows scrolling

www/js/client.js
The cache defeat getTime() was the only remaining part to be included from
https://github.com/filesender/filesender/pull/158
=> remaining part of PR 158

templates/user_page.php
This fixes the first bug in https://github.com/filesender/filesender/issues/477 where the language selector is not shown when the user does not already have an explicit selection in the database. Chicken and egg really as you are unlikely to get a selection set unless you can see this selector in the first place.
=> enable the language selector even when the lang is null

includes/ConfigDefaults.php
This fixes the second bug in https://github.com/filesender/filesender/issues/477 where the language selector is not shown by default.
=> my profile: turn on the language selector by default

.travis.yml, travis/scripts/simplesamlphp-setup.sh
This moves the CI to php 7.2.
Because selenium doesn't like the very latest phpunit that is used by php 7.2 by default I have also moved to using the phpunit that is installed from composer in the vendor directory to ensure compatibility.
There was an issue with the very old simplesamlphp being used so I have updated that to the latest and made moves to allow the version to be updated again in the future.
=> php72 but use the vendor phpunit

docs/v2.0/install/index.md
This offers the reader some information about the ie11/keyversion https://github.com/filesender/filesender/issues/452 when installing. It also opens the door for other compatibility issues to be listed at an appropriate time for new installations.
=> docs: ie11 and keyversion

docs/index.md, docs/roadmap.md, docs/v2.0/install/index.md
This relates to https://github.com/filesender/filesender/issues/466 which was mentioning if php 7.2 was ok.
=> docs: update to mention php 7.2 and where min versions are at in the docs.

www/js/user_page.js
If both the menu language selector and user preferences language selector are shown change the menu language selector as the user changes the preferences selector. Less confusing when they navigate away from the page. 
Note that as the user preference is saved the lang= part of the menu session language selection is not needed for that selector to be accurate when navigating away from the preferences page. eg, change preference to 'de' and then click upload page and the page is rendered in German (as per the set and saved preference) and the menu item is also showing 'de' which is what you have.
=> lang ui: set the menu lang item when the user preference is changed

classes/utils/Config.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, scripts/task/emailfeedback.php
This relates to issue https://github.com/filesender/filesender/issues/420. I have removed about_url.
The old help_url is removed and replaced with an optional support_email. The support_email is not optional when you set relay_unknown_feedbacks to support  as you are wanting to send things to the support_email. The docs mention this and the code will also let you know if you forget to define the support_email and it should be.
=> docs cleanup and code refresh for help_url to support_email

classes/rest/endpoints/RestEndpointTransfer.class.php, www/js/client.js, www/js/transfer.js, www/js/upload_page.js
This is to strengthen up the AUP checked policy as noted in https://github.com/filesender/filesender/issues/440.
One can test this by disabling the block on the user_page that creates the form element. 
https://github.com/filesender/filesender/blob/c0f85be2130edabac0308d073937a09cd93fa359/templates/upload_page.php#L289
This is the sort of thing a nasty client/user might like to do in the browser before the javascript can see the form elements. They might think they are smart removing the form elements so they can send a file without needing to check the aup element. This code will detect that attempt because there is no checked aup sent to the server.
=> server side recheck for aup_checked in case form is mangled by user

classes/data/Transfer.class.php
This addresses the double encoded link highlighed in issue https://github.com/filesender/filesender/issues/465. Mail messages should now contain links that will direct you to the right place.
=> mail: do not double encode the right side of the URL

classes/data/Guest.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, templates/guests_page.php, templates/upload_page.php
When you set can_only_send_to_me as a default=1 and available=0 so the user can not change it then you should disable get_a_link stuff (two are exclusive). With this update you can force can_only_send_to_me and the guest will have no option otherwise and the form is prepopulated as expected.
This relates to https://github.com/filesender/filesender/issues/460.
=> guests: can_only_send_to_me default=1 and available=0

classes/utils/Lang.class.php, classes/utils/Utilities.class.php, templates/guests_page.php, templates/upload_page.php, www/filesender-config.js.php, www/js/guests_page.js, www/js/lang.js, www/js/upload_page.js
This makes the date_format, datetime_format and dp_date_format configurable by setting them with a tr_ prefx in config.php. For example, to add day of week to your instance:
```
$config['tr_date_format'] = '%A %d/%m/%Y';
$config['tr_datetime_format'] = '%A %d/%m/%Y %T';
$config['tr_dp_date_format'] = 'DD dd/mm/yy';
```
Overriding these settings in config.php was suggested in https://github.com/filesender/filesender/issues/299.
=> allow setting the date_format et al in config.php

www/js/download_page.js
This is a band aid until https://github.com/filesender/filesender/issues/325 is completed.
=> osx: always show zip64 warning on download page

classes/utils/Archiver.class.php, classes/utils/Filesystem.class.php, includes/ConfigDefaults.php
The content-length can be calculated using a shallow pass over the data, building an archive without needing to read/write the contents of the files from storage. Using the same API gives the advantages that the padding and other metadata included in the tar is going to be the same as what is generated using a non shallow (real) copy of the data when we stream the real archive to the user.
Note that if you have something like the following running for a tree that includes www/download.php then the size information will be lost in transit. 
```
<Directory "/opt/filesender">
<IfModule mod_deflate.c>
SetOutputFilter DEFLATE
</IfModule>
```
If you are going to on the fly compress like that then maybe use something like the below to override for just download.php. There are likely more elegant …
=> tar: calculate the content-length and set header

classes/utils/Archiver.class.php, lib/PHPZipStreamer/src/ZipStreamer.php
This uses the same design as the tar content-length making a zip file with only metadata in order to work out how large the real zip file is going to be.
=> zip: calculate the size of the zip and set content-length

classes/utils/ApplicationMail.class.php
It was noted in https://github.com/filesender/filesender/issues/515 that blank lines in subjects are not filtered out in favor of the more default generic subject lines.
=> handle blank subject lines in translations

classes/utils/DBI.class.php, classes/utils/Logger.class.php, docs/v2.0/install/index.md
The database.php script wants DROP and REFERENCES privileges to operate. The former can be used to do some fairly undesirable things and so should be limited in exposure. This PR allows the database.php script to connect using db_username_admin and db_password_admin. This way, the regular web site can operate without elevated privileges and the database.php script can connect with additional powers needed to perform it's work. 
The docs are updated to recommend this new two user setup which will also mean less admin allowing and dropping privs when you run the database.php script.
This relates to https://github.com/filesender/filesender/issues/453.
=> db: allow two user accounts for elevated priv in database.php

classes/data/StatLog.class.php, classes/data/constants/DBConstantBrowserType.class.php, classes/data/constants/DBConstantOperatingSystem.class.php, classes/utils/DBView.class.php, classes/utils/DatabasePgsql.class.php, scripts/upgrade/database.php, templates/admin_statistics_section.php
It was mentioned in https://github.com/filesender/filesender/issues/464 that MySQL has an issue with the old admin stats SQL. This lead me to wonder what grouping by the additional_attributes column really meant when we are already grouping by 3 subselections of additional_attributes using LIKE.
The code update creates two new real columns which reference two new dbconstant tables and a view to return the string version of these numbers for easy access. The updated query no longer mixes HTML fragments into large CASE statements inside the SQL itself. At the least this makes the query much more readable. I may move the is_encrypted to being a real field using this plan soon to fully optimize things.
The admin/statistics page now works for me too, so there was something not happening in …
=> sql: update the admin stats SQL

classes/data/StatLog.class.php, classes/utils/DatabasePgsql.class.php
It isn't a really great design to take a boolean value and put it into additional_attributes only to try to pick it out again in the SQL query and group by it. We might as well store it as a bool in the database and avoid the unneeded to string and LIKE loops.
=> db statlog: move is-encrypted to being a real column

classes/utils/Config.class.php, includes/ConfigDefaults.php
If the upload_chunk_size and upload_crypted_chunk_size are not set correctly then bad things can happen. This checks that those settings are correct early and faults to avoid finding issues later.
This relates to https://github.com/filesender/filesender/issues/397.
=> config: complain early if the admin settings are not going to work

includes/ConfigDefaults.php, www/css/default.css, www/filesender-config.js.php, www/js/transfer.js, www/js/upload_page.js, www/lib/terasender/terasender.js, www/lib/terasender/terasender_worker.js
This is targeted at the specific case when the network drops out during an upload https://github.com/filesender/filesender/issues/217. In this case the server may drop the connection and the client must rebuild the connection automatically. The catch is that sometimes creating web workers will also fail due to network IO issues (the network went away after all). So this adds detection for failed web worker startup and flags that as a failure after a period of time. 
I have found that in testing using terasender_worker_xhr_timeout at around 3 seconds a number of automatic resumes occurs before the actual upload starts again. I'm not sure why the web workers keep failing to start, but it does pick up again, maybe after 4-5 attempts and 20 seconds after reenabling wifi.
This also adds …
=> uploading: catch terasender startup fails, xhr timeout, better net stall reporting

classes/data/constants/DBConstantOperatingSystem.class.php, classes/utils/Browser.class.php, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/upload_page.php, www/css/default.css, www/js/upload_page.js
One Firefox and Chrome a select directory option can be added to hint to the user that they are able to upload an entire directory if they like. This is only available if the site allows directory upload (a config.php option). Also the button can be disabled if desired.
If directory upload is enabled the user should be able to drop a directory onto the form. But it might be more friendly and obvious just having a "select directory" button.
This relates to https://github.com/filesender/filesender/issues/372.
=> upload: add a upload directory button where supported.

classes/data/DBObject.class.php
make convertTableResultsToObjects static to avoid Deprecated: Non-static method DBObject::convertTableResultsToObjects() should not be called statically
=> make convertTableResultsToObjects static

classes/rest/RestServer.class.php, config-templates/apache/filesender.conf, docs/v2.0/install/index.md, www/filesender-config.js.php, www/index.php
There is only one area that I can see that uses frames/iframe in filesender. This is to support legacy browsers that do not support the FileReader API. The FileReader is supported on IE10 and many older browsers (https://developer.mozilla.org/en-US/docs/Web/API/FileReader#Browser_compatibility).  This makes the legacy iframe code very unlikely to be useful these days. 
As such I have made the default policy for X-Frame-Options to be deny. The iframe code has not been pruned yet in case it is discovered to be required by some sites and the X-Frame-Options can be adjusted to allow it again. If nobody notices that x-frame is denied then the legacy code can be pruned away.
=> security: start removing the possible use of frames.

classes/rest/RestServer.class.php, classes/utils/Security.class.php, docs/v2.0/admin/configuration/index.md, docs/v2.0/install/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/index.php
Instead of setting the header all over the place, use a new Security class to set that policy in code in one place. That uses a new config.php setting to provide the default choice and there are docs for that new setting. This should make it clean to issue a 'none' value and disable it in the web server configuration for sites which do not wish to use the default sameorigin policy or wish to tighten it up to a 'deny'.
=> security: clean up the policy, add docs

config-templates/apache/filesender.conf, docs/v2.0/install/index.md
These are to 
* Disable displaying errors for simpleSAMLphp
* Disable directory listings in the web server configuration
* Set the Secure flag on cookies that contain a session id
Note that the later only works when the site can only be accessed over https which is recommended. A later PR will cover that detail.
=> simplesamlphp security: some high level config recommendations

docs/v2.0/install/index.md
Recommend using https for the site config. A little paragraph that older versions may along with info as to which versions should really be stuck to.
=> docs and install: min versions, recommend https

www/js/upload_page.js
In Chromium-based browsers, the select directory dialog would appear straight after the select files dialog when clicking "Select Files".
This just makes the selector more specific so that doesn't occur.
=> Prevent both file and directory selection occuring

templates/download_page.php
disable "You can download all files at once as a single compressed archive (.zip) file." when transfer is encrypted as you can not download a zip of it.
=> Update download template

classes/utils/FileSendercsrfProtectorLogger.class.php, classes/utils/Logger.class.php
A call site generally knows if it is recording something relating to security so a new Logger method to articulate that can be helpful. At the moment the call just adds some metadata to the message but it could in the future redirect these from simple ERROR to some SECURITY log file.
=> Logging, new securityIssue() call for potential security logs to be made with

config-templates/apache/filesender.conf, docs/v2.0/install/index.md
The goal of this is to try to limit browsers sending the simplesaml cookie from other sites to a filesender instance. Such as might happen with a third party site trying to use a logged in session to do things without explicit user consent. If the saml cookie is not sent then the user will be seen as not authenticated and requests to perform data modification will be blocked at that level. This relies on a modern browser being used which will respect the samesite selection, of which many browsers do these days.
php 7.3 supports adding this at the code level. It is a bit of a nasty kludge to do it in a php 7.x and 7.3 compliant way, and also in lower level libraries as well as filesender itself. In the shorter term using the apache config to blanket things is a simpler solution.
=> info about adding samesite param to cookies

classes/utils/DatabasePgsql.class.php
This will allow the update script to treat the default value for boolean columns properly and not try to update it when an update is not needed. Specifically if a column was already boolean and the right value we do not try to reset the default. The code to reset the default was also using 1/0 which pgsql doesn't like and would fail on. 
So now you should be able to run update.php two or more times without triggering an issue.
The initial refresh of boolean handling in the postgresql class didn't catch this issue.
Initial update is at https://github.com/filesender/filesender/commit/230c4085279277db2958989e25843c9b38157b32#diff-e827e779c944a7e88324da63750161d2L639
=> dbpsql make update script idempotent on bool columns

templates/transfers_table.php
This should have the same effect as https://github.com/filesender/filesender/pull/589
The main difference is that this PR sets a variable at the top of the file and uses that to select a max spanning row at the bottom of the page. The reason for this modification is desire to try to keep the HTML part of the page as simple as possible.
=> ui: update for row spanning entire table row in guest case

classes/data/constants/DBConstantBrowserType.class.php, classes/data/constants/DBConstantOperatingSystem.class.php, templates/admin_statistics_section.php
Fixed the  browser/os/encryption stats display, somehow...
OS detection doesn't seem to work?
-------------------------------------------------------
Older stats (pre 2.6) are displayed like before with commit f24ab04 
```
Unknown
Unknown
{"encryption":true}
```
-------------------------------------------------------
Older stats (pre 2.6) are displayed like newer stats (>= 2.6) with commit 26b2b60 .
=> fixed the browser/os stats display in admin_statistics_section.php (FS > 2.5)

classes/data/StatLog.class.php
This should fix cron.php crashing with error no_such_property #557
=> Fix to cron.php - Added missing new properties to __get() from StatLog.class.php

classes/data/AuditLog.class.php
This moves joins into a subselect. Tested on mariadb and postgresql locally.
=> cron db: move to a subselect for the auditlog cleanup

classes/utils/Config.class.php, classes/utils/Template.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
This is a little massage of the core code from https://github.com/filesender/filesender/pull/590. I thought it cleaner to separate out the list of locations and the code that operates a location into two distinct code blocks. There is also a docs entry for the new config and it is explicitly in the defaultconfig (as an empty string).
=> ui: allow a subdirectory of templates to be selected as the active theme

language/en_AU/lang.php, templates/guests_page.php, www/css/default.css, www/js/guests_page.js
This updates a bad interaction when the config.php shown below is used. In this case can_only_send_to_me will be checked in the interface and get_a_link will be unchecked by default.  There is now a notification if you subsequently select get_a_link letting you know that can_only_send_to_me has been changed to false and disabled. A subtle background colour is used to link these two options on the page as well. It is possible that a different user interface element such as a single selection drop down or list should be used to handle this setting making the choice explicit and not offering combinations that do not make sense.
```
$config['guest_options'] = array(
'can_only_send_to_me' => array(
'available' => true,
'advanced' => false,
'default' => true
),
```
This relates to …
=> guests: improved interaction of get_a_link and send_to_me

language/en_AU/lang.php, www/js/upload_page.js
When an upload has failed and all the automatic resume attempts have been used then pause the upload to avoid more errors from occurring.
This also abstracts out the pause() and resume() functions so that the many sites that want to perform that can do so without needing to explicitly attend to timers, user interface elements etc that might need to be updated.
=> upload: abstract out the pause and resume functions

classes/auth/Auth.class.php, classes/constants/GUIPages.class.php, classes/utils/GUI.class.php, language/en_AU/lang.php, templates/about_page.php, templates/admin_page.php, templates/menu.php, templates/pagemenuitem.php, templates/statistics_page.php
The statistics page is now a top level menu item. It has a $config['can_view_statistics'] config.php setting which has the same format as the 'admin' config. The stats page can also be enabled for a user through SAML with the auth_sp_saml_can_view_statistics_entitlement config setting and the other saml attribute that are used to define admin rights through SAML attributes (ie,            auth_sp_saml_entitlement_attribute, auth_sp_additional_attributes).
The statistics page also includes a link to the aggregate statistics section if that feature is enabled.
=> ui: bring out statistics from admin page

www/js/download_page.js
Using the same code to offer less surprises when config settings are changed.
=> archives: remove difference in action when enable_recipient is false

language/locale.php, scripts/language/import-langs-directory.sh
I added a comment to the import-all script as that is likely to be the first place that is updated when a new locale is added and that is likely to be a relatively rare event.
=> i18n: when adding a locale you must update this too

classes/rest/endpoints/RestEndpointTransfer.class.php, includes/ConfigDefaults.php
Also, to the default setting for reports_show_ip_addr is now false.
=> make reports_show_ip effective on the transfer audit log

travis/filesender-config.php, unittests/selenium/SeleniumTest.php, unittests/selenium/tests/EncryptionTest.php
This is to help assure that the encryption_key_version_new_files config setting can be changed while allowing transfers that already exist on the server to still be downloaded and decrypted. Much of this has been tested manually, but having it here will help avoid regression.
=> ci test that key_version is stored per transfer by using many key_versions in ci

classes/constants/CryptoAppConstants.class.php, classes/data/File.class.php, classes/exceptions/BadExceptions.class.php, classes/rest/endpoints/RestEndpointFile.class.php, www/js/admin_testing.js, www/js/client.js, www/js/crypter/crypto_app.js, www/js/terasender/terasender.js, www/js/terasender/terasender_worker.js, www/js/upload_page.js
This adds two new key version modes for AES-256-GCM encryption. These mirror the existing AES-256-CBC modes but use GCM (see https://en.wikipedia.org/wiki/Galois/Counter_Mode) for more details than could easily be described here. The implementation uses a design proposed by a cryptographer where the IV is derived using a combination of entropy and a chunk counter to avoid the possibility of IV reuse across chunks.
This has been tested as working across Firefox, Chrome, and Safari. Tests were performed also uploading in one browser and downloading in the others across these choices. These modes do not work in Edge or IE. 
Some more documentation will follow for the encryption_key_version_new_files settings 2 and 3 which enable these new modes using digest_importKey and importKey_deriveKey …
=> crypto: add new AES-256-GCM encryption modes

classes/data/File.class.php, classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/download_page.php, templates/transfers_table.php, www/filesender-config.js.php, www/js/client.js, www/js/crypter/crypto_app.js, www/js/download_page.js, www/js/terasender/terasender.js, www/js/terasender/terasender_worker.js, www/js/transfer.js, www/js/transfers_table.js
A random IV is now created client side and stored in the database for
each uploaded file (the fileiv). That IV is 12 octets long for GCM
mode and 16 octets (unused) for CBC.
The fileiv is now used to set the first 12 octets of the IV for a file
during upload for GCM files.
For GCM: The fileiv is verified against the IV for each filesender chunk during
decode to ensure that it is the same for the IV for each filesender
chunk for the file.
The chunkid is extracted from the IV for each filesender chunk to
verify that it has the correct value (it is for this filesender chunk).
When the FileSender chunkid is encoded and decoded to an encryption IV
it is now expaned to cater for the FileSender upload_chunk_size and
contracted back during a decode. The exact value setting of the
chunkid needs to …
=> GCM updates: IV stored per file, more checks

classes/data/File.class.php, classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, language/en_AU/lang.php, templates/download_page.php, templates/transfers_table.php, www/js/client.js, www/js/crypter/crypto_app.js, www/js/download_page.js, www/js/terasender/terasender.js, www/js/transfer.js, www/js/transfers_table.js
This introduces the use of AEAD for GCM mode encrypted files.
https://en.wikipedia.org/wiki/Authenticated_encryption#Authenticated_encryption_with_associated_data_(AEAD)
AEAD is used to ensure that the chunk size has not changed and that exactly the number of filesender chunks that should be received are received. The random 96 bits of the encryption IV for a file are also stored in AEAD and asserted to be the same as the 96 bits of entropy of a fileiv on decrypt.
As the filesender chunk size and number of chunks are in AEAD the client ensures that the chunk size has not changed after encryption and that the server has sent exactly the correct number of filesender chunks to the client. Changing the filesender chunk size (the value of upload_chunk_size in config.php) is unlikely to happen …
=> GCM: AEAD version 1 to ensure whole file and iv

classes/rest/endpoints/RestEndpointTransfer.class.php, classes/utils/Config.class.php, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/crypter/crypto_app.js
It was found that we can move to using the filesender chunkid directly in the formation of the IV.
=> GCM: we can relax the IV counter. New chunk max size checks

www/js/crypter/crypto_app.js, www/js/transfer.js
There isn't much point to making and storing the AEAD for the AES-CBC cipher modes.
=> AEAD: only generate and store one for GCM modes where it is useful

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/js/admin_testing.js
The API changed slightly for this and the code expects to find aead stuff there if you are using a key_version that uses GCM. I also updated the docs for the config variable encryption_password_hash_iterations_new_files.
=> hash iterations part working with aead

classes/data/Transfer.class.php
This is purely cosmetic and allows the admin sniffing around the database to see password origin without needing to know the numbers.
=> db: add a new generated text column to transfersview

classes/data/constants/DBConstantPasswordEncoding.class.php
Main change is the last part of the file where the regex is enabled again and the error message only displayed on invalid data. Also the function will die on invalid now too.
I'm not sure why this was non unix formatting, that is why it is a small file replace.
=> dbconstant validator active and will die if invalid data given

www/js/crypter/crypto_app.js
This will cache keys where possible to avoid unnecessary recomputation.
Previously generateKey() would be called for every chunk uploaded. This can cause performance issues when large password hash counts (https://www.w3.org/TR/WebCryptoAPI/#pbkdf2-params) are in use as they will be calculated for each chunk uploaded rather than once for an upload or upload-worker thread. Such hash counts may incur a 30 second delay for hash iterations alone. This is a direct trade where a longer time spent in hash iterations makes it more time consuming for an attacker to try to guess a password.
Looking at the filesender-2.10 code one will notice that generateKey() will also generate and reference a new IV for each time it is called (each chunk). That IV handling was expressly overridden in GCM mode …
=> crypto: cache keys if possible to avoid redundant work

scripts/client/filesender.py, www/clidownload.php
Thanks to @peter- for PR 677 which found this issue and suggested a good solution to it. This is a slight update to https://github.com/filesender/filesender/pull/677 to make the regex more specific so that it can only match on the variable declaration line. I found that 677 would substitute on the line https://github.com/filesender/filesender/blob/master/scripts/client/filesender.py#L149 as well with unintended side effects. It is also tempting to use ^ and $ to limit the match scope but as the script is passed as a single string that would not match. Thus the fallback to using the newline to limit the match to only the variable declaration.
Maybe in the future we are better off building a map of configuration names that should be substituted and looping over that map doing a substitution …
=> small update to pr 677 to tighten the regex

classes/data/Guest.class.php, classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, scripts/task/cron.php, scripts/upgrade/explicit/upgrade-2.11-to-2.12-after-database-guestsexpire.php, templates/guests_page.php, www/js/guests_page.js
This brings out the do not expire option to near the expire date selection. The expires column in the Guests table can now be null to indicate that the guest does not expire. This is explicitly set if does not expire is selected during guest creation. 
Some of the SQL fragments had to be updated to return results where the guest does not expire. Without doing this then some guests might not have been returned, for example ones that had a expires time before now but are set to never expire. IMHO it is better to use null for guests that do not expire to explicitly capture the intent that the guest has no expire time.
Tested on Firefox, will test on other browsers soon.
=> guests: better handling of do not expire

language/en_AU/lang.php, www/filesender-config.js.php, www/js/client.js, www/js/guests_page.js
This should resolve https://github.com/filesender/filesender/issues/652
One downside of my initial design is that client.js was handing specific errors at a low nested level. I have added specificErrorHandler to allow client code to explicitly handle some errors in a nice way without having the main client.call() method try to do everything for everyone.
=> guests: show a nicer dialog when user has max guests

scripts/language/oldterms.txt
local repo oldterms.txt updated with ./export-terms-to-new-and-deleted-lists.sh to reflect the list of active terms on poeditor. That new term was already on poeditor so now things are in sync again.
=> i18n: update oldterms to include current data from en_AU

scripts/language/compare-php-lang-files.php, scripts/language/convert-poeditor-json-to-php.php, scripts/language/import-all-from-poeditor.sh, scripts/language/import-langs-directory.sh
A new import-all-from-poeditor.sh top level script to get the language files from poeditor (in json) and convert those to php format before importing them all. The compare-php-lang-files.php script is there to help tell of a php file that is manually exported using the poeditor web interface has significant differences to the converted json file that was obtained using the web api for poeditor.
The direct poeditor import script needs an API key which is expected to be in a file in the user's home directory.
These scripts still need testing. I will start doing some imports using the code like is in these scripts in the next days and comparing their output to the output generated by importing the php from the poeditor web interface. These scripts may see some updates to get into final state …
=> i18n: new script to import from json from poeditor

classes/data/Transfer.class.php, classes/utils/Config.class.php, classes/utils/GUI.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, www/filesender-config.js.php, www/js/crypter/crypto_app.js, www/js/download_page.js, www/js/pbkdf2dialog.js, www/js/terasender/terasender.js, www/js/terasender/terasender_worker.js, www/js/transfer.js, www/js/transfers_table.js, www/js/upload_page.js
An optional dialog can be shown when a password is bring turned into a key which can be a time consuming task.
This dialog is not shown by default currently. That is likely to change soon with other default config settings. The dialog can be enabled with the configuration setting crypto_pbkdf2_dialog_enabled=true.
Depending on how many iterations you are using for key derivation the action can take a long time. See for example https://en.wikipedia.org/wiki/PBKDF2 for more information. If the user is confronted with an interface that does not show any upload or download progress for tens of seconds or minutes they will very likely assume something has failed. This might not be the case, the browser may instead be performing PBKDF2 iterations to derive a key from a password.  Given this …
=> crypto: new dialog displayed with pbkdf2 is taking place

classes/utils/Config.class.php, classes/utils/Crypto.class.php, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/admin_testing_section.php, www/js/admin_testing.js
The admin/testing page now contains a button to generate PBKDF2 performance information in the browser. This is useful for administrators who are looking to tweak the default number of iterations to use for PBKDF2 so that their intended users get a security-to-performance trade off that is known.
A subsequent PR will create a default value for crypto_pbkdf2_expected_secure_to_year which will be shipped in a subsequent release.
=> crypto: add to test page some performance generators

www/js/download_page.js, www/js/pbkdf2dialog.js, www/js/transfers_table.js, www/js/upload_page.js
On chrome it can take a while for all workers to complete, so keep the dialog open until all workers are uploading to avoid a little 1-2 second delay without any UI updates.
This complicates things a little because the dialog is closed either on ended (single worker) or allended (terasender upload).
=> Have the PBKDF2 dialog remain open until all terasender workers are ready

includes/ConfigDefaults.php, travis/filesender-config.php, unittests/selenium/tests/EncryptionTest.php
now that crypto_pbkdf2_expected_secure_to_year has a default value, enable the pbkdf2 delay dialog by default.
=> pbkdf2: enable dialog by default

language/en_AU/lang.php, scripts/client/filesender.py, templates/user_page.php, www/clidownload.php
This allows the base_url, apikey, and username to all be set in a configuration file instead of merged into the python script or provided explicitly on the command line. This relates to https://github.com/filesender/filesender/issues/716. There is now also a link to get this generated configuration file in the "my profile" page. 
The filesender.py wants python3 which is now described in the web interface and the script itself. Some minor python 3.8 updates were also done.
If you have get_a_link=1 as the default configuration for the filesender instance then unintended things used to happen. The script now explicitly sets get_a_link=0 because it expects a recipient on the command line. The script could be expanded to allow "get a link" but we should do the right thing right now with the …
=> filesender.py rest client: refresh

classes/constants/GUIPages.class.php, classes/data/User.class.php, classes/rest/endpoints/RestEndpointUser.class.php, classes/utils/Config.class.php, classes/utils/DatabasePgsql.class.php, classes/utils/GUI.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/user_page.php, www/css/default.css, www/filesender-config.js.php, www/js/client.js, www/js/user_page.js
The time that the api secret was generated is now tracked in the database. The secret can be deleted and created through the "my profile" page on the site. When creating an api secret, if the config api_secret_aup_enabled=true then a dialog is displayed with a link to the full apisecretaup page that allows the aup to be displayed in full in a single page. A secret is not generated unless the user confirms acceptance of this dialog.
The time of acceptance of the api secret aup is also displayed on this page.
This relates to issue https://github.com/filesender/filesender/issues/679
=> filesender.py ability to delete and create apisecret, uap

scripts/client/filesender.py
If a site wants an AUP on the rest clients then it is best to constrain that at the API secret generation point. There is now code that allows for that. So the client will pass along that the aup is accepted because you must have accepted the aup in order to even get an api secret that will be acceptable to the site.
=> filesender.py accept aup in client

classes/data/User.class.php, classes/rest/endpoints/RestEndpointUser.class.php, language/en_AU/lang.php, templates/admin_users_section.php, www/js/admin_users.js, www/js/client.js
This allows a user to be found have the admin to revoke their api secret. They can still make it again if they like, but if there is an aup in place they must accept that to remake the api secret. This button can also be handy to disable a key if a site notices what it regards as abuse of the rest api key. In this case it would be assumed to be unintended abuse, such as a compromised key. This is because the key is revoked but the user can remake a key and continue.
There is also a super "delete all api keys" which was added to allow the introduction of an aup which would require everybody to accept the api secret aup in order to start using the rest clients again.
This also leaves off the ESCAPE clause for pgsql, relates to https://github.com/filesender/filesender/pull/583. I think …
=> api secret: allow admin to delete for one or all users

classes/data/AuditLog.class.php, classes/utils/DBView.class.php
DBView::cast_as_number was called without the required $dbtype.  DBView::cast_as_number function also expects a viewcolname, which should be provided in the function parameter list.
=> Add missing parameter to DBView::cast_as_number; provide default viewcolname

classes/utils/Config.class.php, docs/index.md, docs/v2.0/admin/configuration/index.md, docs/v2.0/admin/reference/index.md, docs/v2.0/development-upgrade-notes/index.md, docs/v2.0/features/index.md, docs/v2.0/install/index.md, www/js/pbkdf2dialog.js
Removing some of these old left over references to flash as mentioned in https://github.com/filesender/filesender/issues/715.
I have also refreshed the main page to list the 1.6.x release line as deprecated.
=> flash: remove older references to Flash

www/js/transfers_table.js
If there is no file.path set then set it to file.name. Many of the translations use file.path and were not seeing any substitution in the my transfers / "see the transfer logs" button. 
This relates to https://github.com/filesender/filesender/issues/642
=> transfer log, set file path to name if not set

classes/rest/endpoints/RestEndpointTransfer.class.php
This improves upon https://github.com/filesender/filesender/pull/723 and addresses issue https://github.com/filesender/filesender/issues/642.
Testing was done in the my transfers / see the transfer logs.
This PR helps for the case that you drop a directory in the upload. Such uploads may have one or more leading directories that are created and in those cases this PR this will show the full path used for those files. Otherwise, just the file name is shown in the transfer log as there is no user supplied leading relative paths in that case.
=> transfer logs: allow full path for files with it

classes/rest/endpoints/RestEndpointTransfer.class.php, www/js/client.js, www/js/transfers_table.js
When you click on the see what happened to this file button on the my transfers page only the file specific dialog is shown. Stacking modal dialogs is not good form. Clicking to send an email report for a file will send a file specific report.
Expanding the file dialog to the transfers level dialog will also loosen the filtering so that the transfers level email is then sent if you want a report from that dialog.
This should fix https://github.com/filesender/filesender/issues/694.
=> transfer-logs better for file log

classes/data/Transfer.class.php, language/en_AU/lang.php, templates/transfers_table.php, www/css/default.css
The rows in the my transfers page have been converted to a table for cleaner formatting. If the upload was to email recipients then the subject and message is now also shown in the table.
=> my transfers as table with extra email md

templates/apisecretaup_page.php
The template adds no additional terms by default.
=> rest api aup add the terms template page

templates/apisecretaup_page.php, www/js/logger.js, www/js/ui.js
This is a preamble to handling cases where browsers ignore console.log() if developer tools are not open. This relates to https://github.com/filesender/filesender/issues/627
=> console log: ui.log() to also add items to clientlog

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/apisecretaup_page.php, www/filesender-config.js.php, www/js/logger.js
Slightly more context in clientlogs. The different name for the stash_len was only used in one place, so it was renamed to be more name consistent with the config.php setting.
=> clientlogs: increse log size to 100 by default. Rename stash_len to be consistent with config.php name

www/js/lang.js
Strengthen lang.js translation variable replacement against null/undefined values.
Without this any null value in placeholders will end up triggering a js error, interrupting translation process and resulting in a broken ui.
We noticed this when slightly inconsistent auditlogs data is sent to the client, it ended up in a broken auditlogs popup.
=> Strengthen lang.js variable replacement

classes/utils/Utilities.class.php
Adds support for multi-valuated client_ip_key config parameter (expressed from most significant source to least significant one).
When previously using X_FORWARDED_FOR with chained proxies the returned client IP was wonky since the header may be multi-valuated and needs parsing in that case.
IPs are validated using php's internals, rejecting local/private network IPs and reserved ones.
Configuration example :
- $config['client_ip_key'] = 'REMOTE_ADDR'; // filesender is its own front server
- $config['client_ip_key'] = 'X_FORWARDED_FOR'; // there is a proxy in front
- $config['client_ip_key'] = array('X_REAL_IP', 'X_FORWARDED_FOR'); // there is a proxy in front that uses real-ip, then x-forwarded-for
=> Improve client IP lookup

classes/utils/Lang.class.php
Restrict user lang preference use for when there actually is a user.
When we are running as LocalProcess auth considers that there is indeed authentication active but without any attributes, so Auth::user() returns a boolean, which cannot be used to get a lang pref property ...
=> Fix user lang preference use

config-templates/apache/filesender.conf
Typo in vhost config causing vanilla apache deploy to crash
=> Fixing typo in apache vhost config

classes/data/Authentication.class.php, scripts/simplesamlphp/passwordverify/PasswordVerify.php, scripts/simplesamlphp/passwordverify/README.md, scripts/simplesamlphp/passwordverify/filesender-config-to-authsources-fragment.php, scripts/simplesamlphp/passwordverify/patch-to-simplesamlphp.patch
This is a SimpleSAMLphp module that can allow FileSender to authenticate against password hashes in it's local database. This is an effort to help make smalller sized installations of FileSender easier so that more people can setup their own instance of FileSender and use it now during the Covid crisis to securely share files. While the README.md is fairly technical it is hoped that packages can be created for FileSender in this setup to allow quick deployment.
I hope to push this auth module to SimpleSAMLphp itself including moving extractAttributes() up to the SQL class at the time. As that happens, the instructions for this can be updated to reflect the simpler installation process.
Next up will be an option to allow the Web interface of filesender to set passwords for users so they …
=> Auth: new SimpleSAMPphp module to verify against filesender db

scripts/simplesamlphp/passwordverify/create-user.php
Making the initial user can not be done by the web interface because you need the initial user to login to the web interface. So this command line php script is the solution and hints that you might like to make that user an admin user so they can then use the web interface to create other users.
The my profile page of the web interface should also let the admin change their own password.  This is assuming that the create-user.php script is being run by a package installer and then the admin logs in with a known initial password and changes their own as the first step.
This is related to the recent changes in https://github.com/filesender/filesender/pull/762 and https://github.com/filesender/filesender/pull/761.
=> localdbauth: create-user command line script chicken and egg

classes/data/Transfer.class.php, classes/exceptions/RestExceptions.class.php, classes/rest/endpoints/RestEndpointFile.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, scripts/client/filesender.py, www/filesender-config.js.php, www/js/client.js, www/js/terasender/terasender.js, www/js/transfer.js
To add yet more security to the existing checks this PR creates a 16 byte random string when a transaction is created and returns that to the client. When the client is uploading file chunks (encrypted or not) it has to return that same roundtriptoken or the upload is rejected. This effectively binds the person creating a transfer to be the only person who can upload data to the files associated with that transfer.
Tested on Firefox, Chrome, {Edge, and IE11 on Windows 10}. In case this does something undesired in an environment is can be disabled with the chunk_upload_roundtriptoken_check_enabled config option (off by default).
This feature is off by default so that information stored in the browser that does not contain the roundtriptoken can still be used to upload a file. Also if a …
=> computest-414: increase lockdown that transaction creator is the file uploader

classes/exceptions/RestExceptions.class.php, classes/rest/endpoints/RestEndpointUser.class.php, travis/filesender-config.php, www/filesender-config.js.php, www/js/client.js, www/js/guests_page.js, www/js/upload_page.js
Use HTTP post to get the list of frequent email addresses to avoid a GET request that has a chance that it might introduce some data into logs that is not necessarily desirable.
=> only get frequent email addresses over http post

classes/exceptions/TransferExceptions.class.php, language/en_AU/lang.php, templates/download_page.php, www/download.php
This relates to https://github.com/filesender/filesender/issues/754
It was certainly confusing to see the old error message. I have used a new "presumed expired" exception type because we don't really know what happened to the data, if it was once valid it has been removed from the database but it might also be that it never was in there in the first place. We presume it expired because we presume the link was once valid.
=> UX: better error message when you attempt to download expired or deleted transfer

classes/data/User.class.php
The user should not have to remember the case used to find a frequent email address. This addresses the issue first reported here https://github.com/filesender/filesender/issues/531
=> email addresses are case insensitive.

www/filesender-config.js.php, www/js/crypter/crypto_app.js
As mentioned in https://github.com/filesender/filesender/issues/757 there is a difference between the encrypt and decrypt password input. This PR makes the decrypt password hidden by default with a checkbox option to show/hide it, similar to the upload page.
=> hide download password text visibility by default, option in dialog to show it

scripts/client/filesender.py
By catching SSL exceptions explicitly, and providing relevant user feedback, we can offer clients a little extra security assurance.
By using urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning), and verify=False in requests, there are no SSL warnings generated regardless of validity of server SSL certificate on the server.
This commit uses the first request that determines value of upload_chunk_size to establish validity of server SSL cert. If invalid, the user is advised of this. To bypass this measure, the --insecure flag can be used, which still generates a warning but lets to script continue to execute.
=> clientscript: Better handling of SSL warnings

www/js/transfers_table.js
Fix wrong jquery test that led regular users to be presented with admin transfer deletion options (delete with notice or delete crudely) instead of closing the transfer as expected.
=> Fix wrong jquery test

classes/data/Transfer.class.php
Transfer space usage was evaluated by fetching all individual stored files' sizes which, when there was a lot of online transfers, lead to php memory exhaustion, switching to db side sum fixes that problem.
=> Use db sum instead of fetching all individual sizes

classes/data/Transfer.class.php, classes/exceptions/RestExceptions.class.php, classes/rest/endpoints/RestEndpointFile.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php
This moves code from being replicated to test access into a new Transfer::havePermission() method to make the code checking for permission simpler. A new exception class was also added to avoid having to pass the user->id around to slipstream that code path.
=> Move to a new havePermission method for testing access

classes/rest/RestServer.class.php
If there was an exception during processing of the filter operation then do not try to lookup values there as that is not going to be an array and will cause issues for those who have
```
display_errors = On
```
in /etc/php.ini.
=> do not go sifting a non array if there was an exception

classes/utils/Utilities.class.php
I found a few things bumping into this running a cron job locally. It seemed like a nice idea to make the REMOTE_ADDR 127.0.0.1 if it is not found and is running in a cron job.
=> cron: seems running locally can bump into an issue with no REMOTE_ADDR

classes/data/TranslatableEmail.class.php, classes/utils/DatabaseMysql.class.php, classes/utils/DatabasePgsql.class.php
As recommended in https://github.com/filesender/filesender/issues/574 the variables in translatableemails is larger now. Longer term, it may make sense to have the code writing those variables trim down large (and hopefully redundant) data from variables.
=> db: make translatableemails.variables mediumtext

classes/data/DBObject.class.php, classes/data/Transfer.class.php, classes/utils/TransferQueryOrder.class.php, templates/admin_transfers_section.php, templates/transfers_table.php
This relates to https://github.com/filesender/filesender/issues/745 so the admin section the transfers listings can be sorted by clicking on the table headers.
A follow up PR might also use this base code for the my transfers page to allow the user to sort their transfers view too.
=> admin transfers page allow sorting

classes/data/ClientLog.class.php, classes/data/Guest.class.php, classes/utils/Config.class.php, scripts/upgrade/checkconfig.php
This relates to https://github.com/filesender/filesender/issues/633.
While there are no new tests in place this opens the door for longer tests on configuration settings. One issue here is if tests should be moved from Config::load() and moved to the longer validation method instead of being performed on every call for a static config.
=> config: a validation script to do more complex validation

classes/data/Transfer.class.php, templates/transfers_page.php, templates/transfers_table.php, www/css/default.css
This allows the my transfers page tables to be sorted by the user. It splits the closed transfers table into a subpage and uses tabs to select which page the user wants. The default size of each table is now 15 entries as the pages are less cluttered because they only have one table on them.
This builds on the core code introduced in https://github.com/filesender/filesender/pull/794.
=> ui: allow tables on my transfers page to be sorted

classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointRecipient.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, language/en_AU/lang.php, templates/transfers_table.php, www/js/client.js, www/js/transfers_table.js
This addresses https://github.com/filesender/filesender/issues/358 allowing the stats to be removed for a transfer. I think this is a better option than annoying users with many stats and confronting them with the choice to delete a transfer and remake it in order to hush stats.
=> The ability to remove some transfer options, only daily stats for now.

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
Share the knowledge that a zero means that there are not rate limit at all for that configuration.
=> rate limiting: update docs and default policy.

scripts/language/oldterms.txt
This is the update performed by
```
cd scripts/language
./export-terms-to-new-and-deleted-lists.sh
``` 
as per the i18n docs.
=> keep i18n terms list up to date on poeditor

www/js/crypter/streamsaver_sink.js
A popup to inform the user that they need to leave the web page open while downloading an encrypted file with streaming.
=> streamsaver: hint to user not to leave download page while active

travis/filesender-config.php, unittests/selenium/SeleniumTest.php, unittests/selenium/tests/EncryptionTest.php
This took a little bit of digging but seems to allow the CI to run against chrome 84. On the upside I now have a local selenium environment to run tests against so updating that part of the CI system is going to be much less of a hassle.
=> CI: move to modern chrome

travis/filesender-config.php, unittests/selenium/SeleniumTest.php
Now that CI is updated to using Chrome 84 we should be able to use StreamSaver on the CI.
=> CI: now that we have recent chrome, use streamsaver in CI

classes/utils/GUI.class.php, language/en_AU/lang.php, templates/admin_testing_section.php, templates/download_page.php, www/js/admin_testing.js, www/js/crc32handler.js, www/js/crypter/crypto_app.js, www/js/crypter/streamsaver_sink.js, www/js/download_page.js, www/js/zip64handler.js
This patch allows the streaming download of one or more encrypted files into a generated zip64 archive. Note that the file content stored in the generated zip64 file is not encrypted any more. This mirrors the functionality of downloading a single file where the result is an unencrypted local file.
For an encrypted transfer, all of the files are encrypted in the browser before upload. This means that the server is unable to offer a zip or tar archive because it does not know how to decrypt any of the files. As encryption is end to end only the browser is able to decrypt any of the files.
This patch allows the browser to use streaming download of encrypted files and will generate a zip64 archive in the browser to stream files into. Decryption of each file happens in the browser just prior …
=> Downloading encrypted files into unencrypted zip64 container

scripts/language/README.md, scripts/language/common.php, scripts/language/convert-php-to-poeditor-json.php
This extends convert-php-to-poeditor-json.php to be able to skip language translations that are already on poeditor and only export new translations. This should help to avoid overwriting existing work on poeditor. 
Also very handy for new translations that might be added in a pull request, the script can export only terms that are in the local git checkout but not already on poeditor.
=> i18n: optional ability to filter terms to upload using existing terms

scripts/language/README.md, scripts/language/download-language-from-poeditor.sh, scripts/language/import-all-from-poeditor.sh, scripts/language/send-json-translations-for-language-to-poeditor.sh
This moves a bash function to a script so it can be used to generate the existing term list for convert-php-to-poeditor-json.php for use with new pull requests.
=> i18n: break out language download script so that convert-php-to-poeditor-json.php can use it

scripts/language/README.md, scripts/language/send-json-translations-for-language-to-poeditor.sh
I think it makes it simpler to create the new terms via the API first.
=> i18n: add new terms before trying to update translations

docs/v2.0/i18n/index.md, scripts/language/send-newterms-json-to-poeditor.sh
This avoids needing to switch to the browser to complete the newterms export.
=> i18n: new command line to upload newterms to poeditor

classes/utils/Archiver.class.php, classes/utils/GUI.class.php
Silence warnings in the logs, possibly from random requests over the Internet.  
(Each commit contains the full log message.)
=> PHP Notice Undefined variable/index

docs/v2.0/install/index.md, scripts/client/filesender.py
This was reported in issue https://github.com/filesender/filesender/issues/844. This PR tries to give more information about an import failure for two libraries that might need to be installed by pip or through platform packages.
=> filesender.py: a more friendly message if deps are not installed

www/index.php
The page header template is not printed to the user if an exception is thrown in the Auth or Security functions before it. This results in a "plain text" error message being printed (see below).
This pull request stores the exception in a variable and re-throws it after the page header is printed.
I was able to replicate this by:
1. Creating a new voucher
2. Modify the expiry date in the database to be in the past
3. Try and load the voucher link.
You will get a `GuestExpiredException`  from `Auth::isAuthenticated()`.
=> Always show page header when an exception is thrown

classes/rest/endpoints/RestEndpointUser.class.php
The GET method should not be being used here. If it is somehow then maybe we should just return no data and allow the show to go on. If frequent recipients returns nothing it is not ideal but it should probably not stop everything.
=> make this error soft, no need to stop everything

classes/data/Transfer.class.php
Add recipient token to "recipient added to transfer" log entries so that it is possible to link token related exception to transfer data using logs only. Use case is when somebody use a very old download link (after audit expiration) or one to a deleted transfer. In such case log tells about a "recipient not found" along with used token, but we are not able to get anymore info as the data isn't in the database anymore, so when the user contact the hotline we are unable to tell her/him whether she/he was too late, or if the transfer owner deleted it ... This new log line format ties the recipient id and token in the logs so data aggregation becomes possible0
=> Add info to help failure investigations

www/js/upload_page.js
Just noticed some problems with auto-resume while looking into adding file integrity checks to completeFile() in StorageFilesystemChunked.class.php
This patch makes it so:
- Multiple auto-resumes are not scheduled  
- The auto-resume countdown does not go below zero (which is a result of multiple auto-resumes being scheduled)
- Use `clearInterval()` instead of `clearTimeout()` to stop the countdown since it's started with `setInterval()`
I've ported this patch from other work, so have not tested it further than copy pasting the appropriate lines into this branch :)
=> Stop auto-resume from scheduling multiple times

classes/utils/ApplicationMail.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
Fixes #871 by making this a deployer choice, not a code decision (meaning we don't have to agree on the content of the additional headers). Though I'm not sure how you'd approach that (e.g. I'd default to an empty `array()`, not `false`, but `include/ConfigDefaults.php` had no such examples, etc.) and whether the proposed code/documentation suffices.  
My own config looks like this, though that may need some more tuning, depending on the brokenness of some mail systems:
```php
$config['email_headers'] = [
'Auto-Submitted' => 'auto-generated',
'X-Auto-Response-Suppress' => 'All'
];
```
=> Add configurable email headers

templates/admin_page.php
This should fix the issue https://github.com/filesender/filesender/issues/889 which mentions that table headers to not work in the admin/transfers subpage.
=> ui: allow clicking headers in admin/transfers page

language/en_AU/lang.php, templates/upload_page.php, www/css/default.css, www/js/upload_page.js
Allow the user to go back to user selected password when they currently have a generated password on the upload page. Generated passwords are treated slightly differently to user entered passwords as the generated ones are more likely to use the full entropy of each byte. This can have an impact when password hashing is used on user entered passwords.
To get around the user modifying a generated password they are set to read only. To go back to a user entered password the selection has become a checkbox with the generation of new passwords moved to a second button which is only available when generated passwords are used. I think retaining the generate button is good because the user might feel better about the appearance of some passwords over others.
This is related to …
=> ui: allow going back from generated to user selected password

classes/data/Transfer.class.php, docs/v2.0/admin/configuration/index.md, language/en_AU/lang.php, templates/transfers_table.php, www/css/default.css, www/js/transfers_table.js
This is a new option `allow_transfer_expiry_date_extension_admin` which works much like `allow_transfer_expiry_date_extension` but is only in effect if you are an admin user. This allows you to set a different schedule for admins to be able to extend expire times without needing to allow normal users to be able to perform this task as well.
This should work in the admin/transfers page as well as in the my transfers page for an admin. The former being the more interesting option allowing an admin to extend the lifetime of a selected transfer.
This is for issue https://github.com/filesender/filesender/issues/875
=> ui: new option to allow admin to extend expire time on transfer

CONTRIBUTE.md
Update contributing graph to show all commits from the first entry in this repository. It used to be capped at 2015.
=> docs: Fix link to github contributor graph

templates/upload_page.php
If a guest can not go to the my transfers page then there isn't much point in offering it.
=> bootstrap: no my transfers button for all guests

www/js/pbkdf2dialog.js
This may manifest elsewhere but I have been able to trigger it more frequently in safari on m1 silicon. The pbkdf2 process on that device is fast which can lead to hashing completing at around the same time as the dialog appears. I have tried hooking into the onshown() for the dialog but it may be that safari just doesn't like the event ordering here. The dialog goes away if there is a 100 or 1000ms delay for the timer based closing.
=> bootstrap ui: safari pbkdf2 dialog race

www/js/ui.js, www/js/upload_page.js
I have not migrated code widely as yet to help merging this into the main tree at some stage.
=> bootstrap: a new method to clean up the get a slicer process

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/terasender/terasender.js, www/js/upload_page.js
In particular there was a setting to `Math.max(Math.round(twc/2),3)` if encryption was enabled. I do not think this is still a valid thing to do with multi cpu core machines which may handle encrypting multiple chunks more readily than before. In any case these clamps should be done via configuration settings so they are no surprise to the system admin and an explicit policy choice.
There is a new `terasender_worker_max_count` config which sets the max for terasender workers explicitly (was always 30 but done in the code hard wired in places).
=> bootstrap: improved handing of terasender_worker_count and its max setting

www/js/upload_page.js
Turning on encryption might make larger files invalid to upload. This refreshes that part of the UI code and has some other small cleanups in it too.
=> clean up handling error message when encryption makes some files invalid to upload

templates/upload_page.php
The guest_can_only_send_to_creator was set to be ok if we are not dealing with a guest but I think it is clearer in the main php body to use a new `$show_get_a_link_or_email_choice` to explicitly choose if that element is made. It is only not made if you are a guest and you can only send to the user who invited you.
=> bootstrap: make that an explicit option rather than relying on the guest_can_only_send_to_creator variable

templates/upload_page.php
Trying to loosen these restrictions bumps up against some other assumptions in the code. This should be closer to the current release where the person inviting the guest can choose one of
```
only send to me
must get a link
must send to emails
```
and the later two can not be changed by the guest.
=> bootstrap: default choice is more restrictive, this is closer to current dev

classes/storage/StorageFilesystem.class.php, templates/upload_page.php, www/js/upload_page.js
When you are prompted about a previous failed transfer and elect to load the transfer to complete it you are not able to change any of the transfer options. Instead of showing the second page with options that are not able to be changed I think it makes more sense to just skip stage2 and start sending the files right from stage1.
=> bootstrap: skip stage2 for a transfer created with re-add

www/js/transfer.js, www/js/upload_page.js
Scenario:
* start an upload with get a link = true and then navigate away from the page.
* go back to upload page and see the dialog mentioning the previous failed upload
* elect to continue the upload
* re-add the files again
* click send and finish the transfer
* Previously the link was not shown on the completion dialog. 
This is a bug which is also present in the current release of filesender.
=> bootstrap: show the download link when re-adding files and gal

templates/upload_page.php
This is to handle the case where an admin has set get_a_link to not available (ie, they wish to force a choice for the user). In this case the default of true or false will select what elements are shown in stage2 but the choice of (get a link or send by email) is not presented to the user. It is as if there is only one choice. It doesn't seem to add value to show the choice if the user is unable to make it.
```
$config['transfer_options'] = array(
...
'get_a_link' => array(
'available' => false,
'advanced' => false,
'default' => true
),
...
);
```
=> bootstrap: if get a link is not to be available then hide the choice

docker/Dockerfile, docker/Dockerfile.bootstrap, docker/README.md, docker/assets/etc/nginx/fastcgi_params, docker/assets/etc/nginx/nginx.conf, docker/assets/etc/nginx/sites-available/default, docker/assets/etc/nginx/sites-enabled/default, docker/assets/etc/service/nginx/run, docker/assets/etc/service/php-fpm/run, docker/assets/usr/local/bin/docker-php-ext-configure, docker/assets/usr/local/bin/docker-php-ext-install, docker/assets/usr/local/etc/php/conf.d/opcache.ini, docker/assets/usr/local/lib/php-fpm-env/PhpFpmEnvironment.php, docker/assets/usr/local/sbin/php-fpm-env, docker/assets/usr/local/sbin/runsvdir-init
Added: Dockerfile  and releated files for a docker image for filesender installs with simplesamlphp.
Fixes: #929
This is an opinionated Docker image, using filesender, simplesamlphp and php-fpm. It makes some assumptions that work nicely in a Kubernetes world, and is based on the work of [ualibraries](https://github.com/ualibraries/filesender-phpfpm) with some influences of [bitnami](https://github.com/bitnami/) as well.
Configuration of this image is done by filling the various /config volumes with real-life configurations.
Feel free to contact me for questions, remarks, etc, or place comments in the PR.
=> Add Docker image for FileSender with SimpleSamlPHP

classes/data/DBObject.class.php, classes/data/Guest.class.php, classes/exceptions/GuestExceptions.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/guests_table.php, templates/transfers_table.php, www/js/client.js, www/js/guests_table.js, www/js/ui.js
This abstracts some of the "expires" functionality from transfers to dbobject on the server side and filesender.ui on the client side. The new abstracted code is used to allow the admin/guests page to extend the expire time for a guest. This relates to https://github.com/filesender/filesender/issues/966.
=> admin: allow guest expires to be extended

classes/data/Guest.class.php, classes/data/User.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, classes/rest/endpoints/RestEndpointUser.class.php, language/en_AU/lang.php, templates/admin_users_section.php, www/js/admin_users.js, www/js/client.js
A new button is now available in admin/users when you search for a user by user ID. This button allows you to overwrite the guest expire days for newly created guests for specific users. The same button can also be used (as described in the dialog) to set 0 to remove the setting for the guest.
When I user has a higher default guest expire days then new guests that they create will have an expire time different to the system default. This allows specific privileged users to be able to make guests that last longer than the system normally allows.
This relates to https://github.com/filesender/filesender/issues/966.
=> admin: allow a guest expires time to be set on a per user basis

classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, templates/transfers_table.php, www/js/transfers_table.js
Now that there is a common use version of this code in DBObject and ui.js the old version of this code should really be removed from use in Transfer management. This has both Guest and Transfer use the same new code that is based on and extended from the old code. Having two code paths around is a bad idea for maintenance.
=> move transfers to use the new shared code for expire updates

classes/rest/endpoints/RestEndpointFile.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/crypter/crypto_app.js, www/js/terasender/terasender_worker.js
This is a huge bottleneck. Some empirical data to show just how large the impact is. The upload speed would ramp up slowly during an encrypted upload on a local connection and for large files (4gb) might get to 85mb/s at the end. Without the base64 encoding and decoding the speed goes over 200mb/s on upload. I am running with 12 terasender workers and 4mb chunk size for these numbers.
I have made a temporary config setting to allow enabling base64 for both local speed testing but mainly for backward compatibility if there are issues discovered in some installations and we need to support base64 on the PUT contents for some reason.
=> core: encryption: do not base64 encrypted data during upload

classes/data/Recipient.class.php
Cast anonymous recipient identity to string to avoid it being rendered as "1" in templates
=> Cast anonymous recipient identity to string

includes/ConfigDefaults.php, language/en_AU/lang.php, www/js/transfer.js, www/js/upload_page.js
This relates to https://github.com/filesender/filesender/issues/1032. The regex has to change to not explicitly match the end of string so we can see where the matching has failed during test(). The UI now presents to the user where the failure has started to happen to help them resolve the issue. I also extended the regex a little to allow quotes. 
Without `\p{P}` in the valid file names the single quote was considered invalid. Removing the added '\\p{P}' is handy for testing as it will give a known fail case.
=> ui: feedback for bad characters in file names during adding

classes/data/Transfer.class.php, classes/data/User.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, templates/transfers_table.php
This is to address https://github.com/filesender/filesender/issues/1000. I have also looked at the emails that are sent though it is possible that this PR does not catch all "guest emails" that might also trigger an email to the user who invited the guest.
Because this test is needed in multiple locations I have created a new `$guest_transfer_shown_to_user_who_invited_guest` column in the Transfers table. This allows SQL to check and also the code to directly check if an email should be sent.
The `$guest_transfer_shown_to_user_who_invited_guest` is set in RestEndpointTransfer.class.php when a transfer is created and remains the same thereafter. The default is to show transfers to the user who owns them. Guest transfers are owned by the user who created them. So this whole config option is …
=> Update to user_can_only_view_guest_transfers_shared_with_them for wider scope

classes/utils/Utilities.class.php
The regex lost the trailing '$' in https://github.com/filesender/filesender/pull/1033 so it is added on the server side test again here. We don't really care where the file name fails that regex on the server we just want complete match or failure.
=> the dollar was removed from the default, add it here

docs/v2.0/admin/configuration/index.md
Update documentation in the section about auth_remote_applications with the example presented in issue #1040
=> fix documentation section about auth_remote_applications config ref #1040

classes/utils/Config.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/upload_page.php, www/css/default.css, www/filesender-config.js.php, www/js/upload_page.js
This relates to a recommendation in 20100861-M1 for longer pass phrases.
=> security: allow long passphrases to have relaxed contents restrictions

config-templates/apache/filesender.conf, docs/v2.0/install/index.md, lib/README.md, lib/vendor/owasp/csrf-protector-php/libs/csrf/csrfprotector.php
The SimpleSAMLphp part of the installation did not take advantage of some of the options for SimpleSAMLphp for the default configuration settings. This introduces a recommendation to use SimpleSAMLphp configuration options that will result in SameSite=Strict and HttpOnly being used to protect the auth cookies.
The OWASP CSRF file was updated to use SameSite=Strict but can not use HttpOnly as the cookie must be explicitly accessed from javascript.
The apache overrides recommendations have also been updated if that is the method an admin wishes to add these cookie options to their environment.
This relates to 20100861-L1 and 20100861-N1
=> cookie: updates to default config and install guide

classes/auth/Auth.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
Setting auth_sp_force_session_start_first to true will cause session_start to happen before auth. This might allow for the php session cookie to be sent to the client if the auth sp method is doing something that might make session_start behave differently.
=> cookies: maybe bring forward session_start for sp auth

classes/utils/Security.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
This can be disabled by setting the config to 0 if the web server itself is the desired way to set the parameter.
=> headers: set HSTS to 2 years by default

classes/auth/Auth.class.php, classes/constants/LogEventTypes.class.php, classes/data/AuditLog.class.php, classes/data/Transfer.class.php, classes/data/User.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/rest/endpoints/RestEndpointUser.class.php, templates/admin_users_section.php, templates/download_page.php, templates/transfers_table.php, www/js/admin_users.js, www/js/client.js, www/js/crypter/crypto_app.js, www/js/crypter/streamsaver_sink.js, www/js/download_page.js, www/js/transfers_table.js
Because decryption is done client side it is hard to install brute force mitigation because the client code can always be modified. This code sends information to the server when decryption has failed. If an abusive user has not taken other measures then the server will rack up many failed decrypt messages for that user and they can be seen by the system admin for whatever action might be desired.
There is a new button on the admin/users page to allow searching for users with most_failed_decryptions. Guests or not logged in users are also shown but with less information.
This relates to 20100861-N2.
=> crypto: log decrypt failures to allow for abuse detection

classes/avprograms/AVProgram.class.php, classes/avprograms/AVProgramMIME.class.php, classes/data/constants/DBConstantAVProgram.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md
This allows a passing list to be used to explicitly validate uploaded content to be certain MIME types. This may be useful if the server is used to exchange only some mime types to warn users that the file might not be what is expected.
=> avprograms: new option to check MIME type 

docs/v2.0/admin/configuration/index.md
Since FileSender 2.9 (released Oct 5, 2019) encryption_random_password_version_new_files has been 2 which is v2019_generated_password_that_is_full_256bit (from crypto_app.js). This password handling has many advantages such as generating a string that contains the entropy that the system desires and also being a password format known to be generated this way it may skip password hashing.
As the encryption_generated_password_length only applies to v2018_text_password I am deprecating it here. Unless you are setting encryption_random_password_version_new_files to 1 explicitly and then looking to set the max length this setting would have no effect. It is strongly recommended to use the default encryption_random_password_version_new_files=2 (or leaving that setting unset to get the default) …
=> docs: update that encryption_generated_password_length is deprecated

scripts/dev/www-lib-update/update-library-versions-from-node_modules.php, templates/download_page.php
Some of the selectors were too general and were getting the avresults files entries instead of the ones from the table as expected.
=> avprograms: allow download again

www/js/pbkdf2dialog.js, www/js/terasender/terasender.js
When terasender_worker sends some data back we know that at least one web worker has started uploading and so we can go ahead and dismiss the pbkdf2 informational window if it is up.
=> pbkdf2: dismiss the pbkdf2 dialog on a progress message from terasender

www/js/terasender/terasender.js, www/js/upload_page.js
Close the pbkdf2 dialog before opening the success dialog.
=> pbkdf2: force the dialog to close on really small fast xfers

classes/storage/StorageFilesystem.class.php
fix Chunked storage free space check, while not breaking standard filesystem, as chunked uses a file as a directory that does not exist at time of check so we go one dir up
=> fix Chunked storage free space check, while not breaking standard class

classes/avprograms/AVProgram.class.php, classes/avprograms/AVProgramEncrypted.class.php, classes/data/constants/DBConstantAVProgram.class.php, scripts/task/execute-av-program-on-files.php
For encrypted content to avoid it being returned by File::findFilesWithoutAVResults().
This will avoid encrypted files being returned more than once for inspection.
=> avprograms: record a passing result by the encrypted tester

templates/upload_page.php, www/js/upload_page.js
When generate password is on the UI elements that relate to password validation are now explicitly hidden and are reenabled and tested when genereate is turned off.
=> upload page explicitly hide ui messages when generating password

classes/storage/StorageCloudS3.class.php
This relates to https://github.com/filesender/filesender/issues/1054
=> s3 storage, default to filesender chunk size equals stream chunk size

classes/exceptions/FileExceptions.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/translate_email_page.php, www/js/transfer.js
Rather than throwing an exception on unexpected mime type it will be simply coerced to a binary data type.
The optional new configuration settings can be left at the default but provide handy knobs to allow quick tweaking if desired.
=> improved validation on some input

classes/exceptions/GuestExceptions.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, classes/utils/Config.class.php, classes/utils/GUI.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/admin_page.php, templates/menu.php
This does not delete existing guests. The default for the new option is to allow guests. Existing systems need not do anything.
A admin may elect to not allow guests by setting in config.php
```
$config['guest_support_enabled'] = false;
```
With this setting in place FileSender will 
* remove the menu item to access the guests page
* fail to load the guests page if explicitly attempted
* fail to create a new guest if explicitly attempted via the REST api.
This relates to https://github.com/filesender/filesender/issues/1123
=> ability to disable guest system

classes/constants/TransferOptions.class.php, classes/data/Transfer.class.php, classes/utils/GUI.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/download_page.php, templates/logon_page.php, www/css/default.css, www/js/download_page.js
A new transfer option (false by default) to allow a user to force the downloading user to authenticate with the FileSender server in order to download files. This might be handy when a user knows that the recipients are all users of the same system for example, they are at the same university or organization.
This relates to https://github.com/filesender/filesender/issues/1066.
=> A new option to only allow downloads from authenticated users.

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/download.php
The logging of downloads is no longer subjected to a IP address filter. This will allow many downloads from the same IPv4 nat address to all be counted.
The throttling was initially introduced because of too much log activity. As such I have turned off this filtering as a configuration option (filtering off by default in 2.30). If this causes problems a single config directive will revert to previous behaviour. Setting the config option logs_limit_messages_from_same_ip_address to `true` will revert to previous behaviour of limiting the logs for given IP addresses.
My plan is to remove the logs_limit_messages_from_same_ip_address and the option to filter in a subsequent release once we know that not performing filtering is not causing a major issue.
This relates to …
=> download counter: count every time

classes/auth/Auth.class.php, classes/data/Guest.class.php, classes/data/User.class.php, classes/exceptions/RestExceptions.class.php, classes/rest/endpoints/RestEndpointPrincipal.class.php, classes/rest/endpoints/RestEndpointUser.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/service_aup_page.php, www/css/default.css, www/index.php, www/js/client.js, www/js/service_aup_page.js
The default setting `(service_aup_min_required_version = 0)` for this will have no change relative to previous versions. If you want to use it you need to enable it.
If you set in your config.php
```
$config['service_aup_min_required_version'] = 0;
```
Then users and guests will be asked to accept a service wide AUP the next time they load a page. Once they accept version 1 then they will not be asked again to accept the service wide AUP while min_required_version remains at 1.
If you then update `$config['service_aup_min_required_version'] = 2;` then any user or guest who has either not accepted the service AUP or only accepted version 1 will, on the next page load, be shown the service AUP for v2 and asked to accept it. This goes on allowing alterations of service AUP as desired (v3, …
=> Add a service wide AUP with basic versioning

includes/ConfigDefaults.php, www/js/transfer.js
If max_transfer_files=0 then do not enforce any maximum amount of files for a transfer. It turns out the server side already supported this if max_transfer_files=0 was in the config so it is client side only.
This addresses https://github.com/filesender/filesender/issues/359.
=> allow no max_transfer_files if admin desires it

includes/ConfigDefaults.php
The default in the configdefaults was updated by mistake in https://github.com/filesender/filesender/pull/1136/files
=> make the default in the config how it was

docs/_includes/menu.html, docs/v2.0/dev/contributing/index.md
This should help new contributors navigate the development/master split.
=> docs: add contributing info

classes/rest/endpoints/RestEndpointFile.class.php, classes/utils/TestSuiteSupport.class.php, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/crypter/crypto_app.js, www/js/terasender/terasender.js, www/js/terasender/terasender_worker.js, www/js/transfer.js, www/js/ui.js
The start of a new TeraReceiver mode. Note the limitations of this initial version below. Work will continue on TeraReceiver to allow multiple workers and move encryption to the workers. TeraReceiver is disabled by default at the moment It can be enabled using 
```
$config['terareceiver_enabled'] = true;
```
The current implementation is limited to one web worker being active, so only one chunk downloaded at a time. Traditionally encrypted downloads have been performed using nested callbacks in crypto_app.js. The code path is retained and a new TeraReceiver mode added which uses the same TeraSender manager/worker code updated to allow chunk downloads. 
The main differences begin around the code that calls filesender.terasender.startReceiver() which passes control of the download over to …
=> core: new terareceiver mode for encrypted downloads

classes/constants/TransferOptions.class.php, classes/data/Transfer.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/storage/StorageCloudS3.class.php, docs/v2.0/admin/configuration/index.md, docs/v2.0/cloud/index.md, includes/ConfigDefaults.php, scripts/cloud/s3/test-s3-simple.php
This provides the option that was suggested in https://github.com/filesender/filesender/pull/1114 to allow all files to be stored in a single bucket. The code is updated to store the current setting for each Transfer as it is created. This way the setting in the config.php can change and existing files can still be downloaded. This allows migration to using buckets or changing the bucket name while the existing files remain available. Conversely you can remove the bucket name and revert to the original style while existing files remain available.
The option is stored in the Rest Transfer class during creation of the Transfer. The option is sought in the Storage class if it is set for the Transfer and used if found. The Rest Transfer class does not return the bucket name in the `cast()` as …
=> clouds3: option to store everything in a single bucket

classes/utils/Config.class.php
The crypto_crypt_name is overridden in the `setCipherAlgorithm` function based on the value of the key version (0,1,2,3) being used. For new uploads the key version is taken from the encryption_key_version_new_files configuration setting. You will likely want 3.
When crypto is performed in the browser the `setCipherAlgorithm` is called to set the crypto_crypt_name correctly. 
https://github.com/filesender/filesender/blob/25fb8150fd29d2a93bad6b05695d2553022931b4/www/js/crypter/crypto_app.js#L447
However the filesender-config.js.php was showing the value from config.php for crypto_crypt_name instead of the overridden value. This should not have effected things as the crypto is initialized using the key version instead of using the crypto_crypt_name directly.
=> update metadata that is shared in filesender-config.js.php

classes/utils/Config.class.php, docs/v2.0/admin/configuration/index.md
This adds some docs for that config setting and makes the crypto_crypt_name explicit setting cover the entire new key version range.
=> some docs for crypto_crypt_name and update to fully set crypto_crypt_name from key version

language/en_AU/lang.php, templates/upload_page.php, www/css/default.css, www/js/ui.js, www/js/upload_page.js
This is based on the current upload speed and amount of data that remains to upload. If the upload speed is stable then the estimate should be _reasonable_. The display of an ETA has a built in 2 second delay to allow some time for the speed to work itself out. The ETA display will also only refresh every 2 seconds to avoid it flickering around too much while the user is trying to read it.
The updating is handled in a new class `nonBusyUpdater` which can be used elsewhere when a once per X milliseconds only update is desired.
This could be expanded to retain a fixed size set of ETA values and perhaps show the variance to the user in a simple way like green, orange, or red if the estimate is varying widely.
=> upload: show a very basic ETA

www/js/upload_page.js
If the expire element on the upload page is completely erased then things will go wrong when the upload starts. This prevents that by reverting to the original value when the date picker is deselected if it is empty.
This relates to https://github.com/filesender/filesender/issues/1149.
=> ui: prevent upload page expires from becoming an empty string

classes/utils/Utilities.class.php, includes/init/init_web.php
This isn't comprehensive by any means, but to get FileSender to run under PHP8 we needed to make these changes.
No behaviour should be changed, as it's just a formatting change, and dead code removal.
=> Fixes to allow running under PHP8

unittests/config_tests_filesender.xml, unittests/selenium/SeleniumTest.php, unittests/selenium/tests/HeaderMenuTest.php, unittests/selenium/tests/InvalidExtensionsTest.php, unittests/selenium/tests/LanguageSelectTest.php, unittests/selenium/tests/MaxFilesTest.php, unittests/selenium/tests/MaxUploadSizeTest.php, unittests/selenium/tests/TemplatingTest.php
Updates for the remaining (LanguageSelectTest.php, HeaderMenuTest.php, MaxFilesTest.php, InvalidExtensionsTest.php, MaxUploadSizeTest.php, TemplatingTest.php) test cases in the bootstrap (filesender 3.x) series.
=> dev3, m2b: update selenium tests for development3

unittests/config_tests_filesender.xml
While testing m2b tests I disabled the existing m2a for a shorter run of the cloud selenium tests. This enables both m2a and m2b during a CI execution.
=> dev3: run tests from both m2a and m2b

www/js/admin_transfers.js
It couldn't search email addresses including the '+' sign in admin_transfers.
I fix it using encodeURIComponent().
=> url-encode email address in admin_transfers

classes/data/Guest.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, classes/utils/Config.class.php, classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/guests_page.js
This makes the range for a new guest expire time more explicit (with a clamp()). It introduces a new `min_guest_days_valid` config setting (default 1) which allows the minimum number of days a new guest invitation will be valid. It also allows for selecting dates that are less than the default expire time. 
This relates to https://github.com/filesender/filesender/issues/1193
=> guest expires: allow selection below the default expire

classes/auth/AuthSPSaml.class.php, classes/auth/AuthSPShibboleth.class.php, classes/utils/Env.class.php
This is a slight update to https://github.com/filesender/filesender/pull/1208 which creates a new Env class which offers it's own `getenv` method. By abstracting things into a class we can document why `Env::getenv()` exists in the code. 
This should also lead new readers of the code to the method to see why it is there rather than potential updates from `getenv()['key']` to `getenv('key')` in the future in places where it will make the code fail for some users.
=> New Env class to allow getenv() to do more in some cases

classes/auth/Auth.class.php, classes/utils/GUI.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
Setting the cookie domain to '' (the new default) will force the browser to use the most restrictive cookie domain where the cookie was served from. This is an improvement over just using filesender.example.com becuase that explicit domain would allow hacker.filesender.example.com and other subdomains to also get access to the cookie.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#domaindomain-value
This has become an option in config.php to allow sites to use filesender.example.com if they explicitly want to allow some subdomains.
This is 5.1.9 of the may2022 report.
=> Cookies: override the cookie_domain with settings from config.php

templates/upload_page.php, www/js/upload_page.js
As reported in https://github.com/filesender/filesender/issues/1223 the functionality is different between adding a directory by drag and drop and adding by "select a directory". Specifically the drag and drop would retain the relative paths of the files in the directories added and the "select a directory" would only store the file names.
This patch allows the relative paths to be stored where the browser supports it for "select a directory" mode. This will also allow the files to be downloaded in a zip containing the paths.
=> allow select directory button to store paths too

scripts/dev/www-lib-update/package.json, scripts/dev/www-lib-update/show-existing-versions.php
This updates the bootstrap metadata to 5.1.3 and bumps bootbox version a minor release too. The www/lib files are already updated during https://github.com/filesender/filesender/pull/1252
This relates to https://github.com/filesender/filesender/pull/1229
=> dev3: update bootstrap and bootbox metadata

classes/autoload.php, classes/data/RateLimitHistory.class.php, classes/data/TranslatableEmail.class.php, classes/exceptions/RateLimitExceptions.class.php, classes/rest/endpoints/RestEndpointGuest.class.php, classes/rest/endpoints/RestEndpointRecipient.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/utils/ApplicationMail.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, www/download.php
Some actions have hard or soft limits that can be applied. For example, actions that result in sending an email may have a soft limit that will perform the action but not send an email after the nominated number of actions is performed per time period. This allows for the system to prevent a nefarious guest from sending too many emails. The database table ratelimithistorys is used to track the information needed for this option. The time period for actions performed used for the initial implementation is 24 hours.
For example, with the right setting you can not create more than 200 guests in a 24 hour block of time. There are two types of limits, hard and soft. A hard limit will be checked before performing an action and if the limit is already reached the action will not be performed. …
=> Rate Limits: new hard and soft rate limits for some actions

classes/auth/AuthGuest.class.php, classes/data/Transfer.class.php, classes/data/TranslatableEmail.class.php, classes/rest/endpoints/RestEndpointFile.class.php, classes/utils/GUI.class.php, classes/utils/Security.class.php, templates/header.php, templates/menu.php, templates/pagemenuitem.php, templates/vidattr.php, www/js/ui.js, www/js/upload_page.js
If a transfer was created by a guest then make sure the 'vid' is sent and that it matches the guest who created the transfer.
And `testRoundTripToken()` will also be forced on to make sure that the roundtriptoken set in the web session is sent in the chunk upload RestEndpointFile/PUT and matches the expected value.
=> Stronger checks on guest vid, round trip token checks are forced on for guest uploads

docs/v2.0/admin/configuration/index.md
Further work on #939, adding in documentation for:
* client_ip_key
* cloud_s3_region
* cloud_s3_version
* cloud_s3_endpoint
* cloud_s3_key
* cloud_s3_secret
* cloud_s3_use_path_style_endpoint
* disable_directory_upload
* directory_upload_button_enabled
=> Adding documentation for 9 options

classes/utils/GUI.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
This PR moves the fixed page lists that are allowed for unlogged in, guest, user, and admin to configuration settings with defaults provided. Note that the user_page is now handled by removing the user page if there are no configured settings for that page.
The allowed pages builds from allow_pages_core adding guest and user pages if the principal meets those requirements.
The new default is to allow unauthenticated users to view the privacy page so they can see information from there without needing to log in to the system.
This relates to https://github.com/filesender/filesender/issues/1261.
=> GUI allowed pages update to move these settings to the config

classes/utils/Logger.class.php, www/download.php, www/js/crypter/crypto_app.js, www/js/crypter/streamsaver_sink.js, www/js/download_page.js, www/js/terasender/terasender.js, www/js/terasender/terasender_worker.js
When multiple files are selected this PR will delay "file downloaded" to the end and send a single email will the names of all the files that were downloaded by a user.
This should fix https://github.com/filesender/filesender/issues/1220.
=> Only send a single email with all downloaded files listed after encrypted download to zip

scripts/upgrade/database.php
Because the text character set is taken from containing objects I have put a warning here if the value is not the expected one. This allows an admin to know that they might like to change the utf8 to utf8mb4 at the correct level (table or database).
There is also an option which is shown in the error message itself to allow the script to be run ignoring this issue. This allows an admin to continue to update FileSender as they may have done before and schedule a character set change at their leisure rather than right now in order to update.
This is related to https://github.com/filesender/filesender/issues/1285.
=> db: mariadb test the TEXT CHARACTER SET for utf8mb4 value

www/js/transfer.js, www/js/upload_page.js
I see the previous fix appeared to revert the value on the upload page but after the new transfer was uploaded the expire time was not set correctly. This update should fix that.
This relates to https://github.com/filesender/filesender/issues/1149
=> upload page: convert blank expire time to original value

scripts/language/common.php, scripts/language/convert-poeditor-json-to-php.php, scripts/language/import-translation-for-language.php
Support for part of this PR was done in poeditor directly. There is no easy way to capture that update inside the PR. The changes include tagging terms on poeditor that should be placed into a file such as `about_text.html.php` with the `html` context. Some other terms had the email context added to them in order to be split into the email file.
By relying on the context from poeditor the spliiting out of email and html single file translations happens automatically and there is now support for two translations on poeditor to have the exact same term but different contexts. This is the case for `download_complete` which has both an email and plain translation.
From the en_au translation 5  terms have both an email and plain translations and have been added to poeditor with the correct …
=> i18n: import script update to better respect the context of a translation

classes/data/File.class.php, classes/data/FileCollection.class.php, classes/data/Transfer.class.php
The File.id was a medium which was implemented as a 24 bit number by the mariadb translation layer. This can overflow after 8 million files so this PR updates that and some other identifiers to explicitly be "big" integers which should be 64 bit and not cause any issues for "a while".
I have used the database.php migration script on both mariadb and postgresql though installations will want to test the update to their satisfaction.
This relates to https://github.com/filesender/filesender/issues/1293.
=> Make files, filecollections, and transfer ids bigints.

classes/data/Guest.class.php, classes/data/Transfer.class.php
As the user id is already a big int it makes sense that guest id should also be a big int.
=> db: make guest id a big int too

classes/rest/endpoints/RestEndpointGuest.class.php, docs/v2.0/admin/configuration/index.md, www/js/guests_table.js, www/js/ui.js
This enables the allow_guest_expiry_date_extension option to enable a regular system user to be able to extend the expire time for one of their guest vouchers. With this setting configured an expand icon appears in the actions on the guests page for a user.
This will help when a user sends a voucher to invite a guest and receives an out of office reply from the guest's email address. The user can then come back and extend the expires time for that guest voucher to allow the guest to use it when they return to the office.
For example, to allow 10 day extensions without a limit the below can be used:
```
$config['allow_guest_expiry_date_extension'] = array(10,true);
```
=> guests: config option to allow a guest to extend voucher expire time

scripts/upgrade/database.php
As mariadb does not allow rollback for transactions over ddl statements and database.php is mostly going to do ddl maybe do not try to wrap it in a transaction for mariadb.
This relates to https://github.com/filesender/filesender/issues/1309
=> mariadb: do not try transactions on DDL heavy script

templates/admin_transfers_section.php
Sanitise email field from admin form and pass it through as a placeholder so PDO uses prepare function + improved UX and search emails in lowercase.
=> Fix possible SQL injection in admin page

classes/data/Recipient.class.php
Otherwise rendering of anonymous recipient in translations leads to a "1" being displayed. This is because Lang::tr returns an object, which will be converted to boolean true by the translation placeholder handler, which will be converted to "1" during later concatenation ...
=> Ensure identity is a string

www/download.php
Avoid php notices like
PHP Notice:  Undefined index: HTTP_X_FILESENDER_ENCRYPTED_ARCHIVE_DOWNLOAD in .../www/download.php on line 409
=> Correct undefined php index

docs/v2.0/admin/configuration/index.md
Document `auth_remote_user_enabled`
Clear up documentation for `auth_remote_user_autogenerate_secret`
Fixes #1318
=> Document auth_remote_user_enabled

classes/data/Guest.class.php, classes/data/Transfer.class.php, scripts/task/cron.php
This is in response to https://github.com/filesender/filesender/issues/1326.
Although 1326 does not mention it I added a new `--force` option to log and continue when a file delete fails. This allows for cases where the admin might have deleted some old files already. This may not be the case most of the time but if the back end is storing files somewhere that might have other forces deleting rather old files and the cron job has not run for a while then you can force the cron job to log and continue.
There is also a new --verbose option to allow some signs of life on the console if you are running it that way.
=> cron: only delete a guest when all their transfers are no longer available, allow force delete

classes/auth/Auth.class.php, classes/rest/RestServer.class.php, classes/utils/Security.class.php, classes/utils/Utilities.class.php
This is the CSRF part of https://github.com/filesender/filesender/pull/1233 with the logic moved into the always made `validateAgainstCSRF()` call.
=> security: allow remote user and app to not have to perform CSRF

classes/auth/Auth.class.php, classes/data/Recipient.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/download.php
This relates to https://github.com/filesender/filesender/issues/1314
This is mostly to be able to see which authenticated users on the same system have downloaded your "get a link" transfers. This is a little tricky as the logging system revolves around the non "get a link" work flow. In that way, each email that is added to a transfer is added to the recipients table for this transfer. Then when a user visits the download page their token uniquely identifies that guest for that transfer as a single tuple in the recipients table. That recipient tuple/object is then used by the system to log their download activity.
Rather than specialise the paths for both recipient and user to allow logging the authenticated user who is downloading, this PR adds a new tuple to the recipients table for …
=> New Option: log downloads from authenticated users as recipients

language/en_AU/lang.php, www/js/crypter/crypto_app.js
This relates to https://github.com/filesender/filesender/issues/1319
The PR allows the successful password to be offered across the individual download buttons and the archive download button. Much nicer than forcing the poor user to retype things to download 2+ files.
=> crypto-ui: when a password has worked offer it for other files on the same download page

docs/v2.0/install/index.md
The explicit versions are not needed here and could be harmful.
=> docs: debiain install allow installation of latest default php versions

classes/utils/Lang.class.php
Avoid adding en as fallback if already the default. Also "fallback" is an arrya of language codes, so loop through those to find the translation and stop on first match
=> Language default and fallback fixes

classes/utils/Lang.class.php, templates/header.php
lang: the self reference there wasnt good. Only log the id to avoid super verbose logs
lang: Consecutive entries with the same language name are avoided in the language drop down.
=> Update for a log entry in language fallback mode and cleaner language selector.

config-templates/apache/filesender.conf, docs/v2.0/install/index.md
The HSTS header is now broadly set for js and other files in the configuration template.
This relates to 4.1.8. of Computest Jan. 2, 2023 Version 1.0.
=> set HSTS in the apache template config

docs/v2.0/admin/configuration/index.md
In the new option auth_config_regex_files, this change allows one attribute to have multiple regexes, each optionally loading different config files.
=> Allow multiple regex per attribute

scripts/client/filesender.py
This Pull request covers two changes:
- Allowing chunks to retry when something goes wrong on either the client or the server.
Errors on the file-sender server or a brief interruption in internet service will currently cancel the whole transfer. 
Simply retrying the request after a delay will resolve this issue the majority of the time.
It will try up to either terasender_worker_max_chunk_retries or a user flag. 
- Adding concurrent workers to increase performance dramatically.
For this we are using a thread pool to try and improve network utilization / remove downtime between chunks.
If terasender is disabled it will revert to a single threaded chunk by chunk transfer.  
The number of workers is user configurable via the --thread argument up to the terasender_worker_count defined by the …
=> Concurency and resilience changes to filesender.py

classes/auth/SamlLogoutCheck.php, classes/utils/FileSendercsrfProtectorLogger.class.php, classes/utils/Security.class.php, templates/menu.php, www/css/default.css
Together with a callback from SimpleSAMLPhp this update allows CSRF checks on logout.
This relates to 4.1.6 of Computest Jan. 2, 2023 Version 1.0.
=> security allow csrf check before doing a saml logout

templates/logon_page.php
When a session times out while a non-upload page is open and I log back on, it takes me to the upload page instead of the originally opened page.
=> Return to original page upon session timeout

classes/utils/FeedbackMail.class.php
When task/emailfeedback.php receives a bounced email with broken Content-type field, it fails to the process. For example, the end of Content-type field is ";".
```
--------------I305M09060309060P_297316237437599
Content-Type: text/plain; charset=UTF-8;
Content-Transfer-Encoding: 8bit
```
=> PHP Notice:  Undefined offset: 1 in /opt/filesender/filesender-2.21/classes/utils/FeedbackMail.class.php on line 151
=> Ignore error if a bounced email with broken Content-type field

classes/utils/FeedbackMail.class.php
This allows erroneous spaces at the end of the content-type to be handled.
=> email handling: improved handling for content-type with errors in it

templates/translate_email_page.php, www/css/default.css
When there are many available languages(default), Translate_email page display breaks through to the right.
=> Display scroll bar on Translate_email page

templates/transfers_table.php
When no transfer options are selected, "none" is not displayed on Transfers page.
=> Display "none" when no options on Transfers page

templates/admin_transfers_section.php
This is an update to https://github.com/filesender/filesender/pull/1425 
Thanks @makinog3 for the above PR which inspired me to tinker on these updates!
It allows a fake `$total_count` if the offset is zero and there are no real selectors in the SQL query. This is the case for when you first view the admin / transfers page and the totals are likely to be large, somewhat uninteresting, and maybe slow (seq scan on the transfers table).
I have also limited the scope of the `for` clause to only consider pages near the current offset rather than from 0 to  `$total_count`.
=> admin transfers page: db paging update

www/js/crypter/crypto_common.js, www/js/zip64handler.js
When generating a ZIP archive on the client side(JS), file names containing multibyte characters are incorrectly handled.
=> Zip archive for file names containing multibyte characters

lib/vendor/maennchen/zipstream-php/.gitignore, lib/vendor/maennchen/zipstream-php/.php-cs-fixer.dist.php, lib/vendor/maennchen/zipstream-php/README.md, lib/vendor/maennchen/zipstream-php/composer.json, lib/vendor/maennchen/zipstream-php/phpunit.xml.dist, lib/vendor/maennchen/zipstream-php/psalm.xml, lib/vendor/maennchen/zipstream-php/src/Bigint.php, lib/vendor/maennchen/zipstream-php/src/DeflateStream.php, lib/vendor/maennchen/zipstream-php/src/Exception.php, lib/vendor/maennchen/zipstream-php/src/Exception/EncodingException.php, lib/vendor/maennchen/zipstream-php/src/Exception/FileNotFoundException.php, lib/vendor/maennchen/zipstream-php/src/Exception/FileNotReadableException.php, lib/vendor/maennchen/zipstream-php/src/Exception/IncompatibleOptionsException.php, lib/vendor/maennchen/zipstream-php/src/Exception/OverflowException.php, lib/vendor/maennchen/zipstream-php/src/Exception/StreamNotReadableException.php, lib/vendor/maennchen/zipstream-php/src/File.php, lib/vendor/maennchen/zipstream-php/src/Option/Archive.php, lib/vendor/maennchen/zipstream-php/src/Option/File.php, lib/vendor/maennchen/zipstream-php/src/Option/Method.php, lib/vendor/maennchen/zipstream-php/src/Option/Version.php, lib/vendor/maennchen/zipstream-php/src/Stream.php, lib/vendor/maennchen/zipstream-php/src/ZipStream.php, lib/vendor/maennchen/zipstream-php/test/BigintTest.php, lib/vendor/maennchen/zipstream-php/test/ZipStreamTest.php, lib/vendor/maennchen/zipstream-php/test/bootstrap.php, lib/vendor/maennchen/zipstream-php/test/bug/BugHonorFileTimeTest.php
With this PR zip files made on the server side (unencrypted transfers) can contain utf8 in their file names.
=> server side zip: support utf8 filenames

scripts/client/filesender.py
Hi, 
I made some mistakes with the previous pull request https://github.com/filesender/filesender/pull/1412 
(I didn't realize it would keep up to date with my latest commits to my own fork.)
The following changes change the output help output of the command line. 
Running `python filesender.py --help` currently will output:
```
usage: filesender.py [-h] [-v] [-i] [-p] [-s SUBJECT] [-m MESSAGE] [-g] [--threads THREADS] [--timeout TIMEOUT] [--retries RETRIES] -u USERNAME -a APIKEY -r RECIPIENTS files [files ...]
positional arguments:
files                 path to file(s) to send
optional arguments:
-h, --help            show this help message and exit
-v, --verbose
-i, --insecure
-p, --progress
-s SUBJECT, --subject SUBJECT
-m MESSAGE, --message MESSAGE
-g, --guest
--threads THREADS …
```
=> Added simple help description to the client CLI

www/js/transfer.js
File extension getter was returning erroneous extension in the case of a directory whose name contains a dot with an extension-less file inside. Example : a `v1.6` folder containing a `OUT` file, the javascript file's name property is `v1.6/OUT`, thus the `getExtension` was returning `6/OUT`, which does not match the file extension regexp and was thus banned. This fix strips the path from the file name before splitting the basename and the extension.
=> Fix erroneous file extension getter

templates/user_page.php
This relates to https://github.com/filesender/filesender/issues/1438
=> templates: move those links into the tr:python_cli_client_setup_information string if the site wishes for it

classes/rest/endpoints/RestEndpointTransfer.class.php, classes/storage/StorageCloudS3.class.php, classes/storage/StorageCloudS3Stream.class.php, docs/v2.0/admin/configuration/index.md, docs/v2.0/cloud/index.md, includes/ConfigDefaults.php, scripts/task/S3bucketmaintenance.php, scripts/task/cron.php, templates/transfers_table.php
This is a _works for me_ version of S3 daily bucket support for Filesender. I'll continue testing this a bit and if I don't find any real issues, we might be inviting some of our real users to test-drive this during next few months.
When storage_type is set to CloudS3, daily buckets can be enabled with `$config['cloud_s3_use_daily_bucket'] = true;`
Bucket naming prefix can be set with cloud_s3_bucket_prefix. Bucket name will be prefix + YYYY-MM-DD, for example:
```
$config['storage_type'] = 'CloudS3';
$config['cloud_s3_use_daily_bucket'] = true;
$config['cloud_s3_bucket_prefix'] = "Demo-";
```
Would today use bucket **Demo-2023-04-27**. Buckets are created (and removed when no longer needed) by cron.php, there is also scripts/task/S3bucketmaintenance.php that can be run to do only daily …
=> Support for S3 daily buckets

docs/v2.0/admin/configuration/index.md, docs/v2.0/cloud/index.md
This takes the advice on clunk size from https://github.com/filesender/filesender/pull/1455 and brings it into the cloud docs page. The configuration page now also links to the cloud page to hint to the admin that relevant information is contained in that page.
=> Cloud docs update

www/js/transfers_table.js
This should fix https://github.com/filesender/filesender/issues/1468
=> bootstrap: show the collapse area in the transfer details again

classes/auth/AuthSPSaml.class.php
The URL for login and logout changed in SimpleSAMLphp 2.x and the code in FileSender had hard coded the locations for login and logout. This PR changes that to ask SimpleSAMLphp for those URLs instead which should allow the code to function against either a SimpleSAMLphp 1.x or SimpleSAMLphp 2.x installation.
This relates to  https://github.com/filesender/filesender/issues/1467
=> simplesamlphp do not force the login url but use the class to get it

docs/known-installs.md
Samenwerkende Universitaire Reken Faciliteiten is now commonly known as _SURF_.
=> Update name of SURF

classes/data/File.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, templates/download_page.php, www/js/download_page.js, www/js/upload_page.js
The download of an unencrypted archive is now performed via a POST request. The existing way was using an http redirect to start this particular form of download. The problem with that is the file_id list could be very long and might overflow what is acceptable on a GET and thus fail for some proxy setups etc. Using POST allows the fileid list to be moved off the URL and thus remain relatively long but also functional in such environments.
Adding many files is now a fair bit quicker. For the test environment it went from 3.3s down to 1.8s. Still not ideal but better. Note that there is still a significant speed difference between "add a directory" and add file(s) and selecting all 1500 test files. I have narrowed this down to a Collection call that is only made on the former and requires …
=> many files: adding them is quicker, download is via POST

templates/download_page.php
A natural sort should allow file collections with numeric version information or sequence numbers embedded in the file names to be displayed in a more agreeable manner.
This relates to https://github.com/filesender/filesender/issues/1489.
=> ui: sort files on download page with natural sort on name

classes/utils/SystemMail.class.php
Fatal error at `scripts/task/cron.php` when calling `SystemMail::quickSend()` because the parameter is different from that of the inherited `ApplicationMail::quickSend()`
```
PHP Fatal error:  Declaration of SystemMail::quickSend($translation_id) must be compatible with ApplicationMail::quickSend($translation_id, $to) in /opt/filesender/filesender-2.39/classes/utils/SystemMail.class.php on line 65
```
=> Fix parameter of SystemMail::quickSend()

classes/utils/GUI.class.php
classes/utils/GUI.class.php filterSources is used to verify that all files passed to it as an argument exist in the web root.
This check was done with file_exists function. file_exists also returns true if the name is a directory. php has as separate is_file function that returns true only if the name exists and is a regular file.
This fixes a cosmetic issue: templates/header.php was sending `<link type="text/css" rel="stylesheet" href="/css/" />` to the browser because we do not have a separate `site_css` defined in config.php.
=> change GUI.class.php filterSources to use is_file instead of file_exists

classes/utils/Browser.class.php, classes/utils/GUI.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/crypter/archive_sink.js, www/js/crypter/crypto_app.js, www/js/crypter/filesystemwritablefilestream_sink.js, www/js/crypter/streamsaver_sink.js, www/js/pbkdf2dialog.js, www/js/zip64handler.js
This feature is currently only available when you have both `fileSystemWritableFileStream_enabled=true` and `streamsaver_enabled=true` set in your config.php. This will prefer to use the FileSystemWritableFileStream API when available to stream data to disk. As at mid 2023 Edge and Chrome support this feature, Firefox supports most but not all (so can not be used) and Safari does not support the feature. In the future this may be separated from the streamsaver_enabled option so it can be enabled independently.
There are two ways I see when FileSystemWritableFileStream API is being used. Firstly, in Chrome when downloading an encrypted file or transfer you will see a file dialog appear asking where to save the file. Secondly, and far more subtle, in the web console you will see messages …
=> Option to use File System Access API on Chromium browsers

www/js/dragdrop-dirtree.js
We need to do this in a timeout otherwise the eval is run before the DOM has settled during adding of files.
This is an update to https://github.com/filesender/filesender/pull/1505 without reverting the speedup when adding 1000s of files.
=> DND eval if send button should be enabled

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/download_page.php, www/css/default.css
Add new option download_show_download_links where default is false. This allows FileSender to show direct download links on the download page (where possible)
How it looks with default filesender settings:
How it looks with download_show_download_links set to true:
=> Add option for download_show_download_links

docs/v2.0/admin/configuration/index.md
The table prefix has been broken for a while now. The feature is now deprecated and will be removed in 3.x. 
It could be added again but it seems reasonably unlikely that people are wanting/using it.
This relates to https://github.com/filesender/filesender/issues/1543.
=> docs: mark this as deprecated

scripts/client/filesender.py
In response to https://github.com/filesender/filesender/issues/1549
This allows the user to specify the -d / --directories flag to automatically try and preserve folder structure. 
I opted for the approach of automatically working out what folders to keep based on a common root for all files. 
We use filesenders automatic directory insertion to create the files, because of this the names returned in transfer aren't actually usable to identify the file locations, to get around this I keep track of the file name we gave filesender and the on disk location. 
I've tested this on windows with 1000 files and several subfolders deep and it worked well.
=> Allow Filesender.py to preserve directory structure

classes/utils/Utilities.class.php
in the event i use two load balancers the X-Forward-For shows as:
```
[HTTP_X_FORWARDED_FOR] => <<User IP>>, <<FIRST LB>>
```
This fix sets it to the first load balancer so we get the users IP and not the first load balancer
=> multiple load balancer fix ip, use the first ip not the last

language/README.md, scripts/language/README.md, scripts/language/send-json-translations-for-language-to-poeditor.sh, scripts/language/send-newterms-json-to-poeditor.sh
This switches references from the old projectid to the new one for filesender3.
The project is currently invite-only, since I'm finishing things like CI for languages.
With CI for languages enabled, we can automate two tasks that are now done semi-automated:
1. Scan for changes in any language file, and handle changes to the terms. I'm currently developing this in https://github.com/AvesIT/filesender/pull/new/2023/10/lang_ci_testing
2. Upon creation of a release-branch, download all languages from poeditor and update the source code as needed. This is yet to be implemented, stay tuned!
=> Switch poeditor project id for filesender3

templates/new_invitation_page.php
dev3: As long as new_invitation_page.js remains looking for these by the parent class it is important for the template to keep putting that expected format in place. Either change both things, neither of them, but certainly not just one of the two.
=> Allow saving new guest options again

templates/guests_table.php
That collection is of transfers not a single transfer object. I dont recall this one being in the review itself. Just an organic one that prevented the page from rendering.
=> Allow the page to render when a guest has performed some uploads

www/js/upload_page.js
The the dev2 code did not allow a message when you were getting a link so it didn't need to worry about checking that as the message element was hidden too. So we check all the time now and resolve https://github.com/filesender/filesender/issues/1592 while we are at it :)
=> dev3 ui3 fix for password and message when getting a link

templates/user_page.php
Not ideal as the download attribute doesn't work cross domain etc, but at least it gives the data to the user.
relates to https://github.com/filesender/filesender/issues/1602
=> dev3 ui3 might as well link right to github there

classes/rest/RestServer.class.php, classes/rest/endpoints/RestEndpointUser.class.php, templates/user_page.php
This allows downloading that config on the user page for quick setup of the filesender.py client.
This relates to https://github.com/filesender/filesender/issues/1602
=> generate the filesender.py configuration file on demand

templates/upload_page.php, www/js/upload_page.js
In that case we might as well select the email option as it is the only choice. This is an update to
https://github.com/filesender/filesender/issues/1621 because in the past you could proceed without selecting anything and would "get a link" by default. Now I am automatically selecting the only option if get a link is not available.
Note that the class get_a_link_top_selector is there for now because get a link is reshown in the options and thus the HTML ID get_a_link might not be unique. When get a link is not shown in the main options then this could be updated to directly use the ID instead.
This relates to https://github.com/filesender/filesender/issues/1621
=> Handle when get a link is not available.

templates/upload_page.php, www/js/upload_page.js
IIRC there was some magic in the old dev3 to not reshow get a link in the options though that might have bit rotted over the years.
I have removed it from the options that are shown and made the rest of the code check if getting a link is an option and if so if it is selected at the top of the page. Basically making that specific toggle more of a global than just another option and only presented in one place in the UI.
This may break other things but it is probably best to do that now and as other ripples are found I can address them.
This addresses https://github.com/filesender/filesender/issues/1589 and may cause side effects that require minor code updates to address.
=> get a link is a top element only and not in options anymore

www/js/upload_page.js
It is redundant to perform PBKDF2 on a randomly generated password of sufficient length. Given that this was a feature introduced in 2019 on the advice of a professional cryptographer I think it should be retained until explicitly removed.
Allowing for generated passwords to avoid PBKDF2 allows for secure site setups. For example, large numbers of PBKDF2 rounds can be set which will require significant time to perform and obtain the commensurate security under attack. As generated passwords do not require PBKDF2 the user has the choice of a custom password and a significant delay or a more random generated password and immediate upload. For example one might set PBKDF2 rounds such that they require minutes to perform.
I would also love to retain this for future PGP integration as that …
=> Dev3 UI3 Allow generated passwords to not have PBKDF2 performed on them

classes/data/RateLimitHistory.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, scripts/task/cron.php
delete entries older than 31 days by default in the cron job.
This relates to https://github.com/filesender/filesender/issues/1677
=> RateLimitHistorys table cleanup

language/en_AU/lang.php, templates/download_page.php
This allows the number of days to be shown in a different location in the string for langauges that can benefit from that for a more natural translation.
I have updated poeditr for en and en_au as well
This relates to https://github.com/filesender/filesender/issues/1647
=> d3ui3 Use an array to allow the wording to change more readily

www/js/upload_page.js
Fix invalid filename error not being displayed at upload (upload_page.js), errorhandler function not called.
Invalid filename errors are not displayed to users. They think that there is no issue with this file. 
Not an issue when uploading one file but when uploading multiple files, the one with invalid filename is ignored/not uploaded and users are not aware of.
This issue has been introduced  as of version 2.41
=> Fix invalid filename error not being displayed at upload 

templates/new_invitation_page.php, templates/upload_page.php, www/js/upload_page.js
The full email fields are shown for a guest upload. They are removed for guests who can only send to the inviting party. That needs retesting.
For now I have disabled the ability for a guest to perform an upload and "get a link" to the file. It is a code path that needs revalidation to allow a guest to upload a file and get a link to it instead of sending emails etc.
=> UI3 guest handling update: email shown, no get a link

templates/new_invitation_page.php
This was dependant on the config / advanced setting before. Now it shows regardless of that setting on guest_options/can_only_send_to_me
This relates to https://github.com/filesender/filesender/issues/1604
=> new invitations page show can only send to me

classes/data/AuditLog.class.php, www/download.php
Upon first access to a download link a transaction identifier is generated (using filesender's uuid generator) and user is redirected to the current download along with the identifier.
AuditLogs get an additional transaction identifier property that automatically logs any (valid) transaction identifier contained in the request.
This makes it so subsequent download events (resumes, ends) are flagged as part of the same transaction in the auditlogs, and thus makes it possible to identify bogus clients and compute more reliable statistics.
This replaces #1681 (base branch fix)
=> Download flow consolidation for v2.x

language/en_AU/lang.php, www/js/upload_page.js
This moves the policy of if the total number of files is shown into the translation layer.
This relates to https://github.com/filesender/filesender/issues/1585
=> d3ui3: Move if the total count and size is shown into the translation layer

classes/data/User.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/rest/endpoints/RestEndpointUser.class.php, classes/utils/Utilities.class.php, templates/user_page.php, www/js/user_page.js
This saves the options
"Use transfer settings from previous upload as default settings for
next transfer."
and
"Save email recipients from past use (used to automatically complete
email fields)."
There is an update to wipe email recipients if that option is off.
The transfer settings are saved if that option is on but they are not currently respected by the upload page. That is a future PR.
This relates to https://github.com/filesender/filesender/issues/1597 and https://github.com/filesender/filesender/issues/1596
=> d3ui3: Two config options in user settings

classes/data/User.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, templates/upload_page.php, www/js/upload_page.js
This uses transfer_preferences if save_transfer_preferences=true in the database when creating a new upload.
The older code would record how frequently things were selected and try to work out what to do from there. The new code just uses what was being used in the last transfer for the next one.
This relates to https://github.com/filesender/filesender/issues/1596
=> d3ui3 Use saved transfer settings if user wants

templates/upload_page.php, www/js/upload_page.js
We can always prune it off again. If we are doing that for design we should be aware and accept the security degradation in any non single person office that is involved in an upload. I imagine there are many shared spaces in higher education where being able to see a password as it is typed on a keyboard is much harder than just taking a photo of it on the screen.
This relates to https://github.com/filesender/filesender/issues/1581
=> d3uid3 bring back show/hide password option

www/js/upload_page.js
If you are getting a link then it doesn't make too much sense to be a recipient too. That is more for email links.
This relates to https://github.com/filesender/filesender/issues/1582
=> d3ui3 remove this option when getting a link

templates/upload_page.php
This brings back support of the advanced setting in config.php/transfer_options. So setting advanced to true will put the option into the advanced subpart of the UI and being advanced=false will make the option a main item.
This gives the sys admin the flexibility to choose how that part of the UI will appear. We could make the default config.php have advanced=true for all the transfer_options to make the default shipping of FileSender as it was in the UI redesign.
$config['transfer_options'] = array(
'email_me_copies' => array(
'available' => true,
'advanced' => true,
'default' => false
),
This relates to https://github.com/filesender/filesender/issues/1595
=> Allow options to be put in advanced or not through config.php

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/upload_page.php, www/js/upload_page.js
For countries, cities, or towns with slower internet access it is extremely useful to be able to pause an upload so that a long upload does not block voip or video calls.
Even if an NREN has significant bandwidth expectations for most users some of those users may travel to areas with limited bandwidth and may then appreciate the ability to pause an upload.
At any rate, as maintainer I find it useful enough for myself and users to have made it at least available as an option. I think people can comprehend the interface and ignore that part unless it is of use.
=> d3ui3 Bring back pause, play, stop on upload as option

www/js/dragdrop-dirtree.js
Its a strange API now having an array of entries returned and the need to do multiple calls until zero are returned. One might have thought a visitor function perhaps with an explicit limit number or function might have been a better choice but such is evolution.
This relates to https://github.com/filesender/filesender/issues/1715
=> Update for 100 file limitation in directories dropped in Chrome

classes/rest/endpoints/RestEndpointGuest.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/storage/StorageCloudS3.class.php
S3 storage: Use the same custom or daily bucket name code for both guests and authenticated users.
This relates to https://github.com/filesender/filesender/issues/1718.
=> use the same bucket names for guests

templates/logon_page.php
Some parameters need to be feed to the ReturnTo parameter in order for the user to return back to the transfer and guest details page correctly.
This can be triggered without waiting for a SAML session timeout by copying the URL, explicit logout. Then paste the original URL again and FileSender will ask you to authenticate. Without this PR you will either get an error on the transfer detail page or a guest not found general error on the guest detail page. With this PR you will see the expected page as the return from saml will complete properly.
This relates to https://github.com/filesender/filesender/issues/1725
=> ui3: SAML if relogin is needed return to details page correctly

.github/workflows/sq.yml
this PR enables sonarqube scanner on you project. 
In order to work, you'll need to setup, two variables.  
You should also create two secrets at Organization level (so they will be shared among your projects):  https://github.com/organizations/ORGANIZATION/settings/secrets/actions (replace ORGANIZATION with the name of your organization).
* SONARQUBE_HOST this is not really a secret: https://sonarqube.software.geant.org/
* SONARQUBE_TOKEN you need to create a token at this URL: https://sonarqube.software.geant.org/account/security
Feel free to edit the triggers according to your needs. Now the scan is set to be triggered on any push, for every branch.
=> add SonarQube CI

scripts/client/FilesenderRestClient.class.php
I have some modes in the nodejs client to allow this sort of SSL stuff for development but it is enabled by explicit triggers in configuration and environment. Such a feature is likely handy for this client too but should be a configuration setting for developers.
=> verify host by default. If an insure mode is desired it should be made explicit in a subsequent PR.

classes/data/Transfer.class.php, classes/storage/StorageCloudS3.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
This adds bulk delete for S3 storage to filesender.
Bulk delete allows deletion of multiple chunks simultaneously, up to a configured maximum. The purpose of this feature is to increase speed while deleting chunks from S3, due to lower overhead on the S3 side.
In tests, with default values, the deletion speed of a file with an exact multiple 1000 chunks was 8x faster than normal.
Bulk delete is controlled by two configurables:
The feature is toggled by boolean `cloud_s3_bulk_delete`, which defaults to false, for backward compatibility
There is one option, called `cloud_s3_bulk_size`, which defaults 1000, and is the number of objects that is deleted in one request.
=> S3: Add bulk delete option

scripts/client/filesender.py
Hi Team, 
I've been working on the start of encryption support in the python client. This can also work as an example for issues such as [1038](https://github.com/filesender/filesender/issues/1038 ). 
Currently it only supports AES-GCM but I tried to write it in such a way that is easy to expand in the future. 
The user simply specified -e with their desired password much like they do for email address already.
There are 3 new imports required, base64 and Enums are from the standard library but the [Cryptography library](https://github.com/pyca/cryptography) is 3rd party
As it is a 3rd party library and may not be present it has been moved so it only impacts users who haven't installed required library but also want to use Encryption. 
There should be no code changes for users who do not …
=> Encryption support in python client

templates/menu.php
This is a reverse of https://github.com/filesender/filesender/pull/1704
The design originally had no logoff button. For SAML we should really move to SAML Single Logout (SLO) if we want to retain the logoff feature.
=> Remove logoff buttton agian as was the original 3.0 design

classes/rest/endpoints/RestEndpointGuest.class.php
When no transfer options are supplied when creating a guest via the REST API then incorrect behaviour was observed. By setting at least one key in the transfer options I noticed the correct behaviour after an upload as that guest.
This relates to https://github.com/filesender/filesender/issues/1773.
=> rest: guests with no transfer options should have at least one default

classes/data/File.class.php, classes/exceptions/StorageFilesystemExceptions.class.php
Setting the below your config.php will result in more debug including the reason that file delete has failed.
```
$config['exception_additional_logging_regex'] = '.*Exception';
```
Tested with `chattr +i ` on the file in `/opt/filesender/files` and attempting to delete the file with the web ui. This clearly showed a message of `Operation not permitted`.
This relates to https://github.com/filesender/filesender/issues/1785.
=> option for more info when delete fails

classes/data/Transfer.class.php
Creating a guest voucher with both the "only send to me" guest option and "add me to recipient" transfer option led to a download link being sent to the guest anyway because "me" was always evaluated as the transfer's creator, this fix makes it so that "me" becomes the guest creator when both options are used.
This bug caused a problem when a user sent an invitation to a mailing list to gather sensitive documents and the list was automatically added as a recipient of the download links ...
=> Fix download recipient for only-send-to-me guests

classes/data/File.class.php, classes/data/Guest.class.php, classes/data/Recipient.class.php, classes/data/ShredFile.class.php, classes/data/TranslatableEmail.class.php, classes/utils/Utilities.class.php
Recent use of uuidv7 for all uids led to a significant loss of entropy for key-based identification (recipients, guests ...)
While the use of uuidv7 for storage is not an issue, its use for identification may be because of its weakness, these changes keep the use of uuidv7 for storage names but use uuidv4 with more entropy when generating identification keys (recipient tokens, guests tokens, email translation tokens, web interface security tokens ...)
=> Use uuidv7 for storage and uuidv4 for key-based identification

classes/storage/StorageFilesystem.class.php, classes/utils/Utilities.class.php
existing files using uuidv7 should still also be handled.
=> use uuidv4 for all uuids again for now. update to filesystem daily buckets to work with uuidv4

.gitignore, classes/auth/AuthRemote.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, scripts/client/nodeclient/README.md, scripts/client/nodeclient/download.js, scripts/client/nodeclient/filesenderapi.js, scripts/client/nodeclient/package.json, scripts/client/nodeclient/upload.js, www/filesender-config.js.php, www/js/client.js, www/js/transfer.js
The main motivation for this client is using nodejs and the WebCrypto API to have as close of a javascript path to transfer files as is used by the web browser. The initial code drop focuses on encrypted upload and download and supports multiple file transfers. A transfer with many files will have all files downloaded to a subdirectory.
Downloads can be performed using the same URL that is loaded in the browser to see a transfer and download files. This is the same link that is displayed as "get a link" and also sent in emails to people. The upload.js program also displays this download link allowing for easy testing.
See scripts/client/nodeclient/README.md for information.
=> rest: new nodejs rest client with encryption support

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, templates/guests_page.php, templates/upload_page.php
This is to help some sites migrate to the 3.x series. It might be useful in other contexts as well. For example,  migrating to a different server machine or disk storage environment where you might not wish to copy existing files over.
I considered if I should disable deleting a transfer, deleting a guest and other mutable actions. At the moment the PR is just for disable new uploads and disable new guest creation.
This relates to https://github.com/filesender/filesender/issues/1808
=> read only mode to allow for major migrations

ci/filesender-config.php, config/config-sample-meijer.php, config/config_sample.php, docs/v2.0/admin/configuration/index.md, docs/v2.0/admin/reference/index.md
This updates the default SAML user ID attribute from the deprecated `eduPersonTargetedId` to the newer `pairwise-id`.
Interested readers may consider https://docs.oasis-open.org/security/saml-subject-id-attr/v1.0/cs01/saml-subject-id-attr-v1.0-cs01.html for more information.
This was kindly suggested in a comment at https://github.com/filesender/filesender/issues/1781#issuecomment-1991258902
This supersedes https://github.com/filesender/filesender/pull/1822
=> SAML: update default id attibute to the more modern pairwise-id for ui3

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
The AES-GCM + PBKDF2 is more secure for a number of reasons and was also audited before acceptance. It may not work in some older browsers but should work in modern Safari, Chrome, Firefox, Edge (Chromium based).
=> ui3: update crypto to version 3 (GCM+PBKDF2) by default

classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
This is an update to the deprecation of strftime and the old translation strings which are specific to that function. The new breaking change is to allow the length of formatted date and time to be specified in the configuration file and the information is then presented in that level of detail using the locale that the user is most comfortable with.
=> d3: foramt dates with locale and a config as to how long the admin wishes these to be

classes/utils/Config.class.php
If a REST client (or other browser) fails to authenticate here we just do not load these additional config files. If failed auth is really a problem then other code will have an `Auth::isAuthenticated()` call that throws and will then stop processing there. We can allow failed auth to be served without these additional config files and for that case to not cause a syslog event.
This relates to https://github.com/filesender/filesender/issues/1840
=> auth: do not throw here if not authenticated

classes/utils/Utilities.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, www/filesender-config.js.php, www/js/filesender.js
I have focused on adding this only in the 3.x series. This is part 1 of 2 for updated timezone handling. This allows the browser to send the timezone to the server if the option is configured on the server. The dates are them formatted for display using that timezone.
This relates to https://github.com/filesender/filesender/issues/354.
=> option to send timezone from the client to the server for date handling

templates/upload_page.php
Our team has suggested these changes to make the UI look and feel better:
Button: Send <tick> to Send <arrow> (since it moves to the next page which does the upload, users might assume that the sending is done with the tick)
Convert generate_password link to a generate_password button, so users know it is something people can click on.
=> v3: don't make send a tick, generate_password to a button

classes/utils/Utilities.class.php
We have 1 user who's first ip in $ips is filtered out, which causes a DBIUsageException exception,
This PR fixes this issue.
=> fix ip when $ip[0] doesn't exist

classes/data/Transfer.class.php, classes/utils/Logger.class.php, classes/utils/TransferQueryOrder.class.php, scripts/upgrade/explicit/upgrade-2.48-to-2.49-post-download-count.php
Each time a file is downloaded the download_count in transfers is incremented. This allow very quick sorting by downloads in the transfers table. 
Note that this requires the values to be brought forward with the explicit database script at scripts/upgrade/explicit/upgrade-2.48-to-2.49-post-download-count.php if you want the counts to be set correctly after an upgrade.
This relates to https://github.com/filesender/filesender/issues/1888.
=> help sort by downloads by better recording the count

classes/autoload.php, classes/data/UploadGraph.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, scripts/task/update-upload-graph-table.php, www/js/graph/uploadGraph.php
A new option that, when enabled, allows the upload graph to used cached data in the database rather than executing a more complex query each time the upload page is loaded.
Using this option requires you to run `scripts/task/update-upload-graph-table.php` in order to keep the cached data up to date. This can mean one execution every 15 minutes, hour, or whatnot instead of one execution for each load of the upload page.
This relates to https://github.com/filesender/filesender/issues/1887.
=> option to precache values for upload graph

classes/rest/RestRequest.class.php
This extra var was effectively ignoring mime_type from web browser eg:
```
Array
(
[0] => RestInput Object
(
[data:RestInput:private] => Array
(
[name] => s-l1600.jpg
[size] => 141657
[mime_type] => image\/jpeg
[cid] => file_1715649373497_11_141657_679143
[aead] =>
)
[mime_type] =>
)
)
```
the mimetype on the bottom is always blank. and code in classes/rest/endpoints/RestEndpointTransfer.class.php `$filedata->mime_type` is always empty thus ignoring the image/jpeg above.
=> Fix mime types

www/css/new-ui/pages/_download.css
These were hidden with css before until needed. They are again.
=> d3ui3: fix regression. hide this part of the page until it is needed

classes/auth/AuthSPSaml.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, language/en_AU/lang.php, www/filesender-config.js.php, www/js/ui.js, www/js/upload_page.js
For SAML sessions, when the new `auth_warn_session_expired` feature is enabled a cookie is used to allow the client to warn the user when their session has expired. This warning is not presented when an upload is in progress because an upload can outlive a session in order to complete.
This relates to https://github.com/filesender/filesender/issues/1881
=> ui: option to warn user if session has expired

www/css/new-ui/components/_buttons.css
This updates the look of the buttons in bootbox to more closely match the css buttons.
This relates to https://github.com/filesender/filesender/issues/1851
=> ui3d3: theme the bootbox dialogs with round corners

www/css/new-ui/components/_buttons.css, www/css/themes/dark.css, www/css/themes/default.css
This relates to https://github.com/filesender/filesender/issues/1851
If green doesn't mean go in the main theme then it shouldn't be that in the dialogs.
=> ui3d3: bootbox button colours match theme

.github/workflows/ci.yml, .github/workflows/pr.yml, .github/workflows/sq.yml
Currently CI runs on all forks, even if it does not make any sense for it to do so.
It would make sense if we add linting to CI, so we can check if everything is at least valid php/css/etc, but currently we try to do all kinds of checks where secrets are absent for selenium, sq, etc.
Let's be friendly to our kind hosters (and the environment!) and not waste CPU cycles.
=> Only run CI on non-forked repositories

classes/data/TranslatableEmail.class.php
This was raised in https://github.com/filesender/filesender/issues/1916. Normally one would not have as many tuples as in that issue but even with fewer tuples and index here will increase efficiency, especially for selecting single tuples from the table.
=> db: add index on TranslatableEmails.token

classes/utils/GUI.class.php, templates/menu.php
Adds back logo behaviour from UI2
Fixes #1552
Possibly the styling in https://github.com/filesender/filesender/blob/bf00c8e4bf123f6964781f30d0e81945a09262ed/classes/utils/GUI.class.php#L232 could be done better, but I'm no CSS king.
=> Bring back configurable site_logo from v2

.github/workflows/ci.yml, .github/workflows/pr.yml
After #1914 limiting runs on master, it may make sense to activate this on the default branch as well
=> Limit CI runs on development branches as well

templates/transfer_detail_page.php, www/css/new-ui/components/_badge.css, www/js/transfer_detail_page.js
The lack of these buttons in ui3 was reported in https://github.com/filesender/filesender/issues/1923.
This PR also adds back an extremely tiny bit of semantic classes for example the recipients having a class of recipient.
=> ui3: allow direct actions for recipients on the transfer details page

templates/transfers_table.php, www/js/transfers_table.js
This is in response to https://github.com/filesender/filesender/issues/1924
These UI items may need to be hidden in a "non advanced" mode as they were removed by UI experts and requested to be returned by an NREN.
=> ui3: bring back quick actions for transfer list

templates/transfers_table.php
some reports indicate that the transfer list is not obvious it can be clicked. This adds a fake icon to allow a hint to click.
=> ui3 info icon in transfer list to hint at clickable

templates/user_page.php
Seeing 0 means nothing if there is no quota in use.
=> ui3: hide quota from profile page if the system is not using one

classes/utils/Lang.class.php
Probably when trying out the [FileSenderCli](https://github.com/WEHI-ResearchComputing/FileSenderCli) these warnings appeared in my web server error log:
```
Undefined array key "HTTP_ACCEPT_LANGUAGE" in /opt/filesender/classes/utils/Lang.class.php on line 265
```
The only call to `Lang::getUserAcceptedLanguages()` is from `formatDate()` in classes/utils/Utilities.class.php that then iterates over the result `foreach ($al as $k => $v)` so I guess returning an empty array in the pathological case makes sense.
=> Fix undef HTTP_ACCEPT_LANGUAGE warning

www/css/new-ui/components/_progress-bar.css
Running these together does have an 1980s retro look but having some space between them makes it seem more planned out.
=> ui3: leave some space between the progressbar text and bar

www/js/dragdrop-dirtree.js, www/js/ui.js
Sometimes having long path names in subdirectories causes drag and drop to ignore the long paths and skip the file all together.
This PR pops up an error when this is caught.
Note: tr for `directory_issue` will need to be added for the error to look nicer. (feel free to rename)
Another issue we have noticed, it seems in upload_page.js in the `filesender.ui.nodes.files.input.on('change'` function, the web browser seems to just skip problematic file paths in `this.files` without warning. Not sure how to solve that, maybe a pop up asking users to double check the list?
=> UI3: handle directory_issue in drag and drop

classes/rest/endpoints/RestEndpointGuest.class.php
Same as #1963, however now against `development` branch
When upgrading an install from 2.40 to 2.48 recently, we ran across an issue where transfer settings for guests would be lost.
This PR should fix this.
=> Fix S3 guests losing transfer settings

classes/utils/ApplicationMail.class.php, classes/utils/Config.class.php, docs/v2.0/admin/configuration/index.md, docs/v3.0/admin/configuration/index.md
This idea was originally proposed in https://github.com/filesender/filesender/pull/1971. 
This update requires the images that can be used in the cid to be listed in a config value and limits which cids can be selected to only using a range of a-z characters. If the cid is not in the config variable then no image will be attached.
=> allow image attachments from mail templates

www/clidownload.php
Hey Team, 
Minor change to address: https://github.com/filesender/filesender/issues/1974 
The CLIDownload will now only replace the default [base_url] string in the python file. 
I tested this on our dev server to confirm the new expected behavior, I kept the $one variable tracking how many changes. there have been but as far as I can tell that isn't used.
=> Clidownload.php fix for python client

templates/download_page.php, templates/new_invitation_page.php, www/css/new-ui/_general.css
This is in response to https://github.com/filesender/filesender/issues/1976
Being able to remove unsafe-inline from CSP is very useful!
=> fix these to allow removing unsafe-inline from CSP

config-templates/apache/filesender.conf, docs/v2.0/install/index.md, docs/v3.0/install/index.md, scripts/install/simplesamlphp-extract-sha256-from-release-notes.php
We should be using SSP 2.x these days. The hash extractor script is updated and many parts of the docs. A clean install into a VM would be useful to try to catch any outstanding issues.
=> Update docs for SSP 2.x use

docs/_includes/menu.html, docs/v3.0/user/download/index.md
The start of some user docs. In this initial page, how to download with command line tools.
This was raised in https://github.com/filesender/filesender/issues/1985
=> d3: add some user docs, downloading

language/en_AU/lang.php, templates/download_page.php
The docs page linked to should start out describing the web ui more as that is probably the first thing folks might want to know about. Then the command line stuff. Then the rest clients to transfer encrypted files.
=> d3: add a more info link on the download page

www/js/upload_page.js
I suspect the page structure changed slightly and the selector was not matching then. This seems to restore functionality.
=> ui allow lang selection in upload again

templates/upload_page.php, www/js/upload_page.js
This restores the optional feature of letting a user select the human language for a transfer. This allows the greeting email to be send in a language that is more likely to be accepted by the person reading the email notifying that a new file is available.
Fixes https://github.com/filesender/filesender/issues/1620
=> d3: allow language selection on upload as option

language/en_AU/lang.php, www/js/upload_page.js
This is an update to UI2 to allow the user to click on the file that is not a duplicate and remove the duplicate(s) in the upload dialog instead. This is because if you delete a file then another file is no longer a duplicate and can be uploaded. 
I will make an update to the UI3 code as well.
This was raised for UI3 at https://github.com/filesender/filesender/issues/2020.
=> cleaner interface for deleting duplicate files when clicking on existing file

classes/rest/endpoints/RestEndpointTransfer.class.php
When POST to endpoint _/rest.php/transfer_ with payload as described here: [creare new tranfert request](https://docs.filesender.org/filesender/v2.0/rest/)
we get the following error:
`Fix: PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, Array given in /usr/local/data/sites/fsender/filesender -2.49/classes/rest/endpoints/RestEndpointTransfer.class.php:564`
Issue ( #2027)
=> Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, Array given- RestEndpointTransfer.class.php (#2027)

classes/constants/TransferOptions.class.php, includes/ConfigDefaults.php, www/js/upload_page.js
Hi Team, 
We've noticed more users raising support requests unsure if their upload was complete and wanting to double check with our team. 
To resolve this we wanted the option for a more aggressive confirmation for the users.
This PR adds a new transfer option called 'popup_on_complete'  following the examples of 'WEB_NOTIFICATION_WHEN_UPLOAD_IS_COMPLETE' and 'redirect_url_on_complete'. 
When enabled it provides a notification using the standard language as follows:
The admin simply needs to add the configuration option to their transfer options like they would any other.
=> Added the option for upload complete popups.

docs/known-installs.md
Changed the description of how to add an install to the list, it was not clear that filesender-dev requires you to be subscribed to it before you can post. Changed that item into an invitation to subscribe to the support list filesender-dev and let the wider community know about your install, added a 3rd option to just send the FileSender board an email.
=> Update known-installs.md - changed description of adding an install

templates/upload_page.php, www/js/upload_page.js
This has been requested by 3 NRENs now (https://github.com/filesender/filesender/issues/1920). It is a strange situation where I am reluctant to make simple changes to the UI code even with strong feedback. I suppose since this is not a huge change code wise it can be reverted if it violates the overall design in mind for the 3.x UI and in the meantime folks can use it based on the feedback they have from their respective teams. Or we can make this yet another an optional change with a configuration setting to have and maintain.
This was requested in https://github.com/filesender/filesender/issues/1920
=> ui3: remove the subject and message when get a link is used

classes/utils/ApplicationMail.class.php, docs/v3.0/admin/configuration/index.md, includes/ConfigDefaults.php
The issue and potential default configuration value updates have been discussed in https://github.com/filesender/filesender/issues/1820.
This PR changes the default to "no-reply@" which will be expended to have `site_hostname` or the host name component from `site_url` appended to it to make a no reply address at the server machine name.
One reason site_hostname is handy is if you have the browser setup in a local test environment for a local host name on the LAN but the email system wants to have `.localdomain` added to the name. So you can set site_hostname to `mymachine.localdomain` and that will allow emails to be in the format that the SMTP server is expecting. If this happens on one dev machine it is likely to happen on 1+ machines so the option to optionally set this configuration …
=> d3: update for default value for email_from/email_return_path sender

classes/utils/Security.class.php, docs/v3.0/admin/configuration/index.md, includes/ConfigDefaults.php
Some sites are wanting to disable this check for guests. The default is to perform the checks so security and configuration does not change unless you set this new option to `false`.
This is in response to a few requests in  https://github.com/filesender/filesender/issues/1514
=> optional: make guest csrf optional to allow sys admins to select

templates/transfer_detail_page.php
This allows an admin to view transfers from any user. This is useful in the admin pages of FileSender when enabled.
This relates to https://github.com/filesender/filesender/issues/2035
=> ui3: allow admin to view transfers from other users

templates/invitation_detail_page.php
This does the same thing as https://github.com/filesender/filesender/pull/2051 
This code is more verbose and checks are split out a bit more. I was in two minds in the past PR about if the isAdmin() lead to an empty // admin block or I used `!isAdmin()`. At any rate the guest owner check is in a different if block here.
The checks for guest id not found are still run even for admin. If the guest is no longer in the database trying to display it will likely end with errors on the page.
=> d3: allow admin to view other guests

templates/invitation_detail_page.php
I removed the `if( $found )` test but it is needed to investigate the `$guest` object here.
An update to https://github.com/filesender/filesender/pull/2052
=> d3 that found test is handy because we would need it anyway to test the guest

lib/vendor/barracudanetworks/archivestream-php/src/TarArchive.php
This was reported in https://github.com/filesender/filesender/issues/2062 and debugged there. This is the result.
=> tar allow creation of tar files with 80gb files in them

scripts/client/filesender.py
Hi Team, 
Just a small change to add the empty file protection that exists in the webui into the cli. 
Currently these transfers just slowly fail, early warning makes it a little nicer for users.
I tested this with both empty files, normal files and a mix passed as a directory and had the expected behavior.
Please let me know if you have any questions.
=> Fix: add empty file error to cli

classes/data/Authentication.class.php
I recall there being some issue with varchar over 170 chars either in the index or one of the mysql storage backends. I don't recall the details but the 170 limit should be ok to differentiate the IdPs.
=> shrink this down to 170 to cover legacy indexing sizes

composer.json, composer.lock, docs/v2.0/install/index.md
The php-cs-fixer is only needed for the rare reforatting of code. That was seen as something needed at some stage. At any rate that should only need to be installed on a development machine.
The sauce/sausage package is not used now. The selenium tests are run through codeception. codeception can handle doing remote code runs.
The sauce/sausage had become untenable as it forced older versions of phpunit which can not be used in the GHA environment in the modern day.
The docs are updated as composer will install all items by default but in an installation env we only want the --no-dev packages installed.
=> Move development only packages to requre-dev & docs update

classes/auth/Auth.class.php, classes/data/Recipient.class.php, classes/data/Transfer.class.php, classes/data/User.class.php, templates/statistics_page.php, www/js/graph/statistics_data_per_day_graph.php, www/js/graph/statistics_encryption_split_graph.php, www/js/graph/statistics_transfers_speeds_graph.php, www/js/graph/statistics_transfers_vouchers_graph.php, www/lib/tables/statistics_page.php
As the database might have null for the idp the code should probably handle the null case anyway. This way we either now (or know and have permission to use) the idp or we have to fall back if it is null.
This relates to https://github.com/filesender/filesender/pull/2099
=> Move $idp to use null if not defined or in use.

classes/data/DBObject.class.php, classes/data/Transfer.class.php
The auths.id can not be used directly, it needs to be accessed through user.authid.
This relates to https://github.com/filesender/filesender/pull/2099
=> Use a view with group by on idp for disk usage

classes/data/Transfer.class.php
It is a nice day when there is a name clash because two people are working to improve some code. We can keep both views as they are very low cost to have.
There was a similar view brought in with https://github.com/filesender/filesender/pull/2108
=> Rename this view to avoid a name clash with new PR

docs/v3.0/admin/configuration/index.md
If this new setting is changed then migration will have to happen manually if old files are to be discoverable.
This relates to https://github.com/filesender/filesender/pull/2118
=> docs: warning about migration

classes/data/File.class.php, classes/storage/StorageFilesystem.class.php, docs/v3.0/admin/configuration/index.md, includes/ConfigDefaults.php
New option to allow the path from storage to be stored per file in the database. This is the first step towards allowing various settings like per day buckets and idp in the storage path to be changed and existing files continue to be downloadable.
This PR only optionally stores the path. A future PR will allow that information to be used and this allow storage settings to change and existing files (uploaded with this new
storage_filesystem_explicitly_store_subpath_per_file enabled) to continue to be downloaded in the face of settings changes.
This was inspired by https://github.com/filesender/filesender/pull/2119
=> Possible to save storage subpath in database for easier migration.

docs/v3.0/admin/configuration/index.md, includes/ConfigDefaults.php
* Document changed defaults for language switcher 
* Revert default changes where there is no clear benefit: `upload_display_bits_per_sec`, `upload_display_per_file_stats` and `admin_can_view_user_transfers_page` had their defaults changed in an earlier PR, but there seems no added benefit
Fixes #1650
=> 3.0rc defaults update

classes/auth/AuthSPSaml.class.php
The cron jobs are not executed via an HTTP request so they do not have this key set in the _SERVER variable. Without it the default of localhost might be used by SSP because it is expecting to be called from an HTTP request in php.
=> Set the HTTP_HOST so that SimpleSAMLphp has the FQDN

www/js/zip64handler.js
This relates to https://github.com/filesender/filesender/issues/2161
=> fix for larger encrypted downloads to zip64 files

classes/rest/endpoints/RestEndpointTransfer.class.php
In line with the remarks in #1555 and as a followup of #1569 this removes the need for users to be authenticated to access the filelist.
Use case: An authenticated user, for example a researcher, creates a transfer and allows anonymous download by sharing the download link to his newest paper on his blog.
Why the change:
Any anonymous user that is intended to download a transfer because he is the bearer of the needed token can now obtain details about the filelist, so further download of files via the REST API is possible.
Because an anonymous user can only authenticate themselves by the token, the need to be authenticated to FileSender in addition to presenting the token is odd.
As an alternative, we could make this a configurable, but I'm unsure if anyone would even be able to meet the …
=> Allow anonymous access to the filelist of a transfer

classes/data/File.class.php, classes/data/Transfer.class.php, classes/storage/Storage.class.php, classes/storage/StorageCloudAzure.class.php, classes/storage/StorageCloudS3.class.php, classes/storage/StorageFilesystem.class.php, classes/storage/StorageFilesystemChunked.class.php, classes/storage/StorageFilesystemChunkedStream.class.php, classes/utils/Config.class.php, codeception.yml, scripts/upgrade/database.php, templates/download_page.php, templates/transfers_table.php, unittests/codeception/Support/Page/Acceptance/FileSender.php, unittests/codeception/accept-dialog.sh, unittests/codeception/acceptance.suite.yml, unittests/codeception/acceptance/ConfigurationABCest.php, unittests/codeception/bootstrap.php, unittests/codeception/fix-download-permissions.sh, www/download.php, www/filesender-config.js.php, www/js/crypter/archive_sink.js, www/js/crypter/crypto_app.js, www/js/crypter/crypto_blob_reader.js, www/js/download_page.js, www/js/terasender/terasender_worker.js, www/js/transfers_table.js
With this you should be able to change the config.php upload_chunk_size (with upload_crypted_chunk_size and download_chunk_size to allow a valid configuration) and still be able to download existing uploads with new uploads performed using the current settings.
This PR has been tested manually and with the new
ConfigurationABCest.php acceptance test. The acceptance test targets both the normal filesystem and filesystemChunked storage_type and varies the chunk size in an A,B,A test with uploads in A, downloads in B then uploads in B and downloads in A for two configurations. These automatic tests check for unencrypted, encrypted, and encrypted to zip transfer scenarios. See testConfigurationAB for details.
Some testing has also been performed using a fake S3 backend and chunk size changes. …
=> updated chunk vary

www/js/ui.js
This makes the buttons the right colour, translates them, and makes an email address required in order to positively process the dialog.
=> Improve transfer details page for add recipient

templates/user_page.php, www/css/new-ui/components/_list.css
There are many UI elements that have issues. This is one case where the text was truncated from view by the button. These are not the sorts of things one would expect to see in the 202x era of web design.
This is not a perfect soluion to the problem. The new listx style sort of relies on there being a button on the left and a description type element on the right. I would have much preferred to use a toolkit that better supports web forms or not have built things in a flex just to add some buttons.
This was reported here https://github.com/filesender/filesender/issues/2181
=> UI3: Allow these two buttons on the my profile page to be seen

templates/transfer_detail_page.php
These strings appear ok on the English page but should be translated to the user's preference instead of forced in English
This relates to https://github.com/filesender/filesender/issues/2187
=> UI3: Translate these strings

templates/transfer_detail_page.php, www/js/transfer_detail_page.js, www/js/ui.js
On the transfer details page if we keep the metadata correct when an extension is performed then we can have valid data without having to resort to reloading the page. This brings the transfer details page extension functionality inline with the existing transfers table functionality.
This relates to https://github.com/filesender/filesender/issues/2179
=> UI3: update the metadata around extensions on the transfer details

templates/upload_page.php, www/js/upload_page.js
I don't like https://github.com/filesender/filesender/pull/2175 so made it use red border
Also fixed a typeO on the "from" input line that was labeled as "to"
=> UI3: "Send transfer to" use red border rather than * mandatory

classes/data/Authentication.class.php, classes/data/File.class.php, classes/data/Guest.class.php, classes/data/Recipient.class.php, classes/data/StatLog.class.php, classes/data/Transfer.class.php, classes/data/User.class.php
The database schema has largely remained identical between 2.x and 3.x. This was a deliberate effort to help allow sites to migrate from 2.x to 3.x installations. Some recent changes in 3.x added new columns and views which might be useful to backport so that the database update script will to nothing when switching between matching 2.x and 3.x release versions.
The extended functionality that is based on these new database columns doesn't need to be in the 2.x series. Only the columns themselves need to be in 2.x in order to allow quick switching (no database script) on matching `2.x <---> 3.x` releases again.
This relates to https://github.com/filesender/filesender/issues/2192.
=> updates for database stuff from recent 3.x series changes

scripts/task/cron.php
There are moments when even forcibly deleting causes failures, and causes cron to abort.
This adds a small handler in these cases. You are not 100% sure the file is deleted, but you have a warning in your logs and cron finishes.
=> fix: Be nicer when deletions fail in cron

classes/rest/endpoints/RestEndpointTransfer.class.php, scripts/client/filesender.py
Hey team, we had some users request the ability to easily download files in filesender.py. 
It doesn't require a configuration to be downloaded so it's a bit easier to use.
Currently this supports serial downloading of normal transfers and encrypted transfers if the server is using aes-gcm. 
- Enable anonymous access to the extended file transfer endpoint to match https://github.com/filesender/filesender/pull/2165. to enabled sub directories correctly and encrypted transfer downloads.
- Change in required argument parsing in the script to enable either the previous upload parameters or a new -d download parameter. 
- Adds a -d argument to filesender.py that takes in a download link for any file sender server and saves the contents of the transfer locally.
`python filesender.py -d …
=> Add download functionality to filesender.py

.github/workflows/ci.yml, ci/scripts/postgresql-setup.sh, ci/setup-machine.sh, scripts/task/cron.php
IIRC mariadb was locked back at 10.2 because there were some issues with that older version and views. But that was a long time ago so we shouldn't be locked there any more.
=> update gha ubuntu version

templates/exception_page.php, www/download.php
Depending on server config and limits it was possible for a bad actor or a bugged user to fill its session with 100s of download exceptions as this storage was not purged. This patch limits the number of stored exceptions to 5 in order to try to mitigate this issue.
=> Patch download exceptions to limit the number of session-stored exceptions

templates/transfer_detail_page.php, www/js/transfer_detail_page.js
This new page is extremely similar to the download page. This updates that new page to also perform well when the chunk size is varied.
=> Update for chunk size vary for transfer details page

classes/autoload.php, classes/data/PublicKey.class.php
I am rechecking that the database schema for 2.x and 3.x is the same again. There was some recent drift between the two which would prevent a 3.x installation from running against a database made with FileSender 2.x. Since the drift is not large I am reinstating the ability to migrate the database in that way.
Note that the PK class being in the 2.x series does not mean any of the functionality is available. It only means that the database elements should be the same.
=> Backport these to allow the database script to find them

scripts/upgrade/database.php
Much easier to make this when there is no data. Also helps keep the two schemas close.
=> Public key backport. Make the FK from the start too.

classes/auth/Auth.class.php, classes/data/Guest.class.php, classes/data/Recipient.class.php, classes/data/Transfer.class.php, classes/data/User.class.php, templates/statistics_page.php, www/css/default.css, www/js/graph/statistics_data_per_day_graph.php, www/js/graph/statistics_encryption_split_graph.php, www/js/graph/statistics_transfers_speeds_graph.php, www/js/graph/statistics_transfers_vouchers_graph.php, www/lib/tables/statistics_page.php
- use idpid rather than entityid
- CSS fix for long names
- fix some broken SQLs
- update some views to include idpid for the ones that were missing it
Note: some views can probably be reduced to remove entityid and perhaps other fields to make things tighter
=> use idpid rather than entityid + CSS fix + fix some broken SQLs

classes/storage/StorageFilesystem.class.php
examples:
```
https://sts.windows.net/42fca927-ac28-48ba-bab0-2fde21a517f4/ => sts_windows_net_42fca927_ac28_48ba_bab0_2fde21a517f4
https://shibboleth.somewhere/idp/shibboleth => shibboleth_somewhere_idp_shibboleth
urn:mace:federation.org.somewhere:testfed:somewhere-idp.somewhere.something => urn_mace_federation_org_somewhere_testfed_somewhere_idp_somewhere_something
```
=> filter out http and trailing / from path name

classes/data/Transfer.class.php, docs/v3.0/admin/configuration/index.md, includes/ConfigDefaults.php
The flag `send_owner_autoreminder` was set to true by default, only to be turned off when private guests feature was turned on.
This causes every transfer owner to be sent a receipt of every automatic reminder, which causes a flood of mail when many transfers/guests are active for a user, triggering spam protection mechanisms. 
This PR makes this configurable, defaulting to `True` for backward compatibility.
=> fix: make sending of autoreminders to transfer owners configurable

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/user_page.php, www/js/theme.js
Some issues with themes have been reported. Some sites disable them by defualt. Perhaps we should make that the default until the themese have been updated a little bit.
It is best not to present a UI being "unable to log in and unable to upload files". Also a catch22, if you can not login then you can not change your theme.
=> D3UI3 disable user theme until it is updated.

classes/storage/StorageCloudAzure.class.php, classes/storage/StorageCloudS3.class.php
While it would be better to check how much storage the back end has available, assuming things are ok and relying on other quota code (eg, user upload size) to enforce limits is better than failing here depending on how much spage is available on the local disk.
This was reported here https://github.com/filesender/filesender/issues/2291
=> Cloud: apply no limits to available storage

classes/data/User.class.php, classes/rest/RestRequest.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, classes/utils/Lang.class.php, templates/transfers_table.php
Updates for PHP 8.4 as raised here https://github.com/filesender/filesender/issues/2140
User.php can not directly use Lang::getCode as that will call back into $user->lang and start some loops.
The transfers table update doesn't really change much (float rounding) but it does remove many lines from the logs when you have
```
error_reporting = E_ALL
```
=> php 8.4 deprecation updates

docs/v2.0/cloud/index.md, docs/v3.0/cloud/index.md
This documents the behaviour mentioned in #2291 and sheds a bit of light into why filesender will use PHP's temp space (which defaults to `$TMPDIR` in many cases) when you enable a CloudS3 storage backend.
=> Document usage of php temp-dir for s3 cloud backend better

classes/auth/AuthSPSaml.class.php, classes/autoload.php, classes/data/Transfer.class.php
If the idp is null we shouldn't pass it to trim
We need to be able to lookup that exception
If we want to pass that view to fetchFromViewForId() it must be a left join to ensure transfer.id lookup will work even if there is no idp information for that particular transfer.
=> First of the post development merge updates

www/js/crypter/crypto_app.js
The evt.lengthComputable is false on osx/safari. This leads to the progressbar not being updated in the UI. The code doesn't actually need to use the total size from the evt message so if there is some indication of what is done we can update the progress anyway.
This should allow a nice download progress message on OSX/Safari.
Tested in an A/B on the current version of macos/safari as of today.
=> UX: On OSX/Safari it seems lengthComputable is not set.

scripts/client/FilesenderRestClient.class.php
Because 1 (true) caused an error in curl 7.28.1 and later
=> fix: set 2 to CURLOPT_SSL_VERIFYHOST

www/js/crypter/crypto_app.js
A follow up to https://github.com/filesender/filesender/pull/2327
=> d3: set the crypto_encrypted_archive_download in the Zip method too

docs/v2.0/admin/configuration/index.md, scripts/task/import-idp-metadata.php
This is an update to my initial update for
https://github.com/filesender/filesender/issues/2334
With this the admin has a potential option to populate the IdPs table with metadata about the IdPs that are available in their Shibboleth SP setup.
This is only tested on a small local setup. More work and updates are likely to be needed for a live setup with real data.
=> Auth shibboleth: add IdP import codepath for shibboleth

scripts/client/filesender.py
Fixes #2341
Clidownload.php was replacing one too many [base_url] instances in filesender.py, thus messing up --base_url argument mandatory status, this uses concatenation to "hide" the specific instance of [base_url] from the str_replace in clidownload.php
=> Fix filesender.py so that it doesn't get messed up by clidownload.php

classes/utils/Config.class.php, docs/v2.0/admin/configuration/index.md
A new auth_config_additional_regex_files config key that matches against the whole array (one at a time) for the picked attributes.
Perhaps we should also add at some stage a "sort" type key to allow the provided array to be sorted so that the order that multiple matching config files is applied is determined explicitly. For example, student and employee we might like the student to sort first so that the employee config can be more permissive or have a larger quota.
=> Config: SAML additional attriubtes to config

classes/utils/Args.class.php, scripts/StorageFilesystemForward/forward-MMCFTP.php, scripts/StorageFilesystemForward/forward-REST.php, scripts/StorageFilesystemForward/forward-SCP.php, scripts/task/S3bucketmaintenance.php, scripts/task/cron.php
More of a cleanup on the util method `getBoolArg` following  https://github.com/filesender/filesender/pull/2365
=> Lift getBoolArg into the Args util class

templates/upload_page.php, www/js/upload_page.js
When forward is enabled in advanced transfer settings and user selects "a transfer link" the forward heading is shown which it shouldn't.
=> tiny forward UX fix

templates/new_invitation_page.php, templates/upload_page.php
The UI3 sent to some hard coded values for these. For some installations using
ui_use_datepicker_for_transfer_expire_time_selection could allow a mitigation for this functionality. If the direct drop down (default) is desired this PR will move towards respecting the configured values again.
This relates to https://github.com/filesender/filesender/issues/1576
=> ui3: respect transfer_days_valid range and guest_days_valid

classes/exceptions/BadExceptions.class.php, classes/rest/endpoints/RestEndpointTransfer.class.php, docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php
The code was ignoring options which were `!available` but were set by the client. The new code does the same thing but also throws if the client has tried to supply a value to an option which should not have been available to the user.
This investigates and resolves https://github.com/filesender/filesender/issues/498
=> validation: check the user doesn't try to sneak a value

www/js/crypter/crypto_app.js
When many smaller files are uploaded with encryption the pbkdf2 key cache uses more parameters than are needed in the cache key. This PR reduces that to only parameters that are used in the key derivation process.
This was raised here https://github.com/filesender/filesender/issues/2396
=> use only the values that generatekey relies on for the cache key

www/js/transfer_detail_page.js
This PR will avoid mangling the auditlog popup leaving it at a size that is large enough and without creating duplicate windows.
This was reported here https://github.com/filesender/filesender/issues/2399
=> UI3: do not mangle the auditlog popup window

classes/data/File.class.php
This addresses https://github.com/filesender/filesender/issues/2407
For postgresql leaving the uid column as a string the index for 0.5m files is about 58mb. Using the native uuid type for a column that is a copy of the uid column the same index is 17mb. So a migration to the native uuid types in mariadb and postgresql is probably a good idea at some stage.
=> db: add an index on files.uid

classes/constants/DatabaseSchemaVersions.class.php, classes/data/File.class.php, classes/utils/Logger.class.php, includes/ConfigDefaults.php, scripts/upgrade/database.php, templates/transfers_table.php
This offers significant performance improvements for a my transfers page with transfers containing 10,000 files each. If you have a number of such transfers the load time on that page might got from 2 minutes to less than 10 seconds.
The migration might take a moment as it will run this somewhat expensive query on the auditlog table to find out how many downloads have happened for each file in the database. It is much, much more efficient to precache that count so it is worth doing this the one time for the pleasure of faster load times from then on out.
This relates to https://github.com/filesender/filesender/issues/2405 but does not include the transfer_id (trid) value in the auditlog as yet. That will be a subsequent investigation.
Note that you will have to run the database.php script …
=> db: precache files.download_count

docs/v2.0/admin/configuration/index.md, includes/ConfigDefaults.php, templates/transfers_table.php
One might consider setting
large_transfer_handling_maximum_files_to_show_inline_on_my_transfers_page to something like 1000
For me, for a page with many 10,000 file transfers I might see 5 second load times without a limit and less than 2 seconds with one.
The limit might be useful if you plan to regularly make transfers with 1 to 10 million files in them.
All the files are there, the my transfers page just doesn't show them explicitly in the expanded transfer in the table.
I moved the `Template::Q` calls out so that one call can service 2 sites. Quoting like that is expensive when you are doing it millions of times.
=> manyfiles: improved performance on my transfers, new limit option

classes/utils/Utilities.class.php
Again, for 10000 files this call can add up and be responsible for say 2% of the overall execution time. Plus it is a waste of time to do it many times anyway. Save those electrons.
=> perf: only do that lang::tr once per run
